// Code generated by ent, DO NOT EDIT.

package prcommitusagesnapshot

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the prcommitusagesnapshot type in the database.
	Label = "pr_commit_usage_snapshot"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldPrRecordID holds the string denoting the pr_record_id field in the database.
	FieldPrRecordID = "pr_record_id"
	// FieldCommitSha holds the string denoting the commit_sha field in the database.
	FieldCommitSha = "commit_sha"
	// FieldCommitCheckpointID holds the string denoting the commit_checkpoint_id field in the database.
	FieldCommitCheckpointID = "commit_checkpoint_id"
	// FieldCapturedAt holds the string denoting the captured_at field in the database.
	FieldCapturedAt = "captured_at"
	// FieldInputTokens holds the string denoting the input_tokens field in the database.
	FieldInputTokens = "input_tokens"
	// FieldOutputTokens holds the string denoting the output_tokens field in the database.
	FieldOutputTokens = "output_tokens"
	// FieldCachedInputTokens holds the string denoting the cached_input_tokens field in the database.
	FieldCachedInputTokens = "cached_input_tokens"
	// FieldReasoningTokens holds the string denoting the reasoning_tokens field in the database.
	FieldReasoningTokens = "reasoning_tokens"
	// FieldCreditUsage holds the string denoting the credit_usage field in the database.
	FieldCreditUsage = "credit_usage"
	// FieldRequestCount holds the string denoting the request_count field in the database.
	FieldRequestCount = "request_count"
	// FieldSortOrder holds the string denoting the sort_order field in the database.
	FieldSortOrder = "sort_order"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgePrRecord holds the string denoting the pr_record edge name in mutations.
	EdgePrRecord = "pr_record"
	// EdgeCommitCheckpoint holds the string denoting the commit_checkpoint edge name in mutations.
	EdgeCommitCheckpoint = "commit_checkpoint"
	// Table holds the table name of the prcommitusagesnapshot in the database.
	Table = "pr_commit_usage_snapshots"
	// PrRecordTable is the table that holds the pr_record relation/edge.
	PrRecordTable = "pr_commit_usage_snapshots"
	// PrRecordInverseTable is the table name for the PrRecord entity.
	// It exists in this package in order to avoid circular dependency with the "prrecord" package.
	PrRecordInverseTable = "pr_records"
	// PrRecordColumn is the table column denoting the pr_record relation/edge.
	PrRecordColumn = "pr_record_id"
	// CommitCheckpointTable is the table that holds the commit_checkpoint relation/edge.
	CommitCheckpointTable = "pr_commit_usage_snapshots"
	// CommitCheckpointInverseTable is the table name for the CommitCheckpoint entity.
	// It exists in this package in order to avoid circular dependency with the "commitcheckpoint" package.
	CommitCheckpointInverseTable = "commit_checkpoints"
	// CommitCheckpointColumn is the table column denoting the commit_checkpoint relation/edge.
	CommitCheckpointColumn = "commit_checkpoint_id"
)

// Columns holds all SQL columns for prcommitusagesnapshot fields.
var Columns = []string{
	FieldID,
	FieldPrRecordID,
	FieldCommitSha,
	FieldCommitCheckpointID,
	FieldCapturedAt,
	FieldInputTokens,
	FieldOutputTokens,
	FieldCachedInputTokens,
	FieldReasoningTokens,
	FieldCreditUsage,
	FieldRequestCount,
	FieldSortOrder,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// CommitShaValidator is a validator for the "commit_sha" field. It is called by the builders before save.
	CommitShaValidator func(string) error
	// DefaultInputTokens holds the default value on creation for the "input_tokens" field.
	DefaultInputTokens int64
	// DefaultOutputTokens holds the default value on creation for the "output_tokens" field.
	DefaultOutputTokens int64
	// DefaultCachedInputTokens holds the default value on creation for the "cached_input_tokens" field.
	DefaultCachedInputTokens int64
	// DefaultReasoningTokens holds the default value on creation for the "reasoning_tokens" field.
	DefaultReasoningTokens int64
	// DefaultCreditUsage holds the default value on creation for the "credit_usage" field.
	DefaultCreditUsage float64
	// DefaultRequestCount holds the default value on creation for the "request_count" field.
	DefaultRequestCount int
	// DefaultSortOrder holds the default value on creation for the "sort_order" field.
	DefaultSortOrder int
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the PRCommitUsageSnapshot queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByPrRecordID orders the results by the pr_record_id field.
func ByPrRecordID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPrRecordID, opts...).ToFunc()
}

// ByCommitSha orders the results by the commit_sha field.
func ByCommitSha(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCommitSha, opts...).ToFunc()
}

// ByCommitCheckpointID orders the results by the commit_checkpoint_id field.
func ByCommitCheckpointID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCommitCheckpointID, opts...).ToFunc()
}

// ByCapturedAt orders the results by the captured_at field.
func ByCapturedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCapturedAt, opts...).ToFunc()
}

// ByInputTokens orders the results by the input_tokens field.
func ByInputTokens(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInputTokens, opts...).ToFunc()
}

// ByOutputTokens orders the results by the output_tokens field.
func ByOutputTokens(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOutputTokens, opts...).ToFunc()
}

// ByCachedInputTokens orders the results by the cached_input_tokens field.
func ByCachedInputTokens(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCachedInputTokens, opts...).ToFunc()
}

// ByReasoningTokens orders the results by the reasoning_tokens field.
func ByReasoningTokens(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReasoningTokens, opts...).ToFunc()
}

// ByCreditUsage orders the results by the credit_usage field.
func ByCreditUsage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreditUsage, opts...).ToFunc()
}

// ByRequestCount orders the results by the request_count field.
func ByRequestCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequestCount, opts...).ToFunc()
}

// BySortOrder orders the results by the sort_order field.
func BySortOrder(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSortOrder, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByPrRecordField orders the results by pr_record field.
func ByPrRecordField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newPrRecordStep(), sql.OrderByField(field, opts...))
	}
}

// ByCommitCheckpointField orders the results by commit_checkpoint field.
func ByCommitCheckpointField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCommitCheckpointStep(), sql.OrderByField(field, opts...))
	}
}
func newPrRecordStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(PrRecordInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, PrRecordTable, PrRecordColumn),
	)
}
func newCommitCheckpointStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CommitCheckpointInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, CommitCheckpointTable, CommitCheckpointColumn),
	)
}
