import type { Locale } from '@/i18n'

const text = {
  'en-US': {
    eyebrow: 'AI Coding Activity reporting',
    title: 'Report Codex coding activity',
    fullDescription: 'This Codex HTTP reporting flow is separate from API keys and access groups. It attributes accepted Token to committed code.',
    normalTitle: 'Normal setup',
    normalHelp: 'Install the CLI, sign in, then let discover configure supported tools and managed global hooks.',
    install: '1. Install ae-cli',
    login: '2. Sign in',
    discover: '3. Configure supported tools',
    advancedTitle: 'Advanced command reference',
    advancedHelp: 'Diagnostics and recovery commands for troubleshooting. They are not required during normal setup.',
    statusCommand: 'Show reporting status',
    doctorCommand: 'Check the local environment',
    syncCommand: 'Retry pending uploads now',
    uploadsCommand: 'Inspect upload and hook state',
    repoCommand: 'Install repository-local hooks',
    repoFallback: 'Use repo-local init only when managed global hooks are unavailable.',
    loading: 'Checking reporting status…',
    loadFailed: 'Reporting status is temporarily unavailable. Activity analytics remain available.',
    retry: 'Retry status',
    openSetup: 'Open the complete setup guide',
    copy: 'Copy',
    copied: 'Copied',
    copyFailed: 'Could not copy the command. Select it manually.',
    not_enrolledTitle: 'Reporting is not connected yet',
    not_enrolledDescription: 'Complete the normal setup below. Reporting activates automatically; no separate enable command is required.',
    revokedTitle: 'Reporting access has been revoked',
    revokedDescription: 'This installation cannot reactivate itself. Contact an administrator, then sign in again after access is restored.',
    disabledTitle: 'Reporting is paused',
    disabledDescription: 'Run the normal sign-in and discover flow again. Use advanced diagnostics only if automatic recovery does not complete.',
    waiting_for_dataTitle: 'Waiting for the first accepted commit',
    waiting_for_dataDescription: 'Setup is ready. Use Codex, commit the resulting code, and managed hooks will upload eligible evidence automatically.',
    activeTitle: 'Codex activity reporting is active',
    activeDescription: 'Accepted committed activity is available in AI Coding Activity.',
    latestAccepted: 'Latest accepted activity',
  },
  'zh-CN': {
    eyebrow: 'AI 开发动态上报',
    title: '上报 Codex 编码活动',
    fullDescription: 'Codex HTTP 上报流程独立于 API 密钥和接入组，用于将已接收的 Token 归因到已提交代码。',
    normalTitle: '正常接入',
    normalHelp: '安装 CLI、登录，再由 discover 配置受支持工具和托管的全局 hooks。',
    install: '1. 安装 ae-cli',
    login: '2. 登录',
    discover: '3. 配置受支持工具',
    advancedTitle: '高级命令参考',
    advancedHelp: '仅在排查或恢复时使用，正常接入无需执行。',
    statusCommand: '查看上报状态',
    doctorCommand: '检查本地环境',
    syncCommand: '立即重试待上传数据',
    uploadsCommand: '检查上传和 hook 状态',
    repoCommand: '安装仓库级 hooks',
    repoFallback: '仅在托管的全局 hooks 不可用时使用仓库级 init。',
    loading: '正在检查上报状态…',
    loadFailed: '上报状态暂时不可用，开发动态分析不受影响。',
    retry: '重试状态',
    openSetup: '查看完整接入教程',
    copy: '复制',
    copied: '已复制',
    copyFailed: '复制失败，请手动选择命令。',
    not_enrolledTitle: '尚未接入上报',
    not_enrolledDescription: '按下方正常流程完成接入。上报会自动开启，不需要单独执行 enable 命令。',
    revokedTitle: '上报权限已撤销',
    revokedDescription: '当前安装无法自行恢复。请联系管理员恢复权限后重新登录。',
    disabledTitle: '上报已暂停',
    disabledDescription: '重新执行正常的登录和 discover 流程；仅在自动恢复未完成时使用高级诊断。',
    waiting_for_dataTitle: '等待首个已接收的提交',
    waiting_for_dataDescription: '接入已就绪。使用 Codex 并提交代码后，托管 hooks 会自动上传符合条件的证据。',
    activeTitle: 'Codex 开发动态上报正常',
    activeDescription: '已接收的提交活动可在 AI 开发动态中查看。',
    latestAccepted: '最近接收活动',
  },
} as const

export type ReportingTextKey = keyof typeof text['en-US']

export function reportingText(locale: Locale, key: ReportingTextKey) {
  return text[locale][key]
}
