// Code generated by ent, DO NOT EDIT.

package relationshipoperation

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/ai-efficiency/backend/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.RelationshipOperation {
	return predicate.RelationshipOperation(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.RelationshipOperation {
	return predicate.RelationshipOperation(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.RelationshipOperation {
	return predicate.RelationshipOperation(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.RelationshipOperation {
	return predicate.RelationshipOperation(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.RelationshipOperation {
	return predicate.RelationshipOperation(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.RelationshipOperation {
	return predicate.RelationshipOperation(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.RelationshipOperation {
	return predicate.RelationshipOperation(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.RelationshipOperation {
	return predicate.RelationshipOperation(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.RelationshipOperation {
	return predicate.RelationshipOperation(sql.FieldLTE(FieldID, id))
}

// OperationKey applies equality check predicate on the "operation_key" field. It's identical to OperationKeyEQ.
func OperationKey(v string) predicate.RelationshipOperation {
	return predicate.RelationshipOperation(sql.FieldEQ(FieldOperationKey, v))
}

// ProviderID applies equality check predicate on the "provider_id" field. It's identical to ProviderIDEQ.
func ProviderID(v int) predicate.RelationshipOperation {
	return predicate.RelationshipOperation(sql.FieldEQ(FieldProviderID, v))
}

// Platform applies equality check predicate on the "platform" field. It's identical to PlatformEQ.
func Platform(v string) predicate.RelationshipOperation {
	return predicate.RelationshipOperation(sql.FieldEQ(FieldPlatform, v))
}

// BaselineFingerprint applies equality check predicate on the "baseline_fingerprint" field. It's identical to BaselineFingerprintEQ.
func BaselineFingerprint(v string) predicate.RelationshipOperation {
	return predicate.RelationshipOperation(sql.FieldEQ(FieldBaselineFingerprint, v))
}

// TargetFingerprint applies equality check predicate on the "target_fingerprint" field. It's identical to TargetFingerprintEQ.
func TargetFingerprint(v string) predicate.RelationshipOperation {
	return predicate.RelationshipOperation(sql.FieldEQ(FieldTargetFingerprint, v))
}

// InitiatedByUserID applies equality check predicate on the "initiated_by_user_id" field. It's identical to InitiatedByUserIDEQ.
func InitiatedByUserID(v int) predicate.RelationshipOperation {
	return predicate.RelationshipOperation(sql.FieldEQ(FieldInitiatedByUserID, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.RelationshipOperation {
	return predicate.RelationshipOperation(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.RelationshipOperation {
	return predicate.RelationshipOperation(sql.FieldEQ(FieldUpdatedAt, v))
}

// CompletedAt applies equality check predicate on the "completed_at" field. It's identical to CompletedAtEQ.
func CompletedAt(v time.Time) predicate.RelationshipOperation {
	return predicate.RelationshipOperation(sql.FieldEQ(FieldCompletedAt, v))
}

// OperationKeyEQ applies the EQ predicate on the "operation_key" field.
func OperationKeyEQ(v string) predicate.RelationshipOperation {
	return predicate.RelationshipOperation(sql.FieldEQ(FieldOperationKey, v))
}

// OperationKeyNEQ applies the NEQ predicate on the "operation_key" field.
func OperationKeyNEQ(v string) predicate.RelationshipOperation {
	return predicate.RelationshipOperation(sql.FieldNEQ(FieldOperationKey, v))
}

// OperationKeyIn applies the In predicate on the "operation_key" field.
func OperationKeyIn(vs ...string) predicate.RelationshipOperation {
	return predicate.RelationshipOperation(sql.FieldIn(FieldOperationKey, vs...))
}

// OperationKeyNotIn applies the NotIn predicate on the "operation_key" field.
func OperationKeyNotIn(vs ...string) predicate.RelationshipOperation {
	return predicate.RelationshipOperation(sql.FieldNotIn(FieldOperationKey, vs...))
}

// OperationKeyGT applies the GT predicate on the "operation_key" field.
func OperationKeyGT(v string) predicate.RelationshipOperation {
	return predicate.RelationshipOperation(sql.FieldGT(FieldOperationKey, v))
}

// OperationKeyGTE applies the GTE predicate on the "operation_key" field.
func OperationKeyGTE(v string) predicate.RelationshipOperation {
	return predicate.RelationshipOperation(sql.FieldGTE(FieldOperationKey, v))
}

// OperationKeyLT applies the LT predicate on the "operation_key" field.
func OperationKeyLT(v string) predicate.RelationshipOperation {
	return predicate.RelationshipOperation(sql.FieldLT(FieldOperationKey, v))
}

// OperationKeyLTE applies the LTE predicate on the "operation_key" field.
func OperationKeyLTE(v string) predicate.RelationshipOperation {
	return predicate.RelationshipOperation(sql.FieldLTE(FieldOperationKey, v))
}

// OperationKeyContains applies the Contains predicate on the "operation_key" field.
func OperationKeyContains(v string) predicate.RelationshipOperation {
	return predicate.RelationshipOperation(sql.FieldContains(FieldOperationKey, v))
}

// OperationKeyHasPrefix applies the HasPrefix predicate on the "operation_key" field.
func OperationKeyHasPrefix(v string) predicate.RelationshipOperation {
	return predicate.RelationshipOperation(sql.FieldHasPrefix(FieldOperationKey, v))
}

// OperationKeyHasSuffix applies the HasSuffix predicate on the "operation_key" field.
func OperationKeyHasSuffix(v string) predicate.RelationshipOperation {
	return predicate.RelationshipOperation(sql.FieldHasSuffix(FieldOperationKey, v))
}

// OperationKeyEqualFold applies the EqualFold predicate on the "operation_key" field.
func OperationKeyEqualFold(v string) predicate.RelationshipOperation {
	return predicate.RelationshipOperation(sql.FieldEqualFold(FieldOperationKey, v))
}

// OperationKeyContainsFold applies the ContainsFold predicate on the "operation_key" field.
func OperationKeyContainsFold(v string) predicate.RelationshipOperation {
	return predicate.RelationshipOperation(sql.FieldContainsFold(FieldOperationKey, v))
}

// ProviderIDEQ applies the EQ predicate on the "provider_id" field.
func ProviderIDEQ(v int) predicate.RelationshipOperation {
	return predicate.RelationshipOperation(sql.FieldEQ(FieldProviderID, v))
}

// ProviderIDNEQ applies the NEQ predicate on the "provider_id" field.
func ProviderIDNEQ(v int) predicate.RelationshipOperation {
	return predicate.RelationshipOperation(sql.FieldNEQ(FieldProviderID, v))
}

// ProviderIDIn applies the In predicate on the "provider_id" field.
func ProviderIDIn(vs ...int) predicate.RelationshipOperation {
	return predicate.RelationshipOperation(sql.FieldIn(FieldProviderID, vs...))
}

// ProviderIDNotIn applies the NotIn predicate on the "provider_id" field.
func ProviderIDNotIn(vs ...int) predicate.RelationshipOperation {
	return predicate.RelationshipOperation(sql.FieldNotIn(FieldProviderID, vs...))
}

// ProviderIDGT applies the GT predicate on the "provider_id" field.
func ProviderIDGT(v int) predicate.RelationshipOperation {
	return predicate.RelationshipOperation(sql.FieldGT(FieldProviderID, v))
}

// ProviderIDGTE applies the GTE predicate on the "provider_id" field.
func ProviderIDGTE(v int) predicate.RelationshipOperation {
	return predicate.RelationshipOperation(sql.FieldGTE(FieldProviderID, v))
}

// ProviderIDLT applies the LT predicate on the "provider_id" field.
func ProviderIDLT(v int) predicate.RelationshipOperation {
	return predicate.RelationshipOperation(sql.FieldLT(FieldProviderID, v))
}

// ProviderIDLTE applies the LTE predicate on the "provider_id" field.
func ProviderIDLTE(v int) predicate.RelationshipOperation {
	return predicate.RelationshipOperation(sql.FieldLTE(FieldProviderID, v))
}

// PlatformEQ applies the EQ predicate on the "platform" field.
func PlatformEQ(v string) predicate.RelationshipOperation {
	return predicate.RelationshipOperation(sql.FieldEQ(FieldPlatform, v))
}

// PlatformNEQ applies the NEQ predicate on the "platform" field.
func PlatformNEQ(v string) predicate.RelationshipOperation {
	return predicate.RelationshipOperation(sql.FieldNEQ(FieldPlatform, v))
}

// PlatformIn applies the In predicate on the "platform" field.
func PlatformIn(vs ...string) predicate.RelationshipOperation {
	return predicate.RelationshipOperation(sql.FieldIn(FieldPlatform, vs...))
}

// PlatformNotIn applies the NotIn predicate on the "platform" field.
func PlatformNotIn(vs ...string) predicate.RelationshipOperation {
	return predicate.RelationshipOperation(sql.FieldNotIn(FieldPlatform, vs...))
}

// PlatformGT applies the GT predicate on the "platform" field.
func PlatformGT(v string) predicate.RelationshipOperation {
	return predicate.RelationshipOperation(sql.FieldGT(FieldPlatform, v))
}

// PlatformGTE applies the GTE predicate on the "platform" field.
func PlatformGTE(v string) predicate.RelationshipOperation {
	return predicate.RelationshipOperation(sql.FieldGTE(FieldPlatform, v))
}

// PlatformLT applies the LT predicate on the "platform" field.
func PlatformLT(v string) predicate.RelationshipOperation {
	return predicate.RelationshipOperation(sql.FieldLT(FieldPlatform, v))
}

// PlatformLTE applies the LTE predicate on the "platform" field.
func PlatformLTE(v string) predicate.RelationshipOperation {
	return predicate.RelationshipOperation(sql.FieldLTE(FieldPlatform, v))
}

// PlatformContains applies the Contains predicate on the "platform" field.
func PlatformContains(v string) predicate.RelationshipOperation {
	return predicate.RelationshipOperation(sql.FieldContains(FieldPlatform, v))
}

// PlatformHasPrefix applies the HasPrefix predicate on the "platform" field.
func PlatformHasPrefix(v string) predicate.RelationshipOperation {
	return predicate.RelationshipOperation(sql.FieldHasPrefix(FieldPlatform, v))
}

// PlatformHasSuffix applies the HasSuffix predicate on the "platform" field.
func PlatformHasSuffix(v string) predicate.RelationshipOperation {
	return predicate.RelationshipOperation(sql.FieldHasSuffix(FieldPlatform, v))
}

// PlatformEqualFold applies the EqualFold predicate on the "platform" field.
func PlatformEqualFold(v string) predicate.RelationshipOperation {
	return predicate.RelationshipOperation(sql.FieldEqualFold(FieldPlatform, v))
}

// PlatformContainsFold applies the ContainsFold predicate on the "platform" field.
func PlatformContainsFold(v string) predicate.RelationshipOperation {
	return predicate.RelationshipOperation(sql.FieldContainsFold(FieldPlatform, v))
}

// LifecycleEQ applies the EQ predicate on the "lifecycle" field.
func LifecycleEQ(v Lifecycle) predicate.RelationshipOperation {
	return predicate.RelationshipOperation(sql.FieldEQ(FieldLifecycle, v))
}

// LifecycleNEQ applies the NEQ predicate on the "lifecycle" field.
func LifecycleNEQ(v Lifecycle) predicate.RelationshipOperation {
	return predicate.RelationshipOperation(sql.FieldNEQ(FieldLifecycle, v))
}

// LifecycleIn applies the In predicate on the "lifecycle" field.
func LifecycleIn(vs ...Lifecycle) predicate.RelationshipOperation {
	return predicate.RelationshipOperation(sql.FieldIn(FieldLifecycle, vs...))
}

// LifecycleNotIn applies the NotIn predicate on the "lifecycle" field.
func LifecycleNotIn(vs ...Lifecycle) predicate.RelationshipOperation {
	return predicate.RelationshipOperation(sql.FieldNotIn(FieldLifecycle, vs...))
}

// BaselineFingerprintEQ applies the EQ predicate on the "baseline_fingerprint" field.
func BaselineFingerprintEQ(v string) predicate.RelationshipOperation {
	return predicate.RelationshipOperation(sql.FieldEQ(FieldBaselineFingerprint, v))
}

// BaselineFingerprintNEQ applies the NEQ predicate on the "baseline_fingerprint" field.
func BaselineFingerprintNEQ(v string) predicate.RelationshipOperation {
	return predicate.RelationshipOperation(sql.FieldNEQ(FieldBaselineFingerprint, v))
}

// BaselineFingerprintIn applies the In predicate on the "baseline_fingerprint" field.
func BaselineFingerprintIn(vs ...string) predicate.RelationshipOperation {
	return predicate.RelationshipOperation(sql.FieldIn(FieldBaselineFingerprint, vs...))
}

// BaselineFingerprintNotIn applies the NotIn predicate on the "baseline_fingerprint" field.
func BaselineFingerprintNotIn(vs ...string) predicate.RelationshipOperation {
	return predicate.RelationshipOperation(sql.FieldNotIn(FieldBaselineFingerprint, vs...))
}

// BaselineFingerprintGT applies the GT predicate on the "baseline_fingerprint" field.
func BaselineFingerprintGT(v string) predicate.RelationshipOperation {
	return predicate.RelationshipOperation(sql.FieldGT(FieldBaselineFingerprint, v))
}

// BaselineFingerprintGTE applies the GTE predicate on the "baseline_fingerprint" field.
func BaselineFingerprintGTE(v string) predicate.RelationshipOperation {
	return predicate.RelationshipOperation(sql.FieldGTE(FieldBaselineFingerprint, v))
}

// BaselineFingerprintLT applies the LT predicate on the "baseline_fingerprint" field.
func BaselineFingerprintLT(v string) predicate.RelationshipOperation {
	return predicate.RelationshipOperation(sql.FieldLT(FieldBaselineFingerprint, v))
}

// BaselineFingerprintLTE applies the LTE predicate on the "baseline_fingerprint" field.
func BaselineFingerprintLTE(v string) predicate.RelationshipOperation {
	return predicate.RelationshipOperation(sql.FieldLTE(FieldBaselineFingerprint, v))
}

// BaselineFingerprintContains applies the Contains predicate on the "baseline_fingerprint" field.
func BaselineFingerprintContains(v string) predicate.RelationshipOperation {
	return predicate.RelationshipOperation(sql.FieldContains(FieldBaselineFingerprint, v))
}

// BaselineFingerprintHasPrefix applies the HasPrefix predicate on the "baseline_fingerprint" field.
func BaselineFingerprintHasPrefix(v string) predicate.RelationshipOperation {
	return predicate.RelationshipOperation(sql.FieldHasPrefix(FieldBaselineFingerprint, v))
}

// BaselineFingerprintHasSuffix applies the HasSuffix predicate on the "baseline_fingerprint" field.
func BaselineFingerprintHasSuffix(v string) predicate.RelationshipOperation {
	return predicate.RelationshipOperation(sql.FieldHasSuffix(FieldBaselineFingerprint, v))
}

// BaselineFingerprintEqualFold applies the EqualFold predicate on the "baseline_fingerprint" field.
func BaselineFingerprintEqualFold(v string) predicate.RelationshipOperation {
	return predicate.RelationshipOperation(sql.FieldEqualFold(FieldBaselineFingerprint, v))
}

// BaselineFingerprintContainsFold applies the ContainsFold predicate on the "baseline_fingerprint" field.
func BaselineFingerprintContainsFold(v string) predicate.RelationshipOperation {
	return predicate.RelationshipOperation(sql.FieldContainsFold(FieldBaselineFingerprint, v))
}

// TargetFingerprintEQ applies the EQ predicate on the "target_fingerprint" field.
func TargetFingerprintEQ(v string) predicate.RelationshipOperation {
	return predicate.RelationshipOperation(sql.FieldEQ(FieldTargetFingerprint, v))
}

// TargetFingerprintNEQ applies the NEQ predicate on the "target_fingerprint" field.
func TargetFingerprintNEQ(v string) predicate.RelationshipOperation {
	return predicate.RelationshipOperation(sql.FieldNEQ(FieldTargetFingerprint, v))
}

// TargetFingerprintIn applies the In predicate on the "target_fingerprint" field.
func TargetFingerprintIn(vs ...string) predicate.RelationshipOperation {
	return predicate.RelationshipOperation(sql.FieldIn(FieldTargetFingerprint, vs...))
}

// TargetFingerprintNotIn applies the NotIn predicate on the "target_fingerprint" field.
func TargetFingerprintNotIn(vs ...string) predicate.RelationshipOperation {
	return predicate.RelationshipOperation(sql.FieldNotIn(FieldTargetFingerprint, vs...))
}

// TargetFingerprintGT applies the GT predicate on the "target_fingerprint" field.
func TargetFingerprintGT(v string) predicate.RelationshipOperation {
	return predicate.RelationshipOperation(sql.FieldGT(FieldTargetFingerprint, v))
}

// TargetFingerprintGTE applies the GTE predicate on the "target_fingerprint" field.
func TargetFingerprintGTE(v string) predicate.RelationshipOperation {
	return predicate.RelationshipOperation(sql.FieldGTE(FieldTargetFingerprint, v))
}

// TargetFingerprintLT applies the LT predicate on the "target_fingerprint" field.
func TargetFingerprintLT(v string) predicate.RelationshipOperation {
	return predicate.RelationshipOperation(sql.FieldLT(FieldTargetFingerprint, v))
}

// TargetFingerprintLTE applies the LTE predicate on the "target_fingerprint" field.
func TargetFingerprintLTE(v string) predicate.RelationshipOperation {
	return predicate.RelationshipOperation(sql.FieldLTE(FieldTargetFingerprint, v))
}

// TargetFingerprintContains applies the Contains predicate on the "target_fingerprint" field.
func TargetFingerprintContains(v string) predicate.RelationshipOperation {
	return predicate.RelationshipOperation(sql.FieldContains(FieldTargetFingerprint, v))
}

// TargetFingerprintHasPrefix applies the HasPrefix predicate on the "target_fingerprint" field.
func TargetFingerprintHasPrefix(v string) predicate.RelationshipOperation {
	return predicate.RelationshipOperation(sql.FieldHasPrefix(FieldTargetFingerprint, v))
}

// TargetFingerprintHasSuffix applies the HasSuffix predicate on the "target_fingerprint" field.
func TargetFingerprintHasSuffix(v string) predicate.RelationshipOperation {
	return predicate.RelationshipOperation(sql.FieldHasSuffix(FieldTargetFingerprint, v))
}

// TargetFingerprintEqualFold applies the EqualFold predicate on the "target_fingerprint" field.
func TargetFingerprintEqualFold(v string) predicate.RelationshipOperation {
	return predicate.RelationshipOperation(sql.FieldEqualFold(FieldTargetFingerprint, v))
}

// TargetFingerprintContainsFold applies the ContainsFold predicate on the "target_fingerprint" field.
func TargetFingerprintContainsFold(v string) predicate.RelationshipOperation {
	return predicate.RelationshipOperation(sql.FieldContainsFold(FieldTargetFingerprint, v))
}

// InitiatedByUserIDEQ applies the EQ predicate on the "initiated_by_user_id" field.
func InitiatedByUserIDEQ(v int) predicate.RelationshipOperation {
	return predicate.RelationshipOperation(sql.FieldEQ(FieldInitiatedByUserID, v))
}

// InitiatedByUserIDNEQ applies the NEQ predicate on the "initiated_by_user_id" field.
func InitiatedByUserIDNEQ(v int) predicate.RelationshipOperation {
	return predicate.RelationshipOperation(sql.FieldNEQ(FieldInitiatedByUserID, v))
}

// InitiatedByUserIDIn applies the In predicate on the "initiated_by_user_id" field.
func InitiatedByUserIDIn(vs ...int) predicate.RelationshipOperation {
	return predicate.RelationshipOperation(sql.FieldIn(FieldInitiatedByUserID, vs...))
}

// InitiatedByUserIDNotIn applies the NotIn predicate on the "initiated_by_user_id" field.
func InitiatedByUserIDNotIn(vs ...int) predicate.RelationshipOperation {
	return predicate.RelationshipOperation(sql.FieldNotIn(FieldInitiatedByUserID, vs...))
}

// InitiatedByUserIDGT applies the GT predicate on the "initiated_by_user_id" field.
func InitiatedByUserIDGT(v int) predicate.RelationshipOperation {
	return predicate.RelationshipOperation(sql.FieldGT(FieldInitiatedByUserID, v))
}

// InitiatedByUserIDGTE applies the GTE predicate on the "initiated_by_user_id" field.
func InitiatedByUserIDGTE(v int) predicate.RelationshipOperation {
	return predicate.RelationshipOperation(sql.FieldGTE(FieldInitiatedByUserID, v))
}

// InitiatedByUserIDLT applies the LT predicate on the "initiated_by_user_id" field.
func InitiatedByUserIDLT(v int) predicate.RelationshipOperation {
	return predicate.RelationshipOperation(sql.FieldLT(FieldInitiatedByUserID, v))
}

// InitiatedByUserIDLTE applies the LTE predicate on the "initiated_by_user_id" field.
func InitiatedByUserIDLTE(v int) predicate.RelationshipOperation {
	return predicate.RelationshipOperation(sql.FieldLTE(FieldInitiatedByUserID, v))
}

// TerminalResultIsNil applies the IsNil predicate on the "terminal_result" field.
func TerminalResultIsNil() predicate.RelationshipOperation {
	return predicate.RelationshipOperation(sql.FieldIsNull(FieldTerminalResult))
}

// TerminalResultNotNil applies the NotNil predicate on the "terminal_result" field.
func TerminalResultNotNil() predicate.RelationshipOperation {
	return predicate.RelationshipOperation(sql.FieldNotNull(FieldTerminalResult))
}

// ExternalBlockerIsNil applies the IsNil predicate on the "external_blocker" field.
func ExternalBlockerIsNil() predicate.RelationshipOperation {
	return predicate.RelationshipOperation(sql.FieldIsNull(FieldExternalBlocker))
}

// ExternalBlockerNotNil applies the NotNil predicate on the "external_blocker" field.
func ExternalBlockerNotNil() predicate.RelationshipOperation {
	return predicate.RelationshipOperation(sql.FieldNotNull(FieldExternalBlocker))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.RelationshipOperation {
	return predicate.RelationshipOperation(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.RelationshipOperation {
	return predicate.RelationshipOperation(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.RelationshipOperation {
	return predicate.RelationshipOperation(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.RelationshipOperation {
	return predicate.RelationshipOperation(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.RelationshipOperation {
	return predicate.RelationshipOperation(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.RelationshipOperation {
	return predicate.RelationshipOperation(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.RelationshipOperation {
	return predicate.RelationshipOperation(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.RelationshipOperation {
	return predicate.RelationshipOperation(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.RelationshipOperation {
	return predicate.RelationshipOperation(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.RelationshipOperation {
	return predicate.RelationshipOperation(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.RelationshipOperation {
	return predicate.RelationshipOperation(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.RelationshipOperation {
	return predicate.RelationshipOperation(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.RelationshipOperation {
	return predicate.RelationshipOperation(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.RelationshipOperation {
	return predicate.RelationshipOperation(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.RelationshipOperation {
	return predicate.RelationshipOperation(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.RelationshipOperation {
	return predicate.RelationshipOperation(sql.FieldLTE(FieldUpdatedAt, v))
}

// CompletedAtEQ applies the EQ predicate on the "completed_at" field.
func CompletedAtEQ(v time.Time) predicate.RelationshipOperation {
	return predicate.RelationshipOperation(sql.FieldEQ(FieldCompletedAt, v))
}

// CompletedAtNEQ applies the NEQ predicate on the "completed_at" field.
func CompletedAtNEQ(v time.Time) predicate.RelationshipOperation {
	return predicate.RelationshipOperation(sql.FieldNEQ(FieldCompletedAt, v))
}

// CompletedAtIn applies the In predicate on the "completed_at" field.
func CompletedAtIn(vs ...time.Time) predicate.RelationshipOperation {
	return predicate.RelationshipOperation(sql.FieldIn(FieldCompletedAt, vs...))
}

// CompletedAtNotIn applies the NotIn predicate on the "completed_at" field.
func CompletedAtNotIn(vs ...time.Time) predicate.RelationshipOperation {
	return predicate.RelationshipOperation(sql.FieldNotIn(FieldCompletedAt, vs...))
}

// CompletedAtGT applies the GT predicate on the "completed_at" field.
func CompletedAtGT(v time.Time) predicate.RelationshipOperation {
	return predicate.RelationshipOperation(sql.FieldGT(FieldCompletedAt, v))
}

// CompletedAtGTE applies the GTE predicate on the "completed_at" field.
func CompletedAtGTE(v time.Time) predicate.RelationshipOperation {
	return predicate.RelationshipOperation(sql.FieldGTE(FieldCompletedAt, v))
}

// CompletedAtLT applies the LT predicate on the "completed_at" field.
func CompletedAtLT(v time.Time) predicate.RelationshipOperation {
	return predicate.RelationshipOperation(sql.FieldLT(FieldCompletedAt, v))
}

// CompletedAtLTE applies the LTE predicate on the "completed_at" field.
func CompletedAtLTE(v time.Time) predicate.RelationshipOperation {
	return predicate.RelationshipOperation(sql.FieldLTE(FieldCompletedAt, v))
}

// CompletedAtIsNil applies the IsNil predicate on the "completed_at" field.
func CompletedAtIsNil() predicate.RelationshipOperation {
	return predicate.RelationshipOperation(sql.FieldIsNull(FieldCompletedAt))
}

// CompletedAtNotNil applies the NotNil predicate on the "completed_at" field.
func CompletedAtNotNil() predicate.RelationshipOperation {
	return predicate.RelationshipOperation(sql.FieldNotNull(FieldCompletedAt))
}

// HasMappings applies the HasEdge predicate on the "mappings" edge.
func HasMappings() predicate.RelationshipOperation {
	return predicate.RelationshipOperation(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, MappingsTable, MappingsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasMappingsWith applies the HasEdge predicate on the "mappings" edge with a given conditions (other predicates).
func HasMappingsWith(preds ...predicate.RelationshipOperationMapping) predicate.RelationshipOperation {
	return predicate.RelationshipOperation(func(s *sql.Selector) {
		step := newMappingsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasSteps applies the HasEdge predicate on the "steps" edge.
func HasSteps() predicate.RelationshipOperation {
	return predicate.RelationshipOperation(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, StepsTable, StepsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasStepsWith applies the HasEdge predicate on the "steps" edge with a given conditions (other predicates).
func HasStepsWith(preds ...predicate.RelationshipOperationStep) predicate.RelationshipOperation {
	return predicate.RelationshipOperation(func(s *sql.Selector) {
		step := newStepsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAttempts applies the HasEdge predicate on the "attempts" edge.
func HasAttempts() predicate.RelationshipOperation {
	return predicate.RelationshipOperation(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, AttemptsTable, AttemptsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAttemptsWith applies the HasEdge predicate on the "attempts" edge with a given conditions (other predicates).
func HasAttemptsWith(preds ...predicate.RelationshipOperationAttempt) predicate.RelationshipOperation {
	return predicate.RelationshipOperation(func(s *sql.Selector) {
		step := newAttemptsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.RelationshipOperation) predicate.RelationshipOperation {
	return predicate.RelationshipOperation(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.RelationshipOperation) predicate.RelationshipOperation {
	return predicate.RelationshipOperation(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.RelationshipOperation) predicate.RelationshipOperation {
	return predicate.RelationshipOperation(sql.NotPredicates(p))
}
