// Code generated by ent, DO NOT EDIT.

package scmprovider

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/ai-efficiency/backend/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.ScmProvider {
	return predicate.ScmProvider(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.ScmProvider {
	return predicate.ScmProvider(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.ScmProvider {
	return predicate.ScmProvider(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.ScmProvider {
	return predicate.ScmProvider(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.ScmProvider {
	return predicate.ScmProvider(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.ScmProvider {
	return predicate.ScmProvider(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.ScmProvider {
	return predicate.ScmProvider(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.ScmProvider {
	return predicate.ScmProvider(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.ScmProvider {
	return predicate.ScmProvider(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.ScmProvider {
	return predicate.ScmProvider(sql.FieldEQ(FieldName, v))
}

// BaseURL applies equality check predicate on the "base_url" field. It's identical to BaseURLEQ.
func BaseURL(v string) predicate.ScmProvider {
	return predicate.ScmProvider(sql.FieldEQ(FieldBaseURL, v))
}

// Credentials applies equality check predicate on the "credentials" field. It's identical to CredentialsEQ.
func Credentials(v string) predicate.ScmProvider {
	return predicate.ScmProvider(sql.FieldEQ(FieldCredentials, v))
}

// APICredentialID applies equality check predicate on the "api_credential_id" field. It's identical to APICredentialIDEQ.
func APICredentialID(v int) predicate.ScmProvider {
	return predicate.ScmProvider(sql.FieldEQ(FieldAPICredentialID, v))
}

// CloneCredentialID applies equality check predicate on the "clone_credential_id" field. It's identical to CloneCredentialIDEQ.
func CloneCredentialID(v int) predicate.ScmProvider {
	return predicate.ScmProvider(sql.FieldEQ(FieldCloneCredentialID, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ScmProvider {
	return predicate.ScmProvider(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.ScmProvider {
	return predicate.ScmProvider(sql.FieldEQ(FieldUpdatedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.ScmProvider {
	return predicate.ScmProvider(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.ScmProvider {
	return predicate.ScmProvider(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.ScmProvider {
	return predicate.ScmProvider(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.ScmProvider {
	return predicate.ScmProvider(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.ScmProvider {
	return predicate.ScmProvider(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.ScmProvider {
	return predicate.ScmProvider(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.ScmProvider {
	return predicate.ScmProvider(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.ScmProvider {
	return predicate.ScmProvider(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.ScmProvider {
	return predicate.ScmProvider(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.ScmProvider {
	return predicate.ScmProvider(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.ScmProvider {
	return predicate.ScmProvider(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.ScmProvider {
	return predicate.ScmProvider(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.ScmProvider {
	return predicate.ScmProvider(sql.FieldContainsFold(FieldName, v))
}

// TypeEQ applies the EQ predicate on the "type" field.
func TypeEQ(v Type) predicate.ScmProvider {
	return predicate.ScmProvider(sql.FieldEQ(FieldType, v))
}

// TypeNEQ applies the NEQ predicate on the "type" field.
func TypeNEQ(v Type) predicate.ScmProvider {
	return predicate.ScmProvider(sql.FieldNEQ(FieldType, v))
}

// TypeIn applies the In predicate on the "type" field.
func TypeIn(vs ...Type) predicate.ScmProvider {
	return predicate.ScmProvider(sql.FieldIn(FieldType, vs...))
}

// TypeNotIn applies the NotIn predicate on the "type" field.
func TypeNotIn(vs ...Type) predicate.ScmProvider {
	return predicate.ScmProvider(sql.FieldNotIn(FieldType, vs...))
}

// BaseURLEQ applies the EQ predicate on the "base_url" field.
func BaseURLEQ(v string) predicate.ScmProvider {
	return predicate.ScmProvider(sql.FieldEQ(FieldBaseURL, v))
}

// BaseURLNEQ applies the NEQ predicate on the "base_url" field.
func BaseURLNEQ(v string) predicate.ScmProvider {
	return predicate.ScmProvider(sql.FieldNEQ(FieldBaseURL, v))
}

// BaseURLIn applies the In predicate on the "base_url" field.
func BaseURLIn(vs ...string) predicate.ScmProvider {
	return predicate.ScmProvider(sql.FieldIn(FieldBaseURL, vs...))
}

// BaseURLNotIn applies the NotIn predicate on the "base_url" field.
func BaseURLNotIn(vs ...string) predicate.ScmProvider {
	return predicate.ScmProvider(sql.FieldNotIn(FieldBaseURL, vs...))
}

// BaseURLGT applies the GT predicate on the "base_url" field.
func BaseURLGT(v string) predicate.ScmProvider {
	return predicate.ScmProvider(sql.FieldGT(FieldBaseURL, v))
}

// BaseURLGTE applies the GTE predicate on the "base_url" field.
func BaseURLGTE(v string) predicate.ScmProvider {
	return predicate.ScmProvider(sql.FieldGTE(FieldBaseURL, v))
}

// BaseURLLT applies the LT predicate on the "base_url" field.
func BaseURLLT(v string) predicate.ScmProvider {
	return predicate.ScmProvider(sql.FieldLT(FieldBaseURL, v))
}

// BaseURLLTE applies the LTE predicate on the "base_url" field.
func BaseURLLTE(v string) predicate.ScmProvider {
	return predicate.ScmProvider(sql.FieldLTE(FieldBaseURL, v))
}

// BaseURLContains applies the Contains predicate on the "base_url" field.
func BaseURLContains(v string) predicate.ScmProvider {
	return predicate.ScmProvider(sql.FieldContains(FieldBaseURL, v))
}

// BaseURLHasPrefix applies the HasPrefix predicate on the "base_url" field.
func BaseURLHasPrefix(v string) predicate.ScmProvider {
	return predicate.ScmProvider(sql.FieldHasPrefix(FieldBaseURL, v))
}

// BaseURLHasSuffix applies the HasSuffix predicate on the "base_url" field.
func BaseURLHasSuffix(v string) predicate.ScmProvider {
	return predicate.ScmProvider(sql.FieldHasSuffix(FieldBaseURL, v))
}

// BaseURLEqualFold applies the EqualFold predicate on the "base_url" field.
func BaseURLEqualFold(v string) predicate.ScmProvider {
	return predicate.ScmProvider(sql.FieldEqualFold(FieldBaseURL, v))
}

// BaseURLContainsFold applies the ContainsFold predicate on the "base_url" field.
func BaseURLContainsFold(v string) predicate.ScmProvider {
	return predicate.ScmProvider(sql.FieldContainsFold(FieldBaseURL, v))
}

// CredentialsEQ applies the EQ predicate on the "credentials" field.
func CredentialsEQ(v string) predicate.ScmProvider {
	return predicate.ScmProvider(sql.FieldEQ(FieldCredentials, v))
}

// CredentialsNEQ applies the NEQ predicate on the "credentials" field.
func CredentialsNEQ(v string) predicate.ScmProvider {
	return predicate.ScmProvider(sql.FieldNEQ(FieldCredentials, v))
}

// CredentialsIn applies the In predicate on the "credentials" field.
func CredentialsIn(vs ...string) predicate.ScmProvider {
	return predicate.ScmProvider(sql.FieldIn(FieldCredentials, vs...))
}

// CredentialsNotIn applies the NotIn predicate on the "credentials" field.
func CredentialsNotIn(vs ...string) predicate.ScmProvider {
	return predicate.ScmProvider(sql.FieldNotIn(FieldCredentials, vs...))
}

// CredentialsGT applies the GT predicate on the "credentials" field.
func CredentialsGT(v string) predicate.ScmProvider {
	return predicate.ScmProvider(sql.FieldGT(FieldCredentials, v))
}

// CredentialsGTE applies the GTE predicate on the "credentials" field.
func CredentialsGTE(v string) predicate.ScmProvider {
	return predicate.ScmProvider(sql.FieldGTE(FieldCredentials, v))
}

// CredentialsLT applies the LT predicate on the "credentials" field.
func CredentialsLT(v string) predicate.ScmProvider {
	return predicate.ScmProvider(sql.FieldLT(FieldCredentials, v))
}

// CredentialsLTE applies the LTE predicate on the "credentials" field.
func CredentialsLTE(v string) predicate.ScmProvider {
	return predicate.ScmProvider(sql.FieldLTE(FieldCredentials, v))
}

// CredentialsContains applies the Contains predicate on the "credentials" field.
func CredentialsContains(v string) predicate.ScmProvider {
	return predicate.ScmProvider(sql.FieldContains(FieldCredentials, v))
}

// CredentialsHasPrefix applies the HasPrefix predicate on the "credentials" field.
func CredentialsHasPrefix(v string) predicate.ScmProvider {
	return predicate.ScmProvider(sql.FieldHasPrefix(FieldCredentials, v))
}

// CredentialsHasSuffix applies the HasSuffix predicate on the "credentials" field.
func CredentialsHasSuffix(v string) predicate.ScmProvider {
	return predicate.ScmProvider(sql.FieldHasSuffix(FieldCredentials, v))
}

// CredentialsIsNil applies the IsNil predicate on the "credentials" field.
func CredentialsIsNil() predicate.ScmProvider {
	return predicate.ScmProvider(sql.FieldIsNull(FieldCredentials))
}

// CredentialsNotNil applies the NotNil predicate on the "credentials" field.
func CredentialsNotNil() predicate.ScmProvider {
	return predicate.ScmProvider(sql.FieldNotNull(FieldCredentials))
}

// CredentialsEqualFold applies the EqualFold predicate on the "credentials" field.
func CredentialsEqualFold(v string) predicate.ScmProvider {
	return predicate.ScmProvider(sql.FieldEqualFold(FieldCredentials, v))
}

// CredentialsContainsFold applies the ContainsFold predicate on the "credentials" field.
func CredentialsContainsFold(v string) predicate.ScmProvider {
	return predicate.ScmProvider(sql.FieldContainsFold(FieldCredentials, v))
}

// APICredentialIDEQ applies the EQ predicate on the "api_credential_id" field.
func APICredentialIDEQ(v int) predicate.ScmProvider {
	return predicate.ScmProvider(sql.FieldEQ(FieldAPICredentialID, v))
}

// APICredentialIDNEQ applies the NEQ predicate on the "api_credential_id" field.
func APICredentialIDNEQ(v int) predicate.ScmProvider {
	return predicate.ScmProvider(sql.FieldNEQ(FieldAPICredentialID, v))
}

// APICredentialIDIn applies the In predicate on the "api_credential_id" field.
func APICredentialIDIn(vs ...int) predicate.ScmProvider {
	return predicate.ScmProvider(sql.FieldIn(FieldAPICredentialID, vs...))
}

// APICredentialIDNotIn applies the NotIn predicate on the "api_credential_id" field.
func APICredentialIDNotIn(vs ...int) predicate.ScmProvider {
	return predicate.ScmProvider(sql.FieldNotIn(FieldAPICredentialID, vs...))
}

// APICredentialIDIsNil applies the IsNil predicate on the "api_credential_id" field.
func APICredentialIDIsNil() predicate.ScmProvider {
	return predicate.ScmProvider(sql.FieldIsNull(FieldAPICredentialID))
}

// APICredentialIDNotNil applies the NotNil predicate on the "api_credential_id" field.
func APICredentialIDNotNil() predicate.ScmProvider {
	return predicate.ScmProvider(sql.FieldNotNull(FieldAPICredentialID))
}

// CloneCredentialIDEQ applies the EQ predicate on the "clone_credential_id" field.
func CloneCredentialIDEQ(v int) predicate.ScmProvider {
	return predicate.ScmProvider(sql.FieldEQ(FieldCloneCredentialID, v))
}

// CloneCredentialIDNEQ applies the NEQ predicate on the "clone_credential_id" field.
func CloneCredentialIDNEQ(v int) predicate.ScmProvider {
	return predicate.ScmProvider(sql.FieldNEQ(FieldCloneCredentialID, v))
}

// CloneCredentialIDIn applies the In predicate on the "clone_credential_id" field.
func CloneCredentialIDIn(vs ...int) predicate.ScmProvider {
	return predicate.ScmProvider(sql.FieldIn(FieldCloneCredentialID, vs...))
}

// CloneCredentialIDNotIn applies the NotIn predicate on the "clone_credential_id" field.
func CloneCredentialIDNotIn(vs ...int) predicate.ScmProvider {
	return predicate.ScmProvider(sql.FieldNotIn(FieldCloneCredentialID, vs...))
}

// CloneCredentialIDIsNil applies the IsNil predicate on the "clone_credential_id" field.
func CloneCredentialIDIsNil() predicate.ScmProvider {
	return predicate.ScmProvider(sql.FieldIsNull(FieldCloneCredentialID))
}

// CloneCredentialIDNotNil applies the NotNil predicate on the "clone_credential_id" field.
func CloneCredentialIDNotNil() predicate.ScmProvider {
	return predicate.ScmProvider(sql.FieldNotNull(FieldCloneCredentialID))
}

// CloneProtocolEQ applies the EQ predicate on the "clone_protocol" field.
func CloneProtocolEQ(v CloneProtocol) predicate.ScmProvider {
	return predicate.ScmProvider(sql.FieldEQ(FieldCloneProtocol, v))
}

// CloneProtocolNEQ applies the NEQ predicate on the "clone_protocol" field.
func CloneProtocolNEQ(v CloneProtocol) predicate.ScmProvider {
	return predicate.ScmProvider(sql.FieldNEQ(FieldCloneProtocol, v))
}

// CloneProtocolIn applies the In predicate on the "clone_protocol" field.
func CloneProtocolIn(vs ...CloneProtocol) predicate.ScmProvider {
	return predicate.ScmProvider(sql.FieldIn(FieldCloneProtocol, vs...))
}

// CloneProtocolNotIn applies the NotIn predicate on the "clone_protocol" field.
func CloneProtocolNotIn(vs ...CloneProtocol) predicate.ScmProvider {
	return predicate.ScmProvider(sql.FieldNotIn(FieldCloneProtocol, vs...))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.ScmProvider {
	return predicate.ScmProvider(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.ScmProvider {
	return predicate.ScmProvider(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.ScmProvider {
	return predicate.ScmProvider(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.ScmProvider {
	return predicate.ScmProvider(sql.FieldNotIn(FieldStatus, vs...))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ScmProvider {
	return predicate.ScmProvider(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ScmProvider {
	return predicate.ScmProvider(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ScmProvider {
	return predicate.ScmProvider(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ScmProvider {
	return predicate.ScmProvider(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ScmProvider {
	return predicate.ScmProvider(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ScmProvider {
	return predicate.ScmProvider(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ScmProvider {
	return predicate.ScmProvider(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ScmProvider {
	return predicate.ScmProvider(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.ScmProvider {
	return predicate.ScmProvider(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.ScmProvider {
	return predicate.ScmProvider(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.ScmProvider {
	return predicate.ScmProvider(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.ScmProvider {
	return predicate.ScmProvider(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.ScmProvider {
	return predicate.ScmProvider(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.ScmProvider {
	return predicate.ScmProvider(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.ScmProvider {
	return predicate.ScmProvider(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.ScmProvider {
	return predicate.ScmProvider(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasAPICredential applies the HasEdge predicate on the "api_credential" edge.
func HasAPICredential() predicate.ScmProvider {
	return predicate.ScmProvider(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, APICredentialTable, APICredentialColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAPICredentialWith applies the HasEdge predicate on the "api_credential" edge with a given conditions (other predicates).
func HasAPICredentialWith(preds ...predicate.Credential) predicate.ScmProvider {
	return predicate.ScmProvider(func(s *sql.Selector) {
		step := newAPICredentialStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasCloneCredential applies the HasEdge predicate on the "clone_credential" edge.
func HasCloneCredential() predicate.ScmProvider {
	return predicate.ScmProvider(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, CloneCredentialTable, CloneCredentialColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCloneCredentialWith applies the HasEdge predicate on the "clone_credential" edge with a given conditions (other predicates).
func HasCloneCredentialWith(preds ...predicate.Credential) predicate.ScmProvider {
	return predicate.ScmProvider(func(s *sql.Selector) {
		step := newCloneCredentialStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasRepoConfigs applies the HasEdge predicate on the "repo_configs" edge.
func HasRepoConfigs() predicate.ScmProvider {
	return predicate.ScmProvider(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, RepoConfigsTable, RepoConfigsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRepoConfigsWith applies the HasEdge predicate on the "repo_configs" edge with a given conditions (other predicates).
func HasRepoConfigsWith(preds ...predicate.RepoConfig) predicate.ScmProvider {
	return predicate.ScmProvider(func(s *sql.Selector) {
		step := newRepoConfigsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ScmProvider) predicate.ScmProvider {
	return predicate.ScmProvider(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ScmProvider) predicate.ScmProvider {
	return predicate.ScmProvider(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ScmProvider) predicate.ScmProvider {
	return predicate.ScmProvider(sql.NotPredicates(p))
}
