// Code generated by ent, DO NOT EDIT.

package attributionclaimgroup

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/ai-efficiency/backend/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldLTE(FieldID, id))
}

// GroupID applies equality check predicate on the "group_id" field. It's identical to GroupIDEQ.
func GroupID(v string) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldEQ(FieldGroupID, v))
}

// InstallationID applies equality check predicate on the "installation_id" field. It's identical to InstallationIDEQ.
func InstallationID(v int) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldEQ(FieldInstallationID, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldEQ(FieldUserID, v))
}

// RelayProviderID applies equality check predicate on the "relay_provider_id" field. It's identical to RelayProviderIDEQ.
func RelayProviderID(v int) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldEQ(FieldRelayProviderID, v))
}

// SchemaVersion applies equality check predicate on the "schema_version" field. It's identical to SchemaVersionEQ.
func SchemaVersion(v int) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldEQ(FieldSchemaVersion, v))
}

// LedgerEpoch applies equality check predicate on the "ledger_epoch" field. It's identical to LedgerEpochEQ.
func LedgerEpoch(v string) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldEQ(FieldLedgerEpoch, v))
}

// ThreadID applies equality check predicate on the "thread_id" field. It's identical to ThreadIDEQ.
func ThreadID(v string) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldEQ(FieldThreadID, v))
}

// TurnID applies equality check predicate on the "turn_id" field. It's identical to TurnIDEQ.
func TurnID(v string) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldEQ(FieldTurnID, v))
}

// EvidenceDigest applies equality check predicate on the "evidence_digest" field. It's identical to EvidenceDigestEQ.
func EvidenceDigest(v string) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldEQ(FieldEvidenceDigest, v))
}

// CalibrationDigest applies equality check predicate on the "calibration_digest" field. It's identical to CalibrationDigestEQ.
func CalibrationDigest(v string) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldEQ(FieldCalibrationDigest, v))
}

// CalibrationInputTokens applies equality check predicate on the "calibration_input_tokens" field. It's identical to CalibrationInputTokensEQ.
func CalibrationInputTokens(v int64) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldEQ(FieldCalibrationInputTokens, v))
}

// CalibrationOutputTokens applies equality check predicate on the "calibration_output_tokens" field. It's identical to CalibrationOutputTokensEQ.
func CalibrationOutputTokens(v int64) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldEQ(FieldCalibrationOutputTokens, v))
}

// CalibrationCacheCreationTokens applies equality check predicate on the "calibration_cache_creation_tokens" field. It's identical to CalibrationCacheCreationTokensEQ.
func CalibrationCacheCreationTokens(v int64) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldEQ(FieldCalibrationCacheCreationTokens, v))
}

// CalibrationCacheReadTokens applies equality check predicate on the "calibration_cache_read_tokens" field. It's identical to CalibrationCacheReadTokensEQ.
func CalibrationCacheReadTokens(v int64) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldEQ(FieldCalibrationCacheReadTokens, v))
}

// CalibrationTotalTokens applies equality check predicate on the "calibration_total_tokens" field. It's identical to CalibrationTotalTokensEQ.
func CalibrationTotalTokens(v int64) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldEQ(FieldCalibrationTotalTokens, v))
}

// RequestCount applies equality check predicate on the "request_count" field. It's identical to RequestCountEQ.
func RequestCount(v int) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldEQ(FieldRequestCount, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldEQ(FieldExpiresAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldEQ(FieldUpdatedAt, v))
}

// GroupIDEQ applies the EQ predicate on the "group_id" field.
func GroupIDEQ(v string) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldEQ(FieldGroupID, v))
}

// GroupIDNEQ applies the NEQ predicate on the "group_id" field.
func GroupIDNEQ(v string) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldNEQ(FieldGroupID, v))
}

// GroupIDIn applies the In predicate on the "group_id" field.
func GroupIDIn(vs ...string) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldIn(FieldGroupID, vs...))
}

// GroupIDNotIn applies the NotIn predicate on the "group_id" field.
func GroupIDNotIn(vs ...string) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldNotIn(FieldGroupID, vs...))
}

// GroupIDGT applies the GT predicate on the "group_id" field.
func GroupIDGT(v string) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldGT(FieldGroupID, v))
}

// GroupIDGTE applies the GTE predicate on the "group_id" field.
func GroupIDGTE(v string) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldGTE(FieldGroupID, v))
}

// GroupIDLT applies the LT predicate on the "group_id" field.
func GroupIDLT(v string) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldLT(FieldGroupID, v))
}

// GroupIDLTE applies the LTE predicate on the "group_id" field.
func GroupIDLTE(v string) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldLTE(FieldGroupID, v))
}

// GroupIDContains applies the Contains predicate on the "group_id" field.
func GroupIDContains(v string) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldContains(FieldGroupID, v))
}

// GroupIDHasPrefix applies the HasPrefix predicate on the "group_id" field.
func GroupIDHasPrefix(v string) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldHasPrefix(FieldGroupID, v))
}

// GroupIDHasSuffix applies the HasSuffix predicate on the "group_id" field.
func GroupIDHasSuffix(v string) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldHasSuffix(FieldGroupID, v))
}

// GroupIDEqualFold applies the EqualFold predicate on the "group_id" field.
func GroupIDEqualFold(v string) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldEqualFold(FieldGroupID, v))
}

// GroupIDContainsFold applies the ContainsFold predicate on the "group_id" field.
func GroupIDContainsFold(v string) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldContainsFold(FieldGroupID, v))
}

// InstallationIDEQ applies the EQ predicate on the "installation_id" field.
func InstallationIDEQ(v int) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldEQ(FieldInstallationID, v))
}

// InstallationIDNEQ applies the NEQ predicate on the "installation_id" field.
func InstallationIDNEQ(v int) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldNEQ(FieldInstallationID, v))
}

// InstallationIDIn applies the In predicate on the "installation_id" field.
func InstallationIDIn(vs ...int) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldIn(FieldInstallationID, vs...))
}

// InstallationIDNotIn applies the NotIn predicate on the "installation_id" field.
func InstallationIDNotIn(vs ...int) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldNotIn(FieldInstallationID, vs...))
}

// InstallationIDGT applies the GT predicate on the "installation_id" field.
func InstallationIDGT(v int) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldGT(FieldInstallationID, v))
}

// InstallationIDGTE applies the GTE predicate on the "installation_id" field.
func InstallationIDGTE(v int) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldGTE(FieldInstallationID, v))
}

// InstallationIDLT applies the LT predicate on the "installation_id" field.
func InstallationIDLT(v int) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldLT(FieldInstallationID, v))
}

// InstallationIDLTE applies the LTE predicate on the "installation_id" field.
func InstallationIDLTE(v int) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldLTE(FieldInstallationID, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v int) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v int) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v int) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v int) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldLTE(FieldUserID, v))
}

// RelayProviderIDEQ applies the EQ predicate on the "relay_provider_id" field.
func RelayProviderIDEQ(v int) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldEQ(FieldRelayProviderID, v))
}

// RelayProviderIDNEQ applies the NEQ predicate on the "relay_provider_id" field.
func RelayProviderIDNEQ(v int) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldNEQ(FieldRelayProviderID, v))
}

// RelayProviderIDIn applies the In predicate on the "relay_provider_id" field.
func RelayProviderIDIn(vs ...int) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldIn(FieldRelayProviderID, vs...))
}

// RelayProviderIDNotIn applies the NotIn predicate on the "relay_provider_id" field.
func RelayProviderIDNotIn(vs ...int) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldNotIn(FieldRelayProviderID, vs...))
}

// RelayProviderIDGT applies the GT predicate on the "relay_provider_id" field.
func RelayProviderIDGT(v int) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldGT(FieldRelayProviderID, v))
}

// RelayProviderIDGTE applies the GTE predicate on the "relay_provider_id" field.
func RelayProviderIDGTE(v int) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldGTE(FieldRelayProviderID, v))
}

// RelayProviderIDLT applies the LT predicate on the "relay_provider_id" field.
func RelayProviderIDLT(v int) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldLT(FieldRelayProviderID, v))
}

// RelayProviderIDLTE applies the LTE predicate on the "relay_provider_id" field.
func RelayProviderIDLTE(v int) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldLTE(FieldRelayProviderID, v))
}

// SchemaVersionEQ applies the EQ predicate on the "schema_version" field.
func SchemaVersionEQ(v int) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldEQ(FieldSchemaVersion, v))
}

// SchemaVersionNEQ applies the NEQ predicate on the "schema_version" field.
func SchemaVersionNEQ(v int) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldNEQ(FieldSchemaVersion, v))
}

// SchemaVersionIn applies the In predicate on the "schema_version" field.
func SchemaVersionIn(vs ...int) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldIn(FieldSchemaVersion, vs...))
}

// SchemaVersionNotIn applies the NotIn predicate on the "schema_version" field.
func SchemaVersionNotIn(vs ...int) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldNotIn(FieldSchemaVersion, vs...))
}

// SchemaVersionGT applies the GT predicate on the "schema_version" field.
func SchemaVersionGT(v int) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldGT(FieldSchemaVersion, v))
}

// SchemaVersionGTE applies the GTE predicate on the "schema_version" field.
func SchemaVersionGTE(v int) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldGTE(FieldSchemaVersion, v))
}

// SchemaVersionLT applies the LT predicate on the "schema_version" field.
func SchemaVersionLT(v int) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldLT(FieldSchemaVersion, v))
}

// SchemaVersionLTE applies the LTE predicate on the "schema_version" field.
func SchemaVersionLTE(v int) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldLTE(FieldSchemaVersion, v))
}

// LedgerEpochEQ applies the EQ predicate on the "ledger_epoch" field.
func LedgerEpochEQ(v string) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldEQ(FieldLedgerEpoch, v))
}

// LedgerEpochNEQ applies the NEQ predicate on the "ledger_epoch" field.
func LedgerEpochNEQ(v string) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldNEQ(FieldLedgerEpoch, v))
}

// LedgerEpochIn applies the In predicate on the "ledger_epoch" field.
func LedgerEpochIn(vs ...string) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldIn(FieldLedgerEpoch, vs...))
}

// LedgerEpochNotIn applies the NotIn predicate on the "ledger_epoch" field.
func LedgerEpochNotIn(vs ...string) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldNotIn(FieldLedgerEpoch, vs...))
}

// LedgerEpochGT applies the GT predicate on the "ledger_epoch" field.
func LedgerEpochGT(v string) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldGT(FieldLedgerEpoch, v))
}

// LedgerEpochGTE applies the GTE predicate on the "ledger_epoch" field.
func LedgerEpochGTE(v string) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldGTE(FieldLedgerEpoch, v))
}

// LedgerEpochLT applies the LT predicate on the "ledger_epoch" field.
func LedgerEpochLT(v string) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldLT(FieldLedgerEpoch, v))
}

// LedgerEpochLTE applies the LTE predicate on the "ledger_epoch" field.
func LedgerEpochLTE(v string) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldLTE(FieldLedgerEpoch, v))
}

// LedgerEpochContains applies the Contains predicate on the "ledger_epoch" field.
func LedgerEpochContains(v string) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldContains(FieldLedgerEpoch, v))
}

// LedgerEpochHasPrefix applies the HasPrefix predicate on the "ledger_epoch" field.
func LedgerEpochHasPrefix(v string) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldHasPrefix(FieldLedgerEpoch, v))
}

// LedgerEpochHasSuffix applies the HasSuffix predicate on the "ledger_epoch" field.
func LedgerEpochHasSuffix(v string) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldHasSuffix(FieldLedgerEpoch, v))
}

// LedgerEpochEqualFold applies the EqualFold predicate on the "ledger_epoch" field.
func LedgerEpochEqualFold(v string) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldEqualFold(FieldLedgerEpoch, v))
}

// LedgerEpochContainsFold applies the ContainsFold predicate on the "ledger_epoch" field.
func LedgerEpochContainsFold(v string) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldContainsFold(FieldLedgerEpoch, v))
}

// ThreadIDEQ applies the EQ predicate on the "thread_id" field.
func ThreadIDEQ(v string) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldEQ(FieldThreadID, v))
}

// ThreadIDNEQ applies the NEQ predicate on the "thread_id" field.
func ThreadIDNEQ(v string) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldNEQ(FieldThreadID, v))
}

// ThreadIDIn applies the In predicate on the "thread_id" field.
func ThreadIDIn(vs ...string) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldIn(FieldThreadID, vs...))
}

// ThreadIDNotIn applies the NotIn predicate on the "thread_id" field.
func ThreadIDNotIn(vs ...string) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldNotIn(FieldThreadID, vs...))
}

// ThreadIDGT applies the GT predicate on the "thread_id" field.
func ThreadIDGT(v string) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldGT(FieldThreadID, v))
}

// ThreadIDGTE applies the GTE predicate on the "thread_id" field.
func ThreadIDGTE(v string) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldGTE(FieldThreadID, v))
}

// ThreadIDLT applies the LT predicate on the "thread_id" field.
func ThreadIDLT(v string) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldLT(FieldThreadID, v))
}

// ThreadIDLTE applies the LTE predicate on the "thread_id" field.
func ThreadIDLTE(v string) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldLTE(FieldThreadID, v))
}

// ThreadIDContains applies the Contains predicate on the "thread_id" field.
func ThreadIDContains(v string) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldContains(FieldThreadID, v))
}

// ThreadIDHasPrefix applies the HasPrefix predicate on the "thread_id" field.
func ThreadIDHasPrefix(v string) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldHasPrefix(FieldThreadID, v))
}

// ThreadIDHasSuffix applies the HasSuffix predicate on the "thread_id" field.
func ThreadIDHasSuffix(v string) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldHasSuffix(FieldThreadID, v))
}

// ThreadIDEqualFold applies the EqualFold predicate on the "thread_id" field.
func ThreadIDEqualFold(v string) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldEqualFold(FieldThreadID, v))
}

// ThreadIDContainsFold applies the ContainsFold predicate on the "thread_id" field.
func ThreadIDContainsFold(v string) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldContainsFold(FieldThreadID, v))
}

// TurnIDEQ applies the EQ predicate on the "turn_id" field.
func TurnIDEQ(v string) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldEQ(FieldTurnID, v))
}

// TurnIDNEQ applies the NEQ predicate on the "turn_id" field.
func TurnIDNEQ(v string) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldNEQ(FieldTurnID, v))
}

// TurnIDIn applies the In predicate on the "turn_id" field.
func TurnIDIn(vs ...string) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldIn(FieldTurnID, vs...))
}

// TurnIDNotIn applies the NotIn predicate on the "turn_id" field.
func TurnIDNotIn(vs ...string) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldNotIn(FieldTurnID, vs...))
}

// TurnIDGT applies the GT predicate on the "turn_id" field.
func TurnIDGT(v string) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldGT(FieldTurnID, v))
}

// TurnIDGTE applies the GTE predicate on the "turn_id" field.
func TurnIDGTE(v string) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldGTE(FieldTurnID, v))
}

// TurnIDLT applies the LT predicate on the "turn_id" field.
func TurnIDLT(v string) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldLT(FieldTurnID, v))
}

// TurnIDLTE applies the LTE predicate on the "turn_id" field.
func TurnIDLTE(v string) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldLTE(FieldTurnID, v))
}

// TurnIDContains applies the Contains predicate on the "turn_id" field.
func TurnIDContains(v string) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldContains(FieldTurnID, v))
}

// TurnIDHasPrefix applies the HasPrefix predicate on the "turn_id" field.
func TurnIDHasPrefix(v string) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldHasPrefix(FieldTurnID, v))
}

// TurnIDHasSuffix applies the HasSuffix predicate on the "turn_id" field.
func TurnIDHasSuffix(v string) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldHasSuffix(FieldTurnID, v))
}

// TurnIDEqualFold applies the EqualFold predicate on the "turn_id" field.
func TurnIDEqualFold(v string) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldEqualFold(FieldTurnID, v))
}

// TurnIDContainsFold applies the ContainsFold predicate on the "turn_id" field.
func TurnIDContainsFold(v string) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldContainsFold(FieldTurnID, v))
}

// EvidenceDigestEQ applies the EQ predicate on the "evidence_digest" field.
func EvidenceDigestEQ(v string) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldEQ(FieldEvidenceDigest, v))
}

// EvidenceDigestNEQ applies the NEQ predicate on the "evidence_digest" field.
func EvidenceDigestNEQ(v string) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldNEQ(FieldEvidenceDigest, v))
}

// EvidenceDigestIn applies the In predicate on the "evidence_digest" field.
func EvidenceDigestIn(vs ...string) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldIn(FieldEvidenceDigest, vs...))
}

// EvidenceDigestNotIn applies the NotIn predicate on the "evidence_digest" field.
func EvidenceDigestNotIn(vs ...string) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldNotIn(FieldEvidenceDigest, vs...))
}

// EvidenceDigestGT applies the GT predicate on the "evidence_digest" field.
func EvidenceDigestGT(v string) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldGT(FieldEvidenceDigest, v))
}

// EvidenceDigestGTE applies the GTE predicate on the "evidence_digest" field.
func EvidenceDigestGTE(v string) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldGTE(FieldEvidenceDigest, v))
}

// EvidenceDigestLT applies the LT predicate on the "evidence_digest" field.
func EvidenceDigestLT(v string) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldLT(FieldEvidenceDigest, v))
}

// EvidenceDigestLTE applies the LTE predicate on the "evidence_digest" field.
func EvidenceDigestLTE(v string) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldLTE(FieldEvidenceDigest, v))
}

// EvidenceDigestContains applies the Contains predicate on the "evidence_digest" field.
func EvidenceDigestContains(v string) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldContains(FieldEvidenceDigest, v))
}

// EvidenceDigestHasPrefix applies the HasPrefix predicate on the "evidence_digest" field.
func EvidenceDigestHasPrefix(v string) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldHasPrefix(FieldEvidenceDigest, v))
}

// EvidenceDigestHasSuffix applies the HasSuffix predicate on the "evidence_digest" field.
func EvidenceDigestHasSuffix(v string) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldHasSuffix(FieldEvidenceDigest, v))
}

// EvidenceDigestEqualFold applies the EqualFold predicate on the "evidence_digest" field.
func EvidenceDigestEqualFold(v string) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldEqualFold(FieldEvidenceDigest, v))
}

// EvidenceDigestContainsFold applies the ContainsFold predicate on the "evidence_digest" field.
func EvidenceDigestContainsFold(v string) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldContainsFold(FieldEvidenceDigest, v))
}

// CalibrationDigestEQ applies the EQ predicate on the "calibration_digest" field.
func CalibrationDigestEQ(v string) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldEQ(FieldCalibrationDigest, v))
}

// CalibrationDigestNEQ applies the NEQ predicate on the "calibration_digest" field.
func CalibrationDigestNEQ(v string) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldNEQ(FieldCalibrationDigest, v))
}

// CalibrationDigestIn applies the In predicate on the "calibration_digest" field.
func CalibrationDigestIn(vs ...string) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldIn(FieldCalibrationDigest, vs...))
}

// CalibrationDigestNotIn applies the NotIn predicate on the "calibration_digest" field.
func CalibrationDigestNotIn(vs ...string) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldNotIn(FieldCalibrationDigest, vs...))
}

// CalibrationDigestGT applies the GT predicate on the "calibration_digest" field.
func CalibrationDigestGT(v string) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldGT(FieldCalibrationDigest, v))
}

// CalibrationDigestGTE applies the GTE predicate on the "calibration_digest" field.
func CalibrationDigestGTE(v string) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldGTE(FieldCalibrationDigest, v))
}

// CalibrationDigestLT applies the LT predicate on the "calibration_digest" field.
func CalibrationDigestLT(v string) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldLT(FieldCalibrationDigest, v))
}

// CalibrationDigestLTE applies the LTE predicate on the "calibration_digest" field.
func CalibrationDigestLTE(v string) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldLTE(FieldCalibrationDigest, v))
}

// CalibrationDigestContains applies the Contains predicate on the "calibration_digest" field.
func CalibrationDigestContains(v string) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldContains(FieldCalibrationDigest, v))
}

// CalibrationDigestHasPrefix applies the HasPrefix predicate on the "calibration_digest" field.
func CalibrationDigestHasPrefix(v string) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldHasPrefix(FieldCalibrationDigest, v))
}

// CalibrationDigestHasSuffix applies the HasSuffix predicate on the "calibration_digest" field.
func CalibrationDigestHasSuffix(v string) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldHasSuffix(FieldCalibrationDigest, v))
}

// CalibrationDigestIsNil applies the IsNil predicate on the "calibration_digest" field.
func CalibrationDigestIsNil() predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldIsNull(FieldCalibrationDigest))
}

// CalibrationDigestNotNil applies the NotNil predicate on the "calibration_digest" field.
func CalibrationDigestNotNil() predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldNotNull(FieldCalibrationDigest))
}

// CalibrationDigestEqualFold applies the EqualFold predicate on the "calibration_digest" field.
func CalibrationDigestEqualFold(v string) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldEqualFold(FieldCalibrationDigest, v))
}

// CalibrationDigestContainsFold applies the ContainsFold predicate on the "calibration_digest" field.
func CalibrationDigestContainsFold(v string) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldContainsFold(FieldCalibrationDigest, v))
}

// CalibrationInputTokensEQ applies the EQ predicate on the "calibration_input_tokens" field.
func CalibrationInputTokensEQ(v int64) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldEQ(FieldCalibrationInputTokens, v))
}

// CalibrationInputTokensNEQ applies the NEQ predicate on the "calibration_input_tokens" field.
func CalibrationInputTokensNEQ(v int64) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldNEQ(FieldCalibrationInputTokens, v))
}

// CalibrationInputTokensIn applies the In predicate on the "calibration_input_tokens" field.
func CalibrationInputTokensIn(vs ...int64) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldIn(FieldCalibrationInputTokens, vs...))
}

// CalibrationInputTokensNotIn applies the NotIn predicate on the "calibration_input_tokens" field.
func CalibrationInputTokensNotIn(vs ...int64) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldNotIn(FieldCalibrationInputTokens, vs...))
}

// CalibrationInputTokensGT applies the GT predicate on the "calibration_input_tokens" field.
func CalibrationInputTokensGT(v int64) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldGT(FieldCalibrationInputTokens, v))
}

// CalibrationInputTokensGTE applies the GTE predicate on the "calibration_input_tokens" field.
func CalibrationInputTokensGTE(v int64) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldGTE(FieldCalibrationInputTokens, v))
}

// CalibrationInputTokensLT applies the LT predicate on the "calibration_input_tokens" field.
func CalibrationInputTokensLT(v int64) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldLT(FieldCalibrationInputTokens, v))
}

// CalibrationInputTokensLTE applies the LTE predicate on the "calibration_input_tokens" field.
func CalibrationInputTokensLTE(v int64) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldLTE(FieldCalibrationInputTokens, v))
}

// CalibrationOutputTokensEQ applies the EQ predicate on the "calibration_output_tokens" field.
func CalibrationOutputTokensEQ(v int64) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldEQ(FieldCalibrationOutputTokens, v))
}

// CalibrationOutputTokensNEQ applies the NEQ predicate on the "calibration_output_tokens" field.
func CalibrationOutputTokensNEQ(v int64) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldNEQ(FieldCalibrationOutputTokens, v))
}

// CalibrationOutputTokensIn applies the In predicate on the "calibration_output_tokens" field.
func CalibrationOutputTokensIn(vs ...int64) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldIn(FieldCalibrationOutputTokens, vs...))
}

// CalibrationOutputTokensNotIn applies the NotIn predicate on the "calibration_output_tokens" field.
func CalibrationOutputTokensNotIn(vs ...int64) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldNotIn(FieldCalibrationOutputTokens, vs...))
}

// CalibrationOutputTokensGT applies the GT predicate on the "calibration_output_tokens" field.
func CalibrationOutputTokensGT(v int64) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldGT(FieldCalibrationOutputTokens, v))
}

// CalibrationOutputTokensGTE applies the GTE predicate on the "calibration_output_tokens" field.
func CalibrationOutputTokensGTE(v int64) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldGTE(FieldCalibrationOutputTokens, v))
}

// CalibrationOutputTokensLT applies the LT predicate on the "calibration_output_tokens" field.
func CalibrationOutputTokensLT(v int64) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldLT(FieldCalibrationOutputTokens, v))
}

// CalibrationOutputTokensLTE applies the LTE predicate on the "calibration_output_tokens" field.
func CalibrationOutputTokensLTE(v int64) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldLTE(FieldCalibrationOutputTokens, v))
}

// CalibrationCacheCreationTokensEQ applies the EQ predicate on the "calibration_cache_creation_tokens" field.
func CalibrationCacheCreationTokensEQ(v int64) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldEQ(FieldCalibrationCacheCreationTokens, v))
}

// CalibrationCacheCreationTokensNEQ applies the NEQ predicate on the "calibration_cache_creation_tokens" field.
func CalibrationCacheCreationTokensNEQ(v int64) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldNEQ(FieldCalibrationCacheCreationTokens, v))
}

// CalibrationCacheCreationTokensIn applies the In predicate on the "calibration_cache_creation_tokens" field.
func CalibrationCacheCreationTokensIn(vs ...int64) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldIn(FieldCalibrationCacheCreationTokens, vs...))
}

// CalibrationCacheCreationTokensNotIn applies the NotIn predicate on the "calibration_cache_creation_tokens" field.
func CalibrationCacheCreationTokensNotIn(vs ...int64) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldNotIn(FieldCalibrationCacheCreationTokens, vs...))
}

// CalibrationCacheCreationTokensGT applies the GT predicate on the "calibration_cache_creation_tokens" field.
func CalibrationCacheCreationTokensGT(v int64) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldGT(FieldCalibrationCacheCreationTokens, v))
}

// CalibrationCacheCreationTokensGTE applies the GTE predicate on the "calibration_cache_creation_tokens" field.
func CalibrationCacheCreationTokensGTE(v int64) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldGTE(FieldCalibrationCacheCreationTokens, v))
}

// CalibrationCacheCreationTokensLT applies the LT predicate on the "calibration_cache_creation_tokens" field.
func CalibrationCacheCreationTokensLT(v int64) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldLT(FieldCalibrationCacheCreationTokens, v))
}

// CalibrationCacheCreationTokensLTE applies the LTE predicate on the "calibration_cache_creation_tokens" field.
func CalibrationCacheCreationTokensLTE(v int64) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldLTE(FieldCalibrationCacheCreationTokens, v))
}

// CalibrationCacheReadTokensEQ applies the EQ predicate on the "calibration_cache_read_tokens" field.
func CalibrationCacheReadTokensEQ(v int64) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldEQ(FieldCalibrationCacheReadTokens, v))
}

// CalibrationCacheReadTokensNEQ applies the NEQ predicate on the "calibration_cache_read_tokens" field.
func CalibrationCacheReadTokensNEQ(v int64) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldNEQ(FieldCalibrationCacheReadTokens, v))
}

// CalibrationCacheReadTokensIn applies the In predicate on the "calibration_cache_read_tokens" field.
func CalibrationCacheReadTokensIn(vs ...int64) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldIn(FieldCalibrationCacheReadTokens, vs...))
}

// CalibrationCacheReadTokensNotIn applies the NotIn predicate on the "calibration_cache_read_tokens" field.
func CalibrationCacheReadTokensNotIn(vs ...int64) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldNotIn(FieldCalibrationCacheReadTokens, vs...))
}

// CalibrationCacheReadTokensGT applies the GT predicate on the "calibration_cache_read_tokens" field.
func CalibrationCacheReadTokensGT(v int64) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldGT(FieldCalibrationCacheReadTokens, v))
}

// CalibrationCacheReadTokensGTE applies the GTE predicate on the "calibration_cache_read_tokens" field.
func CalibrationCacheReadTokensGTE(v int64) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldGTE(FieldCalibrationCacheReadTokens, v))
}

// CalibrationCacheReadTokensLT applies the LT predicate on the "calibration_cache_read_tokens" field.
func CalibrationCacheReadTokensLT(v int64) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldLT(FieldCalibrationCacheReadTokens, v))
}

// CalibrationCacheReadTokensLTE applies the LTE predicate on the "calibration_cache_read_tokens" field.
func CalibrationCacheReadTokensLTE(v int64) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldLTE(FieldCalibrationCacheReadTokens, v))
}

// CalibrationTotalTokensEQ applies the EQ predicate on the "calibration_total_tokens" field.
func CalibrationTotalTokensEQ(v int64) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldEQ(FieldCalibrationTotalTokens, v))
}

// CalibrationTotalTokensNEQ applies the NEQ predicate on the "calibration_total_tokens" field.
func CalibrationTotalTokensNEQ(v int64) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldNEQ(FieldCalibrationTotalTokens, v))
}

// CalibrationTotalTokensIn applies the In predicate on the "calibration_total_tokens" field.
func CalibrationTotalTokensIn(vs ...int64) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldIn(FieldCalibrationTotalTokens, vs...))
}

// CalibrationTotalTokensNotIn applies the NotIn predicate on the "calibration_total_tokens" field.
func CalibrationTotalTokensNotIn(vs ...int64) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldNotIn(FieldCalibrationTotalTokens, vs...))
}

// CalibrationTotalTokensGT applies the GT predicate on the "calibration_total_tokens" field.
func CalibrationTotalTokensGT(v int64) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldGT(FieldCalibrationTotalTokens, v))
}

// CalibrationTotalTokensGTE applies the GTE predicate on the "calibration_total_tokens" field.
func CalibrationTotalTokensGTE(v int64) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldGTE(FieldCalibrationTotalTokens, v))
}

// CalibrationTotalTokensLT applies the LT predicate on the "calibration_total_tokens" field.
func CalibrationTotalTokensLT(v int64) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldLT(FieldCalibrationTotalTokens, v))
}

// CalibrationTotalTokensLTE applies the LTE predicate on the "calibration_total_tokens" field.
func CalibrationTotalTokensLTE(v int64) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldLTE(FieldCalibrationTotalTokens, v))
}

// RequestCountEQ applies the EQ predicate on the "request_count" field.
func RequestCountEQ(v int) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldEQ(FieldRequestCount, v))
}

// RequestCountNEQ applies the NEQ predicate on the "request_count" field.
func RequestCountNEQ(v int) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldNEQ(FieldRequestCount, v))
}

// RequestCountIn applies the In predicate on the "request_count" field.
func RequestCountIn(vs ...int) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldIn(FieldRequestCount, vs...))
}

// RequestCountNotIn applies the NotIn predicate on the "request_count" field.
func RequestCountNotIn(vs ...int) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldNotIn(FieldRequestCount, vs...))
}

// RequestCountGT applies the GT predicate on the "request_count" field.
func RequestCountGT(v int) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldGT(FieldRequestCount, v))
}

// RequestCountGTE applies the GTE predicate on the "request_count" field.
func RequestCountGTE(v int) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldGTE(FieldRequestCount, v))
}

// RequestCountLT applies the LT predicate on the "request_count" field.
func RequestCountLT(v int) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldLT(FieldRequestCount, v))
}

// RequestCountLTE applies the LTE predicate on the "request_count" field.
func RequestCountLTE(v int) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldLTE(FieldRequestCount, v))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldLTE(FieldExpiresAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AttributionClaimGroup) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AttributionClaimGroup) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AttributionClaimGroup) predicate.AttributionClaimGroup {
	return predicate.AttributionClaimGroup(sql.NotPredicates(p))
}
