// Code generated by ent, DO NOT EDIT.

package directoryoffboardingaction

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the directoryoffboardingaction type in the database.
	Label = "directory_offboarding_action"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldSourceID holds the string denoting the source_id field in the database.
	FieldSourceID = "source_id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldRelayUserID holds the string denoting the relay_user_id field in the database.
	FieldRelayUserID = "relay_user_id"
	// FieldDirectoryRunID holds the string denoting the directory_run_id field in the database.
	FieldDirectoryRunID = "directory_run_id"
	// FieldAction holds the string denoting the action field in the database.
	FieldAction = "action"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldReason holds the string denoting the reason field in the database.
	FieldReason = "reason"
	// FieldErrorMessage holds the string denoting the error_message field in the database.
	FieldErrorMessage = "error_message"
	// FieldPerformedByUserID holds the string denoting the performed_by_user_id field in the database.
	FieldPerformedByUserID = "performed_by_user_id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the directoryoffboardingaction in the database.
	Table = "directory_offboarding_actions"
)

// Columns holds all SQL columns for directoryoffboardingaction fields.
var Columns = []string{
	FieldID,
	FieldSourceID,
	FieldUserID,
	FieldRelayUserID,
	FieldDirectoryRunID,
	FieldAction,
	FieldStatus,
	FieldReason,
	FieldErrorMessage,
	FieldPerformedByUserID,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// Action defines the type for the "action" enum field.
type Action string

// Action values.
const (
	ActionDisableRelayUser Action = "disable_relay_user"
)

func (a Action) String() string {
	return string(a)
}

// ActionValidator is a validator for the "action" field enum values. It is called by the builders before save.
func ActionValidator(a Action) error {
	switch a {
	case ActionDisableRelayUser:
		return nil
	default:
		return fmt.Errorf("directoryoffboardingaction: invalid enum value for action field: %q", a)
	}
}

// Status defines the type for the "status" enum field.
type Status string

// StatusRunning is the default value of the Status enum.
const DefaultStatus = StatusRunning

// Status values.
const (
	StatusRunning       Status = "running"
	StatusSucceeded     Status = "succeeded"
	StatusFailed        Status = "failed"
	StatusPartialFailed Status = "partial_failed"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusRunning, StatusSucceeded, StatusFailed, StatusPartialFailed:
		return nil
	default:
		return fmt.Errorf("directoryoffboardingaction: invalid enum value for status field: %q", s)
	}
}

// OrderOption defines the ordering options for the DirectoryOffboardingAction queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// BySourceID orders the results by the source_id field.
func BySourceID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSourceID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByRelayUserID orders the results by the relay_user_id field.
func ByRelayUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRelayUserID, opts...).ToFunc()
}

// ByDirectoryRunID orders the results by the directory_run_id field.
func ByDirectoryRunID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDirectoryRunID, opts...).ToFunc()
}

// ByAction orders the results by the action field.
func ByAction(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAction, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByReason orders the results by the reason field.
func ByReason(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReason, opts...).ToFunc()
}

// ByErrorMessage orders the results by the error_message field.
func ByErrorMessage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldErrorMessage, opts...).ToFunc()
}

// ByPerformedByUserID orders the results by the performed_by_user_id field.
func ByPerformedByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPerformedByUserID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
