// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/ai-efficiency/backend/ent/agentmetadataevent"
	"github.com/ai-efficiency/backend/ent/session"
	"github.com/google/uuid"
)

// AgentMetadataEvent is the model entity for the AgentMetadataEvent schema.
type AgentMetadataEvent struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// SessionID holds the value of the "session_id" field.
	SessionID uuid.UUID `json:"session_id,omitempty"`
	// WorkspaceID holds the value of the "workspace_id" field.
	WorkspaceID *string `json:"workspace_id,omitempty"`
	// Source holds the value of the "source" field.
	Source agentmetadataevent.Source `json:"source,omitempty"`
	// SourceSessionID holds the value of the "source_session_id" field.
	SourceSessionID *string `json:"source_session_id,omitempty"`
	// UsageUnit holds the value of the "usage_unit" field.
	UsageUnit agentmetadataevent.UsageUnit `json:"usage_unit,omitempty"`
	// InputTokens holds the value of the "input_tokens" field.
	InputTokens int64 `json:"input_tokens,omitempty"`
	// OutputTokens holds the value of the "output_tokens" field.
	OutputTokens int64 `json:"output_tokens,omitempty"`
	// CachedInputTokens holds the value of the "cached_input_tokens" field.
	CachedInputTokens int64 `json:"cached_input_tokens,omitempty"`
	// ReasoningTokens holds the value of the "reasoning_tokens" field.
	ReasoningTokens int64 `json:"reasoning_tokens,omitempty"`
	// CreditUsage holds the value of the "credit_usage" field.
	CreditUsage float64 `json:"credit_usage,omitempty"`
	// ContextUsagePct holds the value of the "context_usage_pct" field.
	ContextUsagePct float64 `json:"context_usage_pct,omitempty"`
	// RawPayload holds the value of the "raw_payload" field.
	RawPayload map[string]interface{} `json:"raw_payload,omitempty"`
	// ObservedAt holds the value of the "observed_at" field.
	ObservedAt time.Time `json:"observed_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the AgentMetadataEventQuery when eager-loading is set.
	Edges        AgentMetadataEventEdges `json:"edges"`
	selectValues sql.SelectValues
}

// AgentMetadataEventEdges holds the relations/edges for other nodes in the graph.
type AgentMetadataEventEdges struct {
	// Session holds the value of the session edge.
	Session *Session `json:"session,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// SessionOrErr returns the Session value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AgentMetadataEventEdges) SessionOrErr() (*Session, error) {
	if e.Session != nil {
		return e.Session, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: session.Label}
	}
	return nil, &NotLoadedError{edge: "session"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AgentMetadataEvent) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case agentmetadataevent.FieldRawPayload:
			values[i] = new([]byte)
		case agentmetadataevent.FieldCreditUsage, agentmetadataevent.FieldContextUsagePct:
			values[i] = new(sql.NullFloat64)
		case agentmetadataevent.FieldID, agentmetadataevent.FieldInputTokens, agentmetadataevent.FieldOutputTokens, agentmetadataevent.FieldCachedInputTokens, agentmetadataevent.FieldReasoningTokens:
			values[i] = new(sql.NullInt64)
		case agentmetadataevent.FieldWorkspaceID, agentmetadataevent.FieldSource, agentmetadataevent.FieldSourceSessionID, agentmetadataevent.FieldUsageUnit:
			values[i] = new(sql.NullString)
		case agentmetadataevent.FieldObservedAt:
			values[i] = new(sql.NullTime)
		case agentmetadataevent.FieldSessionID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AgentMetadataEvent fields.
func (ame *AgentMetadataEvent) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case agentmetadataevent.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			ame.ID = int(value.Int64)
		case agentmetadataevent.FieldSessionID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field session_id", values[i])
			} else if value != nil {
				ame.SessionID = *value
			}
		case agentmetadataevent.FieldWorkspaceID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field workspace_id", values[i])
			} else if value.Valid {
				ame.WorkspaceID = new(string)
				*ame.WorkspaceID = value.String
			}
		case agentmetadataevent.FieldSource:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source", values[i])
			} else if value.Valid {
				ame.Source = agentmetadataevent.Source(value.String)
			}
		case agentmetadataevent.FieldSourceSessionID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source_session_id", values[i])
			} else if value.Valid {
				ame.SourceSessionID = new(string)
				*ame.SourceSessionID = value.String
			}
		case agentmetadataevent.FieldUsageUnit:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field usage_unit", values[i])
			} else if value.Valid {
				ame.UsageUnit = agentmetadataevent.UsageUnit(value.String)
			}
		case agentmetadataevent.FieldInputTokens:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field input_tokens", values[i])
			} else if value.Valid {
				ame.InputTokens = value.Int64
			}
		case agentmetadataevent.FieldOutputTokens:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field output_tokens", values[i])
			} else if value.Valid {
				ame.OutputTokens = value.Int64
			}
		case agentmetadataevent.FieldCachedInputTokens:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field cached_input_tokens", values[i])
			} else if value.Valid {
				ame.CachedInputTokens = value.Int64
			}
		case agentmetadataevent.FieldReasoningTokens:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field reasoning_tokens", values[i])
			} else if value.Valid {
				ame.ReasoningTokens = value.Int64
			}
		case agentmetadataevent.FieldCreditUsage:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field credit_usage", values[i])
			} else if value.Valid {
				ame.CreditUsage = value.Float64
			}
		case agentmetadataevent.FieldContextUsagePct:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field context_usage_pct", values[i])
			} else if value.Valid {
				ame.ContextUsagePct = value.Float64
			}
		case agentmetadataevent.FieldRawPayload:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field raw_payload", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &ame.RawPayload); err != nil {
					return fmt.Errorf("unmarshal field raw_payload: %w", err)
				}
			}
		case agentmetadataevent.FieldObservedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field observed_at", values[i])
			} else if value.Valid {
				ame.ObservedAt = value.Time
			}
		default:
			ame.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AgentMetadataEvent.
// This includes values selected through modifiers, order, etc.
func (ame *AgentMetadataEvent) Value(name string) (ent.Value, error) {
	return ame.selectValues.Get(name)
}

// QuerySession queries the "session" edge of the AgentMetadataEvent entity.
func (ame *AgentMetadataEvent) QuerySession() *SessionQuery {
	return NewAgentMetadataEventClient(ame.config).QuerySession(ame)
}

// Update returns a builder for updating this AgentMetadataEvent.
// Note that you need to call AgentMetadataEvent.Unwrap() before calling this method if this AgentMetadataEvent
// was returned from a transaction, and the transaction was committed or rolled back.
func (ame *AgentMetadataEvent) Update() *AgentMetadataEventUpdateOne {
	return NewAgentMetadataEventClient(ame.config).UpdateOne(ame)
}

// Unwrap unwraps the AgentMetadataEvent entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (ame *AgentMetadataEvent) Unwrap() *AgentMetadataEvent {
	_tx, ok := ame.config.driver.(*txDriver)
	if !ok {
		panic("ent: AgentMetadataEvent is not a transactional entity")
	}
	ame.config.driver = _tx.drv
	return ame
}

// String implements the fmt.Stringer.
func (ame *AgentMetadataEvent) String() string {
	var builder strings.Builder
	builder.WriteString("AgentMetadataEvent(")
	builder.WriteString(fmt.Sprintf("id=%v, ", ame.ID))
	builder.WriteString("session_id=")
	builder.WriteString(fmt.Sprintf("%v", ame.SessionID))
	builder.WriteString(", ")
	if v := ame.WorkspaceID; v != nil {
		builder.WriteString("workspace_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("source=")
	builder.WriteString(fmt.Sprintf("%v", ame.Source))
	builder.WriteString(", ")
	if v := ame.SourceSessionID; v != nil {
		builder.WriteString("source_session_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("usage_unit=")
	builder.WriteString(fmt.Sprintf("%v", ame.UsageUnit))
	builder.WriteString(", ")
	builder.WriteString("input_tokens=")
	builder.WriteString(fmt.Sprintf("%v", ame.InputTokens))
	builder.WriteString(", ")
	builder.WriteString("output_tokens=")
	builder.WriteString(fmt.Sprintf("%v", ame.OutputTokens))
	builder.WriteString(", ")
	builder.WriteString("cached_input_tokens=")
	builder.WriteString(fmt.Sprintf("%v", ame.CachedInputTokens))
	builder.WriteString(", ")
	builder.WriteString("reasoning_tokens=")
	builder.WriteString(fmt.Sprintf("%v", ame.ReasoningTokens))
	builder.WriteString(", ")
	builder.WriteString("credit_usage=")
	builder.WriteString(fmt.Sprintf("%v", ame.CreditUsage))
	builder.WriteString(", ")
	builder.WriteString("context_usage_pct=")
	builder.WriteString(fmt.Sprintf("%v", ame.ContextUsagePct))
	builder.WriteString(", ")
	builder.WriteString("raw_payload=")
	builder.WriteString(fmt.Sprintf("%v", ame.RawPayload))
	builder.WriteString(", ")
	builder.WriteString("observed_at=")
	builder.WriteString(ame.ObservedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// AgentMetadataEvents is a parsable slice of AgentMetadataEvent.
type AgentMetadataEvents []*AgentMetadataEvent
