// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ai-efficiency/backend/ent/aiscanresult"
	"github.com/ai-efficiency/backend/ent/predicate"
)

// AiScanResultDelete is the builder for deleting a AiScanResult entity.
type AiScanResultDelete struct {
	config
	hooks    []Hook
	mutation *AiScanResultMutation
}

// Where appends a list predicates to the AiScanResultDelete builder.
func (asrd *AiScanResultDelete) Where(ps ...predicate.AiScanResult) *AiScanResultDelete {
	asrd.mutation.Where(ps...)
	return asrd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (asrd *AiScanResultDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, asrd.sqlExec, asrd.mutation, asrd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (asrd *AiScanResultDelete) ExecX(ctx context.Context) int {
	n, err := asrd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (asrd *AiScanResultDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(aiscanresult.Table, sqlgraph.NewFieldSpec(aiscanresult.FieldID, field.TypeInt))
	if ps := asrd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, asrd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	asrd.mutation.done = true
	return affected, err
}

// AiScanResultDeleteOne is the builder for deleting a single AiScanResult entity.
type AiScanResultDeleteOne struct {
	asrd *AiScanResultDelete
}

// Where appends a list predicates to the AiScanResultDelete builder.
func (asrdo *AiScanResultDeleteOne) Where(ps ...predicate.AiScanResult) *AiScanResultDeleteOne {
	asrdo.asrd.mutation.Where(ps...)
	return asrdo
}

// Exec executes the deletion query.
func (asrdo *AiScanResultDeleteOne) Exec(ctx context.Context) error {
	n, err := asrdo.asrd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{aiscanresult.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (asrdo *AiScanResultDeleteOne) ExecX(ctx context.Context) {
	if err := asrdo.Exec(ctx); err != nil {
		panic(err)
	}
}
