// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/ai-efficiency/backend/ent/attributionusagepoolcommit"
)

// AttributionUsagePoolCommit is the model entity for the AttributionUsagePoolCommit schema.
type AttributionUsagePoolCommit struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// PoolID holds the value of the "pool_id" field.
	PoolID int `json:"pool_id,omitempty"`
	// RepoConfigID holds the value of the "repo_config_id" field.
	RepoConfigID int `json:"repo_config_id,omitempty"`
	// CommitSha holds the value of the "commit_sha" field.
	CommitSha string `json:"commit_sha,omitempty"`
	// RelationKind holds the value of the "relation_kind" field.
	RelationKind attributionusagepoolcommit.RelationKind `json:"relation_kind,omitempty"`
	// Orphaned holds the value of the "orphaned" field.
	Orphaned bool `json:"orphaned,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AttributionUsagePoolCommit) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case attributionusagepoolcommit.FieldOrphaned:
			values[i] = new(sql.NullBool)
		case attributionusagepoolcommit.FieldID, attributionusagepoolcommit.FieldPoolID, attributionusagepoolcommit.FieldRepoConfigID:
			values[i] = new(sql.NullInt64)
		case attributionusagepoolcommit.FieldCommitSha, attributionusagepoolcommit.FieldRelationKind:
			values[i] = new(sql.NullString)
		case attributionusagepoolcommit.FieldCreatedAt, attributionusagepoolcommit.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AttributionUsagePoolCommit fields.
func (aupc *AttributionUsagePoolCommit) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case attributionusagepoolcommit.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			aupc.ID = int(value.Int64)
		case attributionusagepoolcommit.FieldPoolID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field pool_id", values[i])
			} else if value.Valid {
				aupc.PoolID = int(value.Int64)
			}
		case attributionusagepoolcommit.FieldRepoConfigID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field repo_config_id", values[i])
			} else if value.Valid {
				aupc.RepoConfigID = int(value.Int64)
			}
		case attributionusagepoolcommit.FieldCommitSha:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field commit_sha", values[i])
			} else if value.Valid {
				aupc.CommitSha = value.String
			}
		case attributionusagepoolcommit.FieldRelationKind:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field relation_kind", values[i])
			} else if value.Valid {
				aupc.RelationKind = attributionusagepoolcommit.RelationKind(value.String)
			}
		case attributionusagepoolcommit.FieldOrphaned:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field orphaned", values[i])
			} else if value.Valid {
				aupc.Orphaned = value.Bool
			}
		case attributionusagepoolcommit.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				aupc.CreatedAt = value.Time
			}
		case attributionusagepoolcommit.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				aupc.UpdatedAt = value.Time
			}
		default:
			aupc.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AttributionUsagePoolCommit.
// This includes values selected through modifiers, order, etc.
func (aupc *AttributionUsagePoolCommit) Value(name string) (ent.Value, error) {
	return aupc.selectValues.Get(name)
}

// Update returns a builder for updating this AttributionUsagePoolCommit.
// Note that you need to call AttributionUsagePoolCommit.Unwrap() before calling this method if this AttributionUsagePoolCommit
// was returned from a transaction, and the transaction was committed or rolled back.
func (aupc *AttributionUsagePoolCommit) Update() *AttributionUsagePoolCommitUpdateOne {
	return NewAttributionUsagePoolCommitClient(aupc.config).UpdateOne(aupc)
}

// Unwrap unwraps the AttributionUsagePoolCommit entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (aupc *AttributionUsagePoolCommit) Unwrap() *AttributionUsagePoolCommit {
	_tx, ok := aupc.config.driver.(*txDriver)
	if !ok {
		panic("ent: AttributionUsagePoolCommit is not a transactional entity")
	}
	aupc.config.driver = _tx.drv
	return aupc
}

// String implements the fmt.Stringer.
func (aupc *AttributionUsagePoolCommit) String() string {
	var builder strings.Builder
	builder.WriteString("AttributionUsagePoolCommit(")
	builder.WriteString(fmt.Sprintf("id=%v, ", aupc.ID))
	builder.WriteString("pool_id=")
	builder.WriteString(fmt.Sprintf("%v", aupc.PoolID))
	builder.WriteString(", ")
	builder.WriteString("repo_config_id=")
	builder.WriteString(fmt.Sprintf("%v", aupc.RepoConfigID))
	builder.WriteString(", ")
	builder.WriteString("commit_sha=")
	builder.WriteString(aupc.CommitSha)
	builder.WriteString(", ")
	builder.WriteString("relation_kind=")
	builder.WriteString(fmt.Sprintf("%v", aupc.RelationKind))
	builder.WriteString(", ")
	builder.WriteString("orphaned=")
	builder.WriteString(fmt.Sprintf("%v", aupc.Orphaned))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(aupc.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(aupc.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// AttributionUsagePoolCommits is a parsable slice of AttributionUsagePoolCommit.
type AttributionUsagePoolCommits []*AttributionUsagePoolCommit
