// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/ai-efficiency/backend/ent/commitrewrite"
	"github.com/ai-efficiency/backend/ent/session"
	"github.com/google/uuid"
)

// CommitRewrite is the model entity for the CommitRewrite schema.
type CommitRewrite struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// EventID holds the value of the "event_id" field.
	EventID string `json:"event_id,omitempty"`
	// SessionID holds the value of the "session_id" field.
	SessionID *uuid.UUID `json:"session_id,omitempty"`
	// WorkspaceID holds the value of the "workspace_id" field.
	WorkspaceID string `json:"workspace_id,omitempty"`
	// RepoConfigID holds the value of the "repo_config_id" field.
	RepoConfigID int `json:"repo_config_id,omitempty"`
	// RewriteType holds the value of the "rewrite_type" field.
	RewriteType commitrewrite.RewriteType `json:"rewrite_type,omitempty"`
	// OldCommitSha holds the value of the "old_commit_sha" field.
	OldCommitSha string `json:"old_commit_sha,omitempty"`
	// NewCommitSha holds the value of the "new_commit_sha" field.
	NewCommitSha string `json:"new_commit_sha,omitempty"`
	// BindingSource holds the value of the "binding_source" field.
	BindingSource commitrewrite.BindingSource `json:"binding_source,omitempty"`
	// CapturedAt holds the value of the "captured_at" field.
	CapturedAt time.Time `json:"captured_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the CommitRewriteQuery when eager-loading is set.
	Edges        CommitRewriteEdges `json:"edges"`
	selectValues sql.SelectValues
}

// CommitRewriteEdges holds the relations/edges for other nodes in the graph.
type CommitRewriteEdges struct {
	// Session holds the value of the session edge.
	Session *Session `json:"session,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// SessionOrErr returns the Session value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e CommitRewriteEdges) SessionOrErr() (*Session, error) {
	if e.Session != nil {
		return e.Session, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: session.Label}
	}
	return nil, &NotLoadedError{edge: "session"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*CommitRewrite) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case commitrewrite.FieldSessionID:
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case commitrewrite.FieldID, commitrewrite.FieldRepoConfigID:
			values[i] = new(sql.NullInt64)
		case commitrewrite.FieldEventID, commitrewrite.FieldWorkspaceID, commitrewrite.FieldRewriteType, commitrewrite.FieldOldCommitSha, commitrewrite.FieldNewCommitSha, commitrewrite.FieldBindingSource:
			values[i] = new(sql.NullString)
		case commitrewrite.FieldCapturedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the CommitRewrite fields.
func (cr *CommitRewrite) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case commitrewrite.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			cr.ID = int(value.Int64)
		case commitrewrite.FieldEventID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field event_id", values[i])
			} else if value.Valid {
				cr.EventID = value.String
			}
		case commitrewrite.FieldSessionID:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field session_id", values[i])
			} else if value.Valid {
				cr.SessionID = new(uuid.UUID)
				*cr.SessionID = *value.S.(*uuid.UUID)
			}
		case commitrewrite.FieldWorkspaceID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field workspace_id", values[i])
			} else if value.Valid {
				cr.WorkspaceID = value.String
			}
		case commitrewrite.FieldRepoConfigID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field repo_config_id", values[i])
			} else if value.Valid {
				cr.RepoConfigID = int(value.Int64)
			}
		case commitrewrite.FieldRewriteType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field rewrite_type", values[i])
			} else if value.Valid {
				cr.RewriteType = commitrewrite.RewriteType(value.String)
			}
		case commitrewrite.FieldOldCommitSha:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field old_commit_sha", values[i])
			} else if value.Valid {
				cr.OldCommitSha = value.String
			}
		case commitrewrite.FieldNewCommitSha:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field new_commit_sha", values[i])
			} else if value.Valid {
				cr.NewCommitSha = value.String
			}
		case commitrewrite.FieldBindingSource:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field binding_source", values[i])
			} else if value.Valid {
				cr.BindingSource = commitrewrite.BindingSource(value.String)
			}
		case commitrewrite.FieldCapturedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field captured_at", values[i])
			} else if value.Valid {
				cr.CapturedAt = value.Time
			}
		default:
			cr.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the CommitRewrite.
// This includes values selected through modifiers, order, etc.
func (cr *CommitRewrite) Value(name string) (ent.Value, error) {
	return cr.selectValues.Get(name)
}

// QuerySession queries the "session" edge of the CommitRewrite entity.
func (cr *CommitRewrite) QuerySession() *SessionQuery {
	return NewCommitRewriteClient(cr.config).QuerySession(cr)
}

// Update returns a builder for updating this CommitRewrite.
// Note that you need to call CommitRewrite.Unwrap() before calling this method if this CommitRewrite
// was returned from a transaction, and the transaction was committed or rolled back.
func (cr *CommitRewrite) Update() *CommitRewriteUpdateOne {
	return NewCommitRewriteClient(cr.config).UpdateOne(cr)
}

// Unwrap unwraps the CommitRewrite entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (cr *CommitRewrite) Unwrap() *CommitRewrite {
	_tx, ok := cr.config.driver.(*txDriver)
	if !ok {
		panic("ent: CommitRewrite is not a transactional entity")
	}
	cr.config.driver = _tx.drv
	return cr
}

// String implements the fmt.Stringer.
func (cr *CommitRewrite) String() string {
	var builder strings.Builder
	builder.WriteString("CommitRewrite(")
	builder.WriteString(fmt.Sprintf("id=%v, ", cr.ID))
	builder.WriteString("event_id=")
	builder.WriteString(cr.EventID)
	builder.WriteString(", ")
	if v := cr.SessionID; v != nil {
		builder.WriteString("session_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("workspace_id=")
	builder.WriteString(cr.WorkspaceID)
	builder.WriteString(", ")
	builder.WriteString("repo_config_id=")
	builder.WriteString(fmt.Sprintf("%v", cr.RepoConfigID))
	builder.WriteString(", ")
	builder.WriteString("rewrite_type=")
	builder.WriteString(fmt.Sprintf("%v", cr.RewriteType))
	builder.WriteString(", ")
	builder.WriteString("old_commit_sha=")
	builder.WriteString(cr.OldCommitSha)
	builder.WriteString(", ")
	builder.WriteString("new_commit_sha=")
	builder.WriteString(cr.NewCommitSha)
	builder.WriteString(", ")
	builder.WriteString("binding_source=")
	builder.WriteString(fmt.Sprintf("%v", cr.BindingSource))
	builder.WriteString(", ")
	builder.WriteString("captured_at=")
	builder.WriteString(cr.CapturedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// CommitRewrites is a parsable slice of CommitRewrite.
type CommitRewrites []*CommitRewrite
