// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ai-efficiency/backend/ent/commitrewrite"
	"github.com/ai-efficiency/backend/ent/predicate"
	"github.com/ai-efficiency/backend/ent/repoconfig"
	"github.com/ai-efficiency/backend/ent/session"
	"github.com/google/uuid"
)

// CommitRewriteQuery is the builder for querying CommitRewrite entities.
type CommitRewriteQuery struct {
	config
	ctx            *QueryContext
	order          []commitrewrite.OrderOption
	inters         []Interceptor
	predicates     []predicate.CommitRewrite
	withSession    *SessionQuery
	withRepoConfig *RepoConfigQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the CommitRewriteQuery builder.
func (crq *CommitRewriteQuery) Where(ps ...predicate.CommitRewrite) *CommitRewriteQuery {
	crq.predicates = append(crq.predicates, ps...)
	return crq
}

// Limit the number of records to be returned by this query.
func (crq *CommitRewriteQuery) Limit(limit int) *CommitRewriteQuery {
	crq.ctx.Limit = &limit
	return crq
}

// Offset to start from.
func (crq *CommitRewriteQuery) Offset(offset int) *CommitRewriteQuery {
	crq.ctx.Offset = &offset
	return crq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (crq *CommitRewriteQuery) Unique(unique bool) *CommitRewriteQuery {
	crq.ctx.Unique = &unique
	return crq
}

// Order specifies how the records should be ordered.
func (crq *CommitRewriteQuery) Order(o ...commitrewrite.OrderOption) *CommitRewriteQuery {
	crq.order = append(crq.order, o...)
	return crq
}

// QuerySession chains the current query on the "session" edge.
func (crq *CommitRewriteQuery) QuerySession() *SessionQuery {
	query := (&SessionClient{config: crq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := crq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := crq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(commitrewrite.Table, commitrewrite.FieldID, selector),
			sqlgraph.To(session.Table, session.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, commitrewrite.SessionTable, commitrewrite.SessionColumn),
		)
		fromU = sqlgraph.SetNeighbors(crq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryRepoConfig chains the current query on the "repo_config" edge.
func (crq *CommitRewriteQuery) QueryRepoConfig() *RepoConfigQuery {
	query := (&RepoConfigClient{config: crq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := crq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := crq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(commitrewrite.Table, commitrewrite.FieldID, selector),
			sqlgraph.To(repoconfig.Table, repoconfig.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, commitrewrite.RepoConfigTable, commitrewrite.RepoConfigColumn),
		)
		fromU = sqlgraph.SetNeighbors(crq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first CommitRewrite entity from the query.
// Returns a *NotFoundError when no CommitRewrite was found.
func (crq *CommitRewriteQuery) First(ctx context.Context) (*CommitRewrite, error) {
	nodes, err := crq.Limit(1).All(setContextOp(ctx, crq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{commitrewrite.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (crq *CommitRewriteQuery) FirstX(ctx context.Context) *CommitRewrite {
	node, err := crq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first CommitRewrite ID from the query.
// Returns a *NotFoundError when no CommitRewrite ID was found.
func (crq *CommitRewriteQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = crq.Limit(1).IDs(setContextOp(ctx, crq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{commitrewrite.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (crq *CommitRewriteQuery) FirstIDX(ctx context.Context) int {
	id, err := crq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single CommitRewrite entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one CommitRewrite entity is found.
// Returns a *NotFoundError when no CommitRewrite entities are found.
func (crq *CommitRewriteQuery) Only(ctx context.Context) (*CommitRewrite, error) {
	nodes, err := crq.Limit(2).All(setContextOp(ctx, crq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{commitrewrite.Label}
	default:
		return nil, &NotSingularError{commitrewrite.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (crq *CommitRewriteQuery) OnlyX(ctx context.Context) *CommitRewrite {
	node, err := crq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only CommitRewrite ID in the query.
// Returns a *NotSingularError when more than one CommitRewrite ID is found.
// Returns a *NotFoundError when no entities are found.
func (crq *CommitRewriteQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = crq.Limit(2).IDs(setContextOp(ctx, crq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{commitrewrite.Label}
	default:
		err = &NotSingularError{commitrewrite.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (crq *CommitRewriteQuery) OnlyIDX(ctx context.Context) int {
	id, err := crq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of CommitRewrites.
func (crq *CommitRewriteQuery) All(ctx context.Context) ([]*CommitRewrite, error) {
	ctx = setContextOp(ctx, crq.ctx, ent.OpQueryAll)
	if err := crq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*CommitRewrite, *CommitRewriteQuery]()
	return withInterceptors[[]*CommitRewrite](ctx, crq, qr, crq.inters)
}

// AllX is like All, but panics if an error occurs.
func (crq *CommitRewriteQuery) AllX(ctx context.Context) []*CommitRewrite {
	nodes, err := crq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of CommitRewrite IDs.
func (crq *CommitRewriteQuery) IDs(ctx context.Context) (ids []int, err error) {
	if crq.ctx.Unique == nil && crq.path != nil {
		crq.Unique(true)
	}
	ctx = setContextOp(ctx, crq.ctx, ent.OpQueryIDs)
	if err = crq.Select(commitrewrite.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (crq *CommitRewriteQuery) IDsX(ctx context.Context) []int {
	ids, err := crq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (crq *CommitRewriteQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, crq.ctx, ent.OpQueryCount)
	if err := crq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, crq, querierCount[*CommitRewriteQuery](), crq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (crq *CommitRewriteQuery) CountX(ctx context.Context) int {
	count, err := crq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (crq *CommitRewriteQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, crq.ctx, ent.OpQueryExist)
	switch _, err := crq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (crq *CommitRewriteQuery) ExistX(ctx context.Context) bool {
	exist, err := crq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the CommitRewriteQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (crq *CommitRewriteQuery) Clone() *CommitRewriteQuery {
	if crq == nil {
		return nil
	}
	return &CommitRewriteQuery{
		config:         crq.config,
		ctx:            crq.ctx.Clone(),
		order:          append([]commitrewrite.OrderOption{}, crq.order...),
		inters:         append([]Interceptor{}, crq.inters...),
		predicates:     append([]predicate.CommitRewrite{}, crq.predicates...),
		withSession:    crq.withSession.Clone(),
		withRepoConfig: crq.withRepoConfig.Clone(),
		// clone intermediate query.
		sql:  crq.sql.Clone(),
		path: crq.path,
	}
}

// WithSession tells the query-builder to eager-load the nodes that are connected to
// the "session" edge. The optional arguments are used to configure the query builder of the edge.
func (crq *CommitRewriteQuery) WithSession(opts ...func(*SessionQuery)) *CommitRewriteQuery {
	query := (&SessionClient{config: crq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	crq.withSession = query
	return crq
}

// WithRepoConfig tells the query-builder to eager-load the nodes that are connected to
// the "repo_config" edge. The optional arguments are used to configure the query builder of the edge.
func (crq *CommitRewriteQuery) WithRepoConfig(opts ...func(*RepoConfigQuery)) *CommitRewriteQuery {
	query := (&RepoConfigClient{config: crq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	crq.withRepoConfig = query
	return crq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		EventID string `json:"event_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.CommitRewrite.Query().
//		GroupBy(commitrewrite.FieldEventID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (crq *CommitRewriteQuery) GroupBy(field string, fields ...string) *CommitRewriteGroupBy {
	crq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &CommitRewriteGroupBy{build: crq}
	grbuild.flds = &crq.ctx.Fields
	grbuild.label = commitrewrite.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		EventID string `json:"event_id,omitempty"`
//	}
//
//	client.CommitRewrite.Query().
//		Select(commitrewrite.FieldEventID).
//		Scan(ctx, &v)
func (crq *CommitRewriteQuery) Select(fields ...string) *CommitRewriteSelect {
	crq.ctx.Fields = append(crq.ctx.Fields, fields...)
	sbuild := &CommitRewriteSelect{CommitRewriteQuery: crq}
	sbuild.label = commitrewrite.Label
	sbuild.flds, sbuild.scan = &crq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a CommitRewriteSelect configured with the given aggregations.
func (crq *CommitRewriteQuery) Aggregate(fns ...AggregateFunc) *CommitRewriteSelect {
	return crq.Select().Aggregate(fns...)
}

func (crq *CommitRewriteQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range crq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, crq); err != nil {
				return err
			}
		}
	}
	for _, f := range crq.ctx.Fields {
		if !commitrewrite.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if crq.path != nil {
		prev, err := crq.path(ctx)
		if err != nil {
			return err
		}
		crq.sql = prev
	}
	return nil
}

func (crq *CommitRewriteQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*CommitRewrite, error) {
	var (
		nodes       = []*CommitRewrite{}
		_spec       = crq.querySpec()
		loadedTypes = [2]bool{
			crq.withSession != nil,
			crq.withRepoConfig != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*CommitRewrite).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &CommitRewrite{config: crq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, crq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := crq.withSession; query != nil {
		if err := crq.loadSession(ctx, query, nodes, nil,
			func(n *CommitRewrite, e *Session) { n.Edges.Session = e }); err != nil {
			return nil, err
		}
	}
	if query := crq.withRepoConfig; query != nil {
		if err := crq.loadRepoConfig(ctx, query, nodes, nil,
			func(n *CommitRewrite, e *RepoConfig) { n.Edges.RepoConfig = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (crq *CommitRewriteQuery) loadSession(ctx context.Context, query *SessionQuery, nodes []*CommitRewrite, init func(*CommitRewrite), assign func(*CommitRewrite, *Session)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*CommitRewrite)
	for i := range nodes {
		if nodes[i].SessionID == nil {
			continue
		}
		fk := *nodes[i].SessionID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(session.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "session_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (crq *CommitRewriteQuery) loadRepoConfig(ctx context.Context, query *RepoConfigQuery, nodes []*CommitRewrite, init func(*CommitRewrite), assign func(*CommitRewrite, *RepoConfig)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*CommitRewrite)
	for i := range nodes {
		fk := nodes[i].RepoConfigID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(repoconfig.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "repo_config_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (crq *CommitRewriteQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := crq.querySpec()
	_spec.Node.Columns = crq.ctx.Fields
	if len(crq.ctx.Fields) > 0 {
		_spec.Unique = crq.ctx.Unique != nil && *crq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, crq.driver, _spec)
}

func (crq *CommitRewriteQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(commitrewrite.Table, commitrewrite.Columns, sqlgraph.NewFieldSpec(commitrewrite.FieldID, field.TypeInt))
	_spec.From = crq.sql
	if unique := crq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if crq.path != nil {
		_spec.Unique = true
	}
	if fields := crq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, commitrewrite.FieldID)
		for i := range fields {
			if fields[i] != commitrewrite.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if crq.withSession != nil {
			_spec.Node.AddColumnOnce(commitrewrite.FieldSessionID)
		}
		if crq.withRepoConfig != nil {
			_spec.Node.AddColumnOnce(commitrewrite.FieldRepoConfigID)
		}
	}
	if ps := crq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := crq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := crq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := crq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (crq *CommitRewriteQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(crq.driver.Dialect())
	t1 := builder.Table(commitrewrite.Table)
	columns := crq.ctx.Fields
	if len(columns) == 0 {
		columns = commitrewrite.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if crq.sql != nil {
		selector = crq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if crq.ctx.Unique != nil && *crq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range crq.predicates {
		p(selector)
	}
	for _, p := range crq.order {
		p(selector)
	}
	if offset := crq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := crq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// CommitRewriteGroupBy is the group-by builder for CommitRewrite entities.
type CommitRewriteGroupBy struct {
	selector
	build *CommitRewriteQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (crgb *CommitRewriteGroupBy) Aggregate(fns ...AggregateFunc) *CommitRewriteGroupBy {
	crgb.fns = append(crgb.fns, fns...)
	return crgb
}

// Scan applies the selector query and scans the result into the given value.
func (crgb *CommitRewriteGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, crgb.build.ctx, ent.OpQueryGroupBy)
	if err := crgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*CommitRewriteQuery, *CommitRewriteGroupBy](ctx, crgb.build, crgb, crgb.build.inters, v)
}

func (crgb *CommitRewriteGroupBy) sqlScan(ctx context.Context, root *CommitRewriteQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(crgb.fns))
	for _, fn := range crgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*crgb.flds)+len(crgb.fns))
		for _, f := range *crgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*crgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := crgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// CommitRewriteSelect is the builder for selecting fields of CommitRewrite entities.
type CommitRewriteSelect struct {
	*CommitRewriteQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (crs *CommitRewriteSelect) Aggregate(fns ...AggregateFunc) *CommitRewriteSelect {
	crs.fns = append(crs.fns, fns...)
	return crs
}

// Scan applies the selector query and scans the result into the given value.
func (crs *CommitRewriteSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, crs.ctx, ent.OpQuerySelect)
	if err := crs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*CommitRewriteQuery, *CommitRewriteSelect](ctx, crs.CommitRewriteQuery, crs, crs.inters, v)
}

func (crs *CommitRewriteSelect) sqlScan(ctx context.Context, root *CommitRewriteQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(crs.fns))
	for _, fn := range crs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*crs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := crs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
