// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/ai-efficiency/backend/ent/directorysyncrun"
)

// DirectorySyncRun is the model entity for the DirectorySyncRun schema.
type DirectorySyncRun struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// SourceID holds the value of the "source_id" field.
	SourceID int `json:"source_id,omitempty"`
	// Mode holds the value of the "mode" field.
	Mode directorysyncrun.Mode `json:"mode,omitempty"`
	// Trigger holds the value of the "trigger" field.
	Trigger directorysyncrun.Trigger `json:"trigger,omitempty"`
	// Status holds the value of the "status" field.
	Status directorysyncrun.Status `json:"status,omitempty"`
	// Phase holds the value of the "phase" field.
	Phase directorysyncrun.Phase `json:"phase,omitempty"`
	// StartedAt holds the value of the "started_at" field.
	StartedAt *time.Time `json:"started_at,omitempty"`
	// CompletedAt holds the value of the "completed_at" field.
	CompletedAt *time.Time `json:"completed_at,omitempty"`
	// HTTPRequestCount holds the value of the "http_request_count" field.
	HTTPRequestCount int `json:"http_request_count,omitempty"`
	// DepartmentCount holds the value of the "department_count" field.
	DepartmentCount int `json:"department_count,omitempty"`
	// MemberCount holds the value of the "member_count" field.
	MemberCount int `json:"member_count,omitempty"`
	// InvalidMemberCount holds the value of the "invalid_member_count" field.
	InvalidMemberCount int `json:"invalid_member_count,omitempty"`
	// WarningCount holds the value of the "warning_count" field.
	WarningCount int `json:"warning_count,omitempty"`
	// ErrorMessage holds the value of the "error_message" field.
	ErrorMessage *string `json:"error_message,omitempty"`
	// Warnings holds the value of the "warnings" field.
	Warnings []map[string]interface{} `json:"warnings,omitempty"`
	// Summary holds the value of the "summary" field.
	Summary map[string]interface{} `json:"summary,omitempty"`
	// PreviewDiff holds the value of the "preview_diff" field.
	PreviewDiff map[string]interface{} `json:"preview_diff,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*DirectorySyncRun) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case directorysyncrun.FieldWarnings, directorysyncrun.FieldSummary, directorysyncrun.FieldPreviewDiff:
			values[i] = new([]byte)
		case directorysyncrun.FieldID, directorysyncrun.FieldSourceID, directorysyncrun.FieldHTTPRequestCount, directorysyncrun.FieldDepartmentCount, directorysyncrun.FieldMemberCount, directorysyncrun.FieldInvalidMemberCount, directorysyncrun.FieldWarningCount:
			values[i] = new(sql.NullInt64)
		case directorysyncrun.FieldMode, directorysyncrun.FieldTrigger, directorysyncrun.FieldStatus, directorysyncrun.FieldPhase, directorysyncrun.FieldErrorMessage:
			values[i] = new(sql.NullString)
		case directorysyncrun.FieldStartedAt, directorysyncrun.FieldCompletedAt, directorysyncrun.FieldCreatedAt, directorysyncrun.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the DirectorySyncRun fields.
func (dsr *DirectorySyncRun) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case directorysyncrun.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			dsr.ID = int(value.Int64)
		case directorysyncrun.FieldSourceID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field source_id", values[i])
			} else if value.Valid {
				dsr.SourceID = int(value.Int64)
			}
		case directorysyncrun.FieldMode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field mode", values[i])
			} else if value.Valid {
				dsr.Mode = directorysyncrun.Mode(value.String)
			}
		case directorysyncrun.FieldTrigger:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field trigger", values[i])
			} else if value.Valid {
				dsr.Trigger = directorysyncrun.Trigger(value.String)
			}
		case directorysyncrun.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				dsr.Status = directorysyncrun.Status(value.String)
			}
		case directorysyncrun.FieldPhase:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field phase", values[i])
			} else if value.Valid {
				dsr.Phase = directorysyncrun.Phase(value.String)
			}
		case directorysyncrun.FieldStartedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field started_at", values[i])
			} else if value.Valid {
				dsr.StartedAt = new(time.Time)
				*dsr.StartedAt = value.Time
			}
		case directorysyncrun.FieldCompletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field completed_at", values[i])
			} else if value.Valid {
				dsr.CompletedAt = new(time.Time)
				*dsr.CompletedAt = value.Time
			}
		case directorysyncrun.FieldHTTPRequestCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field http_request_count", values[i])
			} else if value.Valid {
				dsr.HTTPRequestCount = int(value.Int64)
			}
		case directorysyncrun.FieldDepartmentCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field department_count", values[i])
			} else if value.Valid {
				dsr.DepartmentCount = int(value.Int64)
			}
		case directorysyncrun.FieldMemberCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field member_count", values[i])
			} else if value.Valid {
				dsr.MemberCount = int(value.Int64)
			}
		case directorysyncrun.FieldInvalidMemberCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field invalid_member_count", values[i])
			} else if value.Valid {
				dsr.InvalidMemberCount = int(value.Int64)
			}
		case directorysyncrun.FieldWarningCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field warning_count", values[i])
			} else if value.Valid {
				dsr.WarningCount = int(value.Int64)
			}
		case directorysyncrun.FieldErrorMessage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error_message", values[i])
			} else if value.Valid {
				dsr.ErrorMessage = new(string)
				*dsr.ErrorMessage = value.String
			}
		case directorysyncrun.FieldWarnings:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field warnings", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &dsr.Warnings); err != nil {
					return fmt.Errorf("unmarshal field warnings: %w", err)
				}
			}
		case directorysyncrun.FieldSummary:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field summary", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &dsr.Summary); err != nil {
					return fmt.Errorf("unmarshal field summary: %w", err)
				}
			}
		case directorysyncrun.FieldPreviewDiff:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field preview_diff", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &dsr.PreviewDiff); err != nil {
					return fmt.Errorf("unmarshal field preview_diff: %w", err)
				}
			}
		case directorysyncrun.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				dsr.CreatedAt = value.Time
			}
		case directorysyncrun.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				dsr.UpdatedAt = value.Time
			}
		default:
			dsr.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the DirectorySyncRun.
// This includes values selected through modifiers, order, etc.
func (dsr *DirectorySyncRun) Value(name string) (ent.Value, error) {
	return dsr.selectValues.Get(name)
}

// Update returns a builder for updating this DirectorySyncRun.
// Note that you need to call DirectorySyncRun.Unwrap() before calling this method if this DirectorySyncRun
// was returned from a transaction, and the transaction was committed or rolled back.
func (dsr *DirectorySyncRun) Update() *DirectorySyncRunUpdateOne {
	return NewDirectorySyncRunClient(dsr.config).UpdateOne(dsr)
}

// Unwrap unwraps the DirectorySyncRun entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (dsr *DirectorySyncRun) Unwrap() *DirectorySyncRun {
	_tx, ok := dsr.config.driver.(*txDriver)
	if !ok {
		panic("ent: DirectorySyncRun is not a transactional entity")
	}
	dsr.config.driver = _tx.drv
	return dsr
}

// String implements the fmt.Stringer.
func (dsr *DirectorySyncRun) String() string {
	var builder strings.Builder
	builder.WriteString("DirectorySyncRun(")
	builder.WriteString(fmt.Sprintf("id=%v, ", dsr.ID))
	builder.WriteString("source_id=")
	builder.WriteString(fmt.Sprintf("%v", dsr.SourceID))
	builder.WriteString(", ")
	builder.WriteString("mode=")
	builder.WriteString(fmt.Sprintf("%v", dsr.Mode))
	builder.WriteString(", ")
	builder.WriteString("trigger=")
	builder.WriteString(fmt.Sprintf("%v", dsr.Trigger))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", dsr.Status))
	builder.WriteString(", ")
	builder.WriteString("phase=")
	builder.WriteString(fmt.Sprintf("%v", dsr.Phase))
	builder.WriteString(", ")
	if v := dsr.StartedAt; v != nil {
		builder.WriteString("started_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := dsr.CompletedAt; v != nil {
		builder.WriteString("completed_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("http_request_count=")
	builder.WriteString(fmt.Sprintf("%v", dsr.HTTPRequestCount))
	builder.WriteString(", ")
	builder.WriteString("department_count=")
	builder.WriteString(fmt.Sprintf("%v", dsr.DepartmentCount))
	builder.WriteString(", ")
	builder.WriteString("member_count=")
	builder.WriteString(fmt.Sprintf("%v", dsr.MemberCount))
	builder.WriteString(", ")
	builder.WriteString("invalid_member_count=")
	builder.WriteString(fmt.Sprintf("%v", dsr.InvalidMemberCount))
	builder.WriteString(", ")
	builder.WriteString("warning_count=")
	builder.WriteString(fmt.Sprintf("%v", dsr.WarningCount))
	builder.WriteString(", ")
	if v := dsr.ErrorMessage; v != nil {
		builder.WriteString("error_message=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("warnings=")
	builder.WriteString(fmt.Sprintf("%v", dsr.Warnings))
	builder.WriteString(", ")
	builder.WriteString("summary=")
	builder.WriteString(fmt.Sprintf("%v", dsr.Summary))
	builder.WriteString(", ")
	builder.WriteString("preview_diff=")
	builder.WriteString(fmt.Sprintf("%v", dsr.PreviewDiff))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(dsr.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(dsr.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// DirectorySyncRuns is a parsable slice of DirectorySyncRun.
type DirectorySyncRuns []*DirectorySyncRun
