// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ai-efficiency/backend/ent/directorydepartment"
	"github.com/ai-efficiency/backend/ent/predicate"
)

// DirectoryDepartmentQuery is the builder for querying DirectoryDepartment entities.
type DirectoryDepartmentQuery struct {
	config
	ctx        *QueryContext
	order      []directorydepartment.OrderOption
	inters     []Interceptor
	predicates []predicate.DirectoryDepartment
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the DirectoryDepartmentQuery builder.
func (ddq *DirectoryDepartmentQuery) Where(ps ...predicate.DirectoryDepartment) *DirectoryDepartmentQuery {
	ddq.predicates = append(ddq.predicates, ps...)
	return ddq
}

// Limit the number of records to be returned by this query.
func (ddq *DirectoryDepartmentQuery) Limit(limit int) *DirectoryDepartmentQuery {
	ddq.ctx.Limit = &limit
	return ddq
}

// Offset to start from.
func (ddq *DirectoryDepartmentQuery) Offset(offset int) *DirectoryDepartmentQuery {
	ddq.ctx.Offset = &offset
	return ddq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (ddq *DirectoryDepartmentQuery) Unique(unique bool) *DirectoryDepartmentQuery {
	ddq.ctx.Unique = &unique
	return ddq
}

// Order specifies how the records should be ordered.
func (ddq *DirectoryDepartmentQuery) Order(o ...directorydepartment.OrderOption) *DirectoryDepartmentQuery {
	ddq.order = append(ddq.order, o...)
	return ddq
}

// First returns the first DirectoryDepartment entity from the query.
// Returns a *NotFoundError when no DirectoryDepartment was found.
func (ddq *DirectoryDepartmentQuery) First(ctx context.Context) (*DirectoryDepartment, error) {
	nodes, err := ddq.Limit(1).All(setContextOp(ctx, ddq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{directorydepartment.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (ddq *DirectoryDepartmentQuery) FirstX(ctx context.Context) *DirectoryDepartment {
	node, err := ddq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first DirectoryDepartment ID from the query.
// Returns a *NotFoundError when no DirectoryDepartment ID was found.
func (ddq *DirectoryDepartmentQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = ddq.Limit(1).IDs(setContextOp(ctx, ddq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{directorydepartment.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (ddq *DirectoryDepartmentQuery) FirstIDX(ctx context.Context) int {
	id, err := ddq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single DirectoryDepartment entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one DirectoryDepartment entity is found.
// Returns a *NotFoundError when no DirectoryDepartment entities are found.
func (ddq *DirectoryDepartmentQuery) Only(ctx context.Context) (*DirectoryDepartment, error) {
	nodes, err := ddq.Limit(2).All(setContextOp(ctx, ddq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{directorydepartment.Label}
	default:
		return nil, &NotSingularError{directorydepartment.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (ddq *DirectoryDepartmentQuery) OnlyX(ctx context.Context) *DirectoryDepartment {
	node, err := ddq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only DirectoryDepartment ID in the query.
// Returns a *NotSingularError when more than one DirectoryDepartment ID is found.
// Returns a *NotFoundError when no entities are found.
func (ddq *DirectoryDepartmentQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = ddq.Limit(2).IDs(setContextOp(ctx, ddq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{directorydepartment.Label}
	default:
		err = &NotSingularError{directorydepartment.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (ddq *DirectoryDepartmentQuery) OnlyIDX(ctx context.Context) int {
	id, err := ddq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of DirectoryDepartments.
func (ddq *DirectoryDepartmentQuery) All(ctx context.Context) ([]*DirectoryDepartment, error) {
	ctx = setContextOp(ctx, ddq.ctx, ent.OpQueryAll)
	if err := ddq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*DirectoryDepartment, *DirectoryDepartmentQuery]()
	return withInterceptors[[]*DirectoryDepartment](ctx, ddq, qr, ddq.inters)
}

// AllX is like All, but panics if an error occurs.
func (ddq *DirectoryDepartmentQuery) AllX(ctx context.Context) []*DirectoryDepartment {
	nodes, err := ddq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of DirectoryDepartment IDs.
func (ddq *DirectoryDepartmentQuery) IDs(ctx context.Context) (ids []int, err error) {
	if ddq.ctx.Unique == nil && ddq.path != nil {
		ddq.Unique(true)
	}
	ctx = setContextOp(ctx, ddq.ctx, ent.OpQueryIDs)
	if err = ddq.Select(directorydepartment.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (ddq *DirectoryDepartmentQuery) IDsX(ctx context.Context) []int {
	ids, err := ddq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (ddq *DirectoryDepartmentQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, ddq.ctx, ent.OpQueryCount)
	if err := ddq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, ddq, querierCount[*DirectoryDepartmentQuery](), ddq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (ddq *DirectoryDepartmentQuery) CountX(ctx context.Context) int {
	count, err := ddq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (ddq *DirectoryDepartmentQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, ddq.ctx, ent.OpQueryExist)
	switch _, err := ddq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (ddq *DirectoryDepartmentQuery) ExistX(ctx context.Context) bool {
	exist, err := ddq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the DirectoryDepartmentQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (ddq *DirectoryDepartmentQuery) Clone() *DirectoryDepartmentQuery {
	if ddq == nil {
		return nil
	}
	return &DirectoryDepartmentQuery{
		config:     ddq.config,
		ctx:        ddq.ctx.Clone(),
		order:      append([]directorydepartment.OrderOption{}, ddq.order...),
		inters:     append([]Interceptor{}, ddq.inters...),
		predicates: append([]predicate.DirectoryDepartment{}, ddq.predicates...),
		// clone intermediate query.
		sql:  ddq.sql.Clone(),
		path: ddq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		SourceID int `json:"source_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.DirectoryDepartment.Query().
//		GroupBy(directorydepartment.FieldSourceID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (ddq *DirectoryDepartmentQuery) GroupBy(field string, fields ...string) *DirectoryDepartmentGroupBy {
	ddq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &DirectoryDepartmentGroupBy{build: ddq}
	grbuild.flds = &ddq.ctx.Fields
	grbuild.label = directorydepartment.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		SourceID int `json:"source_id,omitempty"`
//	}
//
//	client.DirectoryDepartment.Query().
//		Select(directorydepartment.FieldSourceID).
//		Scan(ctx, &v)
func (ddq *DirectoryDepartmentQuery) Select(fields ...string) *DirectoryDepartmentSelect {
	ddq.ctx.Fields = append(ddq.ctx.Fields, fields...)
	sbuild := &DirectoryDepartmentSelect{DirectoryDepartmentQuery: ddq}
	sbuild.label = directorydepartment.Label
	sbuild.flds, sbuild.scan = &ddq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a DirectoryDepartmentSelect configured with the given aggregations.
func (ddq *DirectoryDepartmentQuery) Aggregate(fns ...AggregateFunc) *DirectoryDepartmentSelect {
	return ddq.Select().Aggregate(fns...)
}

func (ddq *DirectoryDepartmentQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range ddq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, ddq); err != nil {
				return err
			}
		}
	}
	for _, f := range ddq.ctx.Fields {
		if !directorydepartment.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if ddq.path != nil {
		prev, err := ddq.path(ctx)
		if err != nil {
			return err
		}
		ddq.sql = prev
	}
	return nil
}

func (ddq *DirectoryDepartmentQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*DirectoryDepartment, error) {
	var (
		nodes = []*DirectoryDepartment{}
		_spec = ddq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*DirectoryDepartment).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &DirectoryDepartment{config: ddq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, ddq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (ddq *DirectoryDepartmentQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := ddq.querySpec()
	_spec.Node.Columns = ddq.ctx.Fields
	if len(ddq.ctx.Fields) > 0 {
		_spec.Unique = ddq.ctx.Unique != nil && *ddq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, ddq.driver, _spec)
}

func (ddq *DirectoryDepartmentQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(directorydepartment.Table, directorydepartment.Columns, sqlgraph.NewFieldSpec(directorydepartment.FieldID, field.TypeInt))
	_spec.From = ddq.sql
	if unique := ddq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if ddq.path != nil {
		_spec.Unique = true
	}
	if fields := ddq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, directorydepartment.FieldID)
		for i := range fields {
			if fields[i] != directorydepartment.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := ddq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := ddq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := ddq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := ddq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (ddq *DirectoryDepartmentQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(ddq.driver.Dialect())
	t1 := builder.Table(directorydepartment.Table)
	columns := ddq.ctx.Fields
	if len(columns) == 0 {
		columns = directorydepartment.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if ddq.sql != nil {
		selector = ddq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if ddq.ctx.Unique != nil && *ddq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range ddq.predicates {
		p(selector)
	}
	for _, p := range ddq.order {
		p(selector)
	}
	if offset := ddq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := ddq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// DirectoryDepartmentGroupBy is the group-by builder for DirectoryDepartment entities.
type DirectoryDepartmentGroupBy struct {
	selector
	build *DirectoryDepartmentQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (ddgb *DirectoryDepartmentGroupBy) Aggregate(fns ...AggregateFunc) *DirectoryDepartmentGroupBy {
	ddgb.fns = append(ddgb.fns, fns...)
	return ddgb
}

// Scan applies the selector query and scans the result into the given value.
func (ddgb *DirectoryDepartmentGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ddgb.build.ctx, ent.OpQueryGroupBy)
	if err := ddgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*DirectoryDepartmentQuery, *DirectoryDepartmentGroupBy](ctx, ddgb.build, ddgb, ddgb.build.inters, v)
}

func (ddgb *DirectoryDepartmentGroupBy) sqlScan(ctx context.Context, root *DirectoryDepartmentQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(ddgb.fns))
	for _, fn := range ddgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*ddgb.flds)+len(ddgb.fns))
		for _, f := range *ddgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*ddgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ddgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// DirectoryDepartmentSelect is the builder for selecting fields of DirectoryDepartment entities.
type DirectoryDepartmentSelect struct {
	*DirectoryDepartmentQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (dds *DirectoryDepartmentSelect) Aggregate(fns ...AggregateFunc) *DirectoryDepartmentSelect {
	dds.fns = append(dds.fns, fns...)
	return dds
}

// Scan applies the selector query and scans the result into the given value.
func (dds *DirectoryDepartmentSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, dds.ctx, ent.OpQuerySelect)
	if err := dds.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*DirectoryDepartmentQuery, *DirectoryDepartmentSelect](ctx, dds.DirectoryDepartmentQuery, dds, dds.inters, v)
}

func (dds *DirectoryDepartmentSelect) sqlScan(ctx context.Context, root *DirectoryDepartmentQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(dds.fns))
	for _, fn := range dds.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*dds.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := dds.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
