// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ai-efficiency/backend/ent/directorydepartment"
	"github.com/ai-efficiency/backend/ent/predicate"
)

// DirectoryDepartmentUpdate is the builder for updating DirectoryDepartment entities.
type DirectoryDepartmentUpdate struct {
	config
	hooks    []Hook
	mutation *DirectoryDepartmentMutation
}

// Where appends a list predicates to the DirectoryDepartmentUpdate builder.
func (ddu *DirectoryDepartmentUpdate) Where(ps ...predicate.DirectoryDepartment) *DirectoryDepartmentUpdate {
	ddu.mutation.Where(ps...)
	return ddu
}

// SetSourceID sets the "source_id" field.
func (ddu *DirectoryDepartmentUpdate) SetSourceID(i int) *DirectoryDepartmentUpdate {
	ddu.mutation.ResetSourceID()
	ddu.mutation.SetSourceID(i)
	return ddu
}

// SetNillableSourceID sets the "source_id" field if the given value is not nil.
func (ddu *DirectoryDepartmentUpdate) SetNillableSourceID(i *int) *DirectoryDepartmentUpdate {
	if i != nil {
		ddu.SetSourceID(*i)
	}
	return ddu
}

// AddSourceID adds i to the "source_id" field.
func (ddu *DirectoryDepartmentUpdate) AddSourceID(i int) *DirectoryDepartmentUpdate {
	ddu.mutation.AddSourceID(i)
	return ddu
}

// SetExternalID sets the "external_id" field.
func (ddu *DirectoryDepartmentUpdate) SetExternalID(s string) *DirectoryDepartmentUpdate {
	ddu.mutation.SetExternalID(s)
	return ddu
}

// SetNillableExternalID sets the "external_id" field if the given value is not nil.
func (ddu *DirectoryDepartmentUpdate) SetNillableExternalID(s *string) *DirectoryDepartmentUpdate {
	if s != nil {
		ddu.SetExternalID(*s)
	}
	return ddu
}

// SetParentExternalID sets the "parent_external_id" field.
func (ddu *DirectoryDepartmentUpdate) SetParentExternalID(s string) *DirectoryDepartmentUpdate {
	ddu.mutation.SetParentExternalID(s)
	return ddu
}

// SetNillableParentExternalID sets the "parent_external_id" field if the given value is not nil.
func (ddu *DirectoryDepartmentUpdate) SetNillableParentExternalID(s *string) *DirectoryDepartmentUpdate {
	if s != nil {
		ddu.SetParentExternalID(*s)
	}
	return ddu
}

// ClearParentExternalID clears the value of the "parent_external_id" field.
func (ddu *DirectoryDepartmentUpdate) ClearParentExternalID() *DirectoryDepartmentUpdate {
	ddu.mutation.ClearParentExternalID()
	return ddu
}

// SetName sets the "name" field.
func (ddu *DirectoryDepartmentUpdate) SetName(s string) *DirectoryDepartmentUpdate {
	ddu.mutation.SetName(s)
	return ddu
}

// SetNillableName sets the "name" field if the given value is not nil.
func (ddu *DirectoryDepartmentUpdate) SetNillableName(s *string) *DirectoryDepartmentUpdate {
	if s != nil {
		ddu.SetName(*s)
	}
	return ddu
}

// SetPath sets the "path" field.
func (ddu *DirectoryDepartmentUpdate) SetPath(s string) *DirectoryDepartmentUpdate {
	ddu.mutation.SetPath(s)
	return ddu
}

// SetNillablePath sets the "path" field if the given value is not nil.
func (ddu *DirectoryDepartmentUpdate) SetNillablePath(s *string) *DirectoryDepartmentUpdate {
	if s != nil {
		ddu.SetPath(*s)
	}
	return ddu
}

// SetMetadata sets the "metadata" field.
func (ddu *DirectoryDepartmentUpdate) SetMetadata(m map[string]interface{}) *DirectoryDepartmentUpdate {
	ddu.mutation.SetMetadata(m)
	return ddu
}

// ClearMetadata clears the value of the "metadata" field.
func (ddu *DirectoryDepartmentUpdate) ClearMetadata() *DirectoryDepartmentUpdate {
	ddu.mutation.ClearMetadata()
	return ddu
}

// SetLastSeenRunID sets the "last_seen_run_id" field.
func (ddu *DirectoryDepartmentUpdate) SetLastSeenRunID(i int) *DirectoryDepartmentUpdate {
	ddu.mutation.ResetLastSeenRunID()
	ddu.mutation.SetLastSeenRunID(i)
	return ddu
}

// SetNillableLastSeenRunID sets the "last_seen_run_id" field if the given value is not nil.
func (ddu *DirectoryDepartmentUpdate) SetNillableLastSeenRunID(i *int) *DirectoryDepartmentUpdate {
	if i != nil {
		ddu.SetLastSeenRunID(*i)
	}
	return ddu
}

// AddLastSeenRunID adds i to the "last_seen_run_id" field.
func (ddu *DirectoryDepartmentUpdate) AddLastSeenRunID(i int) *DirectoryDepartmentUpdate {
	ddu.mutation.AddLastSeenRunID(i)
	return ddu
}

// SetCreatedAt sets the "created_at" field.
func (ddu *DirectoryDepartmentUpdate) SetCreatedAt(t time.Time) *DirectoryDepartmentUpdate {
	ddu.mutation.SetCreatedAt(t)
	return ddu
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (ddu *DirectoryDepartmentUpdate) SetNillableCreatedAt(t *time.Time) *DirectoryDepartmentUpdate {
	if t != nil {
		ddu.SetCreatedAt(*t)
	}
	return ddu
}

// SetUpdatedAt sets the "updated_at" field.
func (ddu *DirectoryDepartmentUpdate) SetUpdatedAt(t time.Time) *DirectoryDepartmentUpdate {
	ddu.mutation.SetUpdatedAt(t)
	return ddu
}

// Mutation returns the DirectoryDepartmentMutation object of the builder.
func (ddu *DirectoryDepartmentUpdate) Mutation() *DirectoryDepartmentMutation {
	return ddu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (ddu *DirectoryDepartmentUpdate) Save(ctx context.Context) (int, error) {
	ddu.defaults()
	return withHooks(ctx, ddu.sqlSave, ddu.mutation, ddu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ddu *DirectoryDepartmentUpdate) SaveX(ctx context.Context) int {
	affected, err := ddu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (ddu *DirectoryDepartmentUpdate) Exec(ctx context.Context) error {
	_, err := ddu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ddu *DirectoryDepartmentUpdate) ExecX(ctx context.Context) {
	if err := ddu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ddu *DirectoryDepartmentUpdate) defaults() {
	if _, ok := ddu.mutation.UpdatedAt(); !ok {
		v := directorydepartment.UpdateDefaultUpdatedAt()
		ddu.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ddu *DirectoryDepartmentUpdate) check() error {
	if v, ok := ddu.mutation.ExternalID(); ok {
		if err := directorydepartment.ExternalIDValidator(v); err != nil {
			return &ValidationError{Name: "external_id", err: fmt.Errorf(`ent: validator failed for field "DirectoryDepartment.external_id": %w`, err)}
		}
	}
	if v, ok := ddu.mutation.Name(); ok {
		if err := directorydepartment.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "DirectoryDepartment.name": %w`, err)}
		}
	}
	return nil
}

func (ddu *DirectoryDepartmentUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := ddu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(directorydepartment.Table, directorydepartment.Columns, sqlgraph.NewFieldSpec(directorydepartment.FieldID, field.TypeInt))
	if ps := ddu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ddu.mutation.SourceID(); ok {
		_spec.SetField(directorydepartment.FieldSourceID, field.TypeInt, value)
	}
	if value, ok := ddu.mutation.AddedSourceID(); ok {
		_spec.AddField(directorydepartment.FieldSourceID, field.TypeInt, value)
	}
	if value, ok := ddu.mutation.ExternalID(); ok {
		_spec.SetField(directorydepartment.FieldExternalID, field.TypeString, value)
	}
	if value, ok := ddu.mutation.ParentExternalID(); ok {
		_spec.SetField(directorydepartment.FieldParentExternalID, field.TypeString, value)
	}
	if ddu.mutation.ParentExternalIDCleared() {
		_spec.ClearField(directorydepartment.FieldParentExternalID, field.TypeString)
	}
	if value, ok := ddu.mutation.Name(); ok {
		_spec.SetField(directorydepartment.FieldName, field.TypeString, value)
	}
	if value, ok := ddu.mutation.Path(); ok {
		_spec.SetField(directorydepartment.FieldPath, field.TypeString, value)
	}
	if value, ok := ddu.mutation.Metadata(); ok {
		_spec.SetField(directorydepartment.FieldMetadata, field.TypeJSON, value)
	}
	if ddu.mutation.MetadataCleared() {
		_spec.ClearField(directorydepartment.FieldMetadata, field.TypeJSON)
	}
	if value, ok := ddu.mutation.LastSeenRunID(); ok {
		_spec.SetField(directorydepartment.FieldLastSeenRunID, field.TypeInt, value)
	}
	if value, ok := ddu.mutation.AddedLastSeenRunID(); ok {
		_spec.AddField(directorydepartment.FieldLastSeenRunID, field.TypeInt, value)
	}
	if value, ok := ddu.mutation.CreatedAt(); ok {
		_spec.SetField(directorydepartment.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := ddu.mutation.UpdatedAt(); ok {
		_spec.SetField(directorydepartment.FieldUpdatedAt, field.TypeTime, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, ddu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{directorydepartment.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	ddu.mutation.done = true
	return n, nil
}

// DirectoryDepartmentUpdateOne is the builder for updating a single DirectoryDepartment entity.
type DirectoryDepartmentUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *DirectoryDepartmentMutation
}

// SetSourceID sets the "source_id" field.
func (dduo *DirectoryDepartmentUpdateOne) SetSourceID(i int) *DirectoryDepartmentUpdateOne {
	dduo.mutation.ResetSourceID()
	dduo.mutation.SetSourceID(i)
	return dduo
}

// SetNillableSourceID sets the "source_id" field if the given value is not nil.
func (dduo *DirectoryDepartmentUpdateOne) SetNillableSourceID(i *int) *DirectoryDepartmentUpdateOne {
	if i != nil {
		dduo.SetSourceID(*i)
	}
	return dduo
}

// AddSourceID adds i to the "source_id" field.
func (dduo *DirectoryDepartmentUpdateOne) AddSourceID(i int) *DirectoryDepartmentUpdateOne {
	dduo.mutation.AddSourceID(i)
	return dduo
}

// SetExternalID sets the "external_id" field.
func (dduo *DirectoryDepartmentUpdateOne) SetExternalID(s string) *DirectoryDepartmentUpdateOne {
	dduo.mutation.SetExternalID(s)
	return dduo
}

// SetNillableExternalID sets the "external_id" field if the given value is not nil.
func (dduo *DirectoryDepartmentUpdateOne) SetNillableExternalID(s *string) *DirectoryDepartmentUpdateOne {
	if s != nil {
		dduo.SetExternalID(*s)
	}
	return dduo
}

// SetParentExternalID sets the "parent_external_id" field.
func (dduo *DirectoryDepartmentUpdateOne) SetParentExternalID(s string) *DirectoryDepartmentUpdateOne {
	dduo.mutation.SetParentExternalID(s)
	return dduo
}

// SetNillableParentExternalID sets the "parent_external_id" field if the given value is not nil.
func (dduo *DirectoryDepartmentUpdateOne) SetNillableParentExternalID(s *string) *DirectoryDepartmentUpdateOne {
	if s != nil {
		dduo.SetParentExternalID(*s)
	}
	return dduo
}

// ClearParentExternalID clears the value of the "parent_external_id" field.
func (dduo *DirectoryDepartmentUpdateOne) ClearParentExternalID() *DirectoryDepartmentUpdateOne {
	dduo.mutation.ClearParentExternalID()
	return dduo
}

// SetName sets the "name" field.
func (dduo *DirectoryDepartmentUpdateOne) SetName(s string) *DirectoryDepartmentUpdateOne {
	dduo.mutation.SetName(s)
	return dduo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (dduo *DirectoryDepartmentUpdateOne) SetNillableName(s *string) *DirectoryDepartmentUpdateOne {
	if s != nil {
		dduo.SetName(*s)
	}
	return dduo
}

// SetPath sets the "path" field.
func (dduo *DirectoryDepartmentUpdateOne) SetPath(s string) *DirectoryDepartmentUpdateOne {
	dduo.mutation.SetPath(s)
	return dduo
}

// SetNillablePath sets the "path" field if the given value is not nil.
func (dduo *DirectoryDepartmentUpdateOne) SetNillablePath(s *string) *DirectoryDepartmentUpdateOne {
	if s != nil {
		dduo.SetPath(*s)
	}
	return dduo
}

// SetMetadata sets the "metadata" field.
func (dduo *DirectoryDepartmentUpdateOne) SetMetadata(m map[string]interface{}) *DirectoryDepartmentUpdateOne {
	dduo.mutation.SetMetadata(m)
	return dduo
}

// ClearMetadata clears the value of the "metadata" field.
func (dduo *DirectoryDepartmentUpdateOne) ClearMetadata() *DirectoryDepartmentUpdateOne {
	dduo.mutation.ClearMetadata()
	return dduo
}

// SetLastSeenRunID sets the "last_seen_run_id" field.
func (dduo *DirectoryDepartmentUpdateOne) SetLastSeenRunID(i int) *DirectoryDepartmentUpdateOne {
	dduo.mutation.ResetLastSeenRunID()
	dduo.mutation.SetLastSeenRunID(i)
	return dduo
}

// SetNillableLastSeenRunID sets the "last_seen_run_id" field if the given value is not nil.
func (dduo *DirectoryDepartmentUpdateOne) SetNillableLastSeenRunID(i *int) *DirectoryDepartmentUpdateOne {
	if i != nil {
		dduo.SetLastSeenRunID(*i)
	}
	return dduo
}

// AddLastSeenRunID adds i to the "last_seen_run_id" field.
func (dduo *DirectoryDepartmentUpdateOne) AddLastSeenRunID(i int) *DirectoryDepartmentUpdateOne {
	dduo.mutation.AddLastSeenRunID(i)
	return dduo
}

// SetCreatedAt sets the "created_at" field.
func (dduo *DirectoryDepartmentUpdateOne) SetCreatedAt(t time.Time) *DirectoryDepartmentUpdateOne {
	dduo.mutation.SetCreatedAt(t)
	return dduo
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (dduo *DirectoryDepartmentUpdateOne) SetNillableCreatedAt(t *time.Time) *DirectoryDepartmentUpdateOne {
	if t != nil {
		dduo.SetCreatedAt(*t)
	}
	return dduo
}

// SetUpdatedAt sets the "updated_at" field.
func (dduo *DirectoryDepartmentUpdateOne) SetUpdatedAt(t time.Time) *DirectoryDepartmentUpdateOne {
	dduo.mutation.SetUpdatedAt(t)
	return dduo
}

// Mutation returns the DirectoryDepartmentMutation object of the builder.
func (dduo *DirectoryDepartmentUpdateOne) Mutation() *DirectoryDepartmentMutation {
	return dduo.mutation
}

// Where appends a list predicates to the DirectoryDepartmentUpdate builder.
func (dduo *DirectoryDepartmentUpdateOne) Where(ps ...predicate.DirectoryDepartment) *DirectoryDepartmentUpdateOne {
	dduo.mutation.Where(ps...)
	return dduo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (dduo *DirectoryDepartmentUpdateOne) Select(field string, fields ...string) *DirectoryDepartmentUpdateOne {
	dduo.fields = append([]string{field}, fields...)
	return dduo
}

// Save executes the query and returns the updated DirectoryDepartment entity.
func (dduo *DirectoryDepartmentUpdateOne) Save(ctx context.Context) (*DirectoryDepartment, error) {
	dduo.defaults()
	return withHooks(ctx, dduo.sqlSave, dduo.mutation, dduo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (dduo *DirectoryDepartmentUpdateOne) SaveX(ctx context.Context) *DirectoryDepartment {
	node, err := dduo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (dduo *DirectoryDepartmentUpdateOne) Exec(ctx context.Context) error {
	_, err := dduo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (dduo *DirectoryDepartmentUpdateOne) ExecX(ctx context.Context) {
	if err := dduo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (dduo *DirectoryDepartmentUpdateOne) defaults() {
	if _, ok := dduo.mutation.UpdatedAt(); !ok {
		v := directorydepartment.UpdateDefaultUpdatedAt()
		dduo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (dduo *DirectoryDepartmentUpdateOne) check() error {
	if v, ok := dduo.mutation.ExternalID(); ok {
		if err := directorydepartment.ExternalIDValidator(v); err != nil {
			return &ValidationError{Name: "external_id", err: fmt.Errorf(`ent: validator failed for field "DirectoryDepartment.external_id": %w`, err)}
		}
	}
	if v, ok := dduo.mutation.Name(); ok {
		if err := directorydepartment.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "DirectoryDepartment.name": %w`, err)}
		}
	}
	return nil
}

func (dduo *DirectoryDepartmentUpdateOne) sqlSave(ctx context.Context) (_node *DirectoryDepartment, err error) {
	if err := dduo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(directorydepartment.Table, directorydepartment.Columns, sqlgraph.NewFieldSpec(directorydepartment.FieldID, field.TypeInt))
	id, ok := dduo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "DirectoryDepartment.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := dduo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, directorydepartment.FieldID)
		for _, f := range fields {
			if !directorydepartment.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != directorydepartment.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := dduo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := dduo.mutation.SourceID(); ok {
		_spec.SetField(directorydepartment.FieldSourceID, field.TypeInt, value)
	}
	if value, ok := dduo.mutation.AddedSourceID(); ok {
		_spec.AddField(directorydepartment.FieldSourceID, field.TypeInt, value)
	}
	if value, ok := dduo.mutation.ExternalID(); ok {
		_spec.SetField(directorydepartment.FieldExternalID, field.TypeString, value)
	}
	if value, ok := dduo.mutation.ParentExternalID(); ok {
		_spec.SetField(directorydepartment.FieldParentExternalID, field.TypeString, value)
	}
	if dduo.mutation.ParentExternalIDCleared() {
		_spec.ClearField(directorydepartment.FieldParentExternalID, field.TypeString)
	}
	if value, ok := dduo.mutation.Name(); ok {
		_spec.SetField(directorydepartment.FieldName, field.TypeString, value)
	}
	if value, ok := dduo.mutation.Path(); ok {
		_spec.SetField(directorydepartment.FieldPath, field.TypeString, value)
	}
	if value, ok := dduo.mutation.Metadata(); ok {
		_spec.SetField(directorydepartment.FieldMetadata, field.TypeJSON, value)
	}
	if dduo.mutation.MetadataCleared() {
		_spec.ClearField(directorydepartment.FieldMetadata, field.TypeJSON)
	}
	if value, ok := dduo.mutation.LastSeenRunID(); ok {
		_spec.SetField(directorydepartment.FieldLastSeenRunID, field.TypeInt, value)
	}
	if value, ok := dduo.mutation.AddedLastSeenRunID(); ok {
		_spec.AddField(directorydepartment.FieldLastSeenRunID, field.TypeInt, value)
	}
	if value, ok := dduo.mutation.CreatedAt(); ok {
		_spec.SetField(directorydepartment.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := dduo.mutation.UpdatedAt(); ok {
		_spec.SetField(directorydepartment.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &DirectoryDepartment{config: dduo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, dduo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{directorydepartment.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	dduo.mutation.done = true
	return _node, nil
}
