// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ai-efficiency/backend/ent/directorymemberdepartment"
)

// DirectoryMemberDepartmentCreate is the builder for creating a DirectoryMemberDepartment entity.
type DirectoryMemberDepartmentCreate struct {
	config
	mutation *DirectoryMemberDepartmentMutation
	hooks    []Hook
}

// SetSourceID sets the "source_id" field.
func (dmdc *DirectoryMemberDepartmentCreate) SetSourceID(i int) *DirectoryMemberDepartmentCreate {
	dmdc.mutation.SetSourceID(i)
	return dmdc
}

// SetDirectoryMemberID sets the "directory_member_id" field.
func (dmdc *DirectoryMemberDepartmentCreate) SetDirectoryMemberID(i int) *DirectoryMemberDepartmentCreate {
	dmdc.mutation.SetDirectoryMemberID(i)
	return dmdc
}

// SetMemberExternalID sets the "member_external_id" field.
func (dmdc *DirectoryMemberDepartmentCreate) SetMemberExternalID(s string) *DirectoryMemberDepartmentCreate {
	dmdc.mutation.SetMemberExternalID(s)
	return dmdc
}

// SetNillableMemberExternalID sets the "member_external_id" field if the given value is not nil.
func (dmdc *DirectoryMemberDepartmentCreate) SetNillableMemberExternalID(s *string) *DirectoryMemberDepartmentCreate {
	if s != nil {
		dmdc.SetMemberExternalID(*s)
	}
	return dmdc
}

// SetMemberEmailNormalized sets the "member_email_normalized" field.
func (dmdc *DirectoryMemberDepartmentCreate) SetMemberEmailNormalized(s string) *DirectoryMemberDepartmentCreate {
	dmdc.mutation.SetMemberEmailNormalized(s)
	return dmdc
}

// SetDepartmentExternalID sets the "department_external_id" field.
func (dmdc *DirectoryMemberDepartmentCreate) SetDepartmentExternalID(s string) *DirectoryMemberDepartmentCreate {
	dmdc.mutation.SetDepartmentExternalID(s)
	return dmdc
}

// SetLastSeenRunID sets the "last_seen_run_id" field.
func (dmdc *DirectoryMemberDepartmentCreate) SetLastSeenRunID(i int) *DirectoryMemberDepartmentCreate {
	dmdc.mutation.SetLastSeenRunID(i)
	return dmdc
}

// SetCreatedAt sets the "created_at" field.
func (dmdc *DirectoryMemberDepartmentCreate) SetCreatedAt(t time.Time) *DirectoryMemberDepartmentCreate {
	dmdc.mutation.SetCreatedAt(t)
	return dmdc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (dmdc *DirectoryMemberDepartmentCreate) SetNillableCreatedAt(t *time.Time) *DirectoryMemberDepartmentCreate {
	if t != nil {
		dmdc.SetCreatedAt(*t)
	}
	return dmdc
}

// SetUpdatedAt sets the "updated_at" field.
func (dmdc *DirectoryMemberDepartmentCreate) SetUpdatedAt(t time.Time) *DirectoryMemberDepartmentCreate {
	dmdc.mutation.SetUpdatedAt(t)
	return dmdc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (dmdc *DirectoryMemberDepartmentCreate) SetNillableUpdatedAt(t *time.Time) *DirectoryMemberDepartmentCreate {
	if t != nil {
		dmdc.SetUpdatedAt(*t)
	}
	return dmdc
}

// Mutation returns the DirectoryMemberDepartmentMutation object of the builder.
func (dmdc *DirectoryMemberDepartmentCreate) Mutation() *DirectoryMemberDepartmentMutation {
	return dmdc.mutation
}

// Save creates the DirectoryMemberDepartment in the database.
func (dmdc *DirectoryMemberDepartmentCreate) Save(ctx context.Context) (*DirectoryMemberDepartment, error) {
	dmdc.defaults()
	return withHooks(ctx, dmdc.sqlSave, dmdc.mutation, dmdc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (dmdc *DirectoryMemberDepartmentCreate) SaveX(ctx context.Context) *DirectoryMemberDepartment {
	v, err := dmdc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (dmdc *DirectoryMemberDepartmentCreate) Exec(ctx context.Context) error {
	_, err := dmdc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (dmdc *DirectoryMemberDepartmentCreate) ExecX(ctx context.Context) {
	if err := dmdc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (dmdc *DirectoryMemberDepartmentCreate) defaults() {
	if _, ok := dmdc.mutation.MemberExternalID(); !ok {
		v := directorymemberdepartment.DefaultMemberExternalID
		dmdc.mutation.SetMemberExternalID(v)
	}
	if _, ok := dmdc.mutation.CreatedAt(); !ok {
		v := directorymemberdepartment.DefaultCreatedAt()
		dmdc.mutation.SetCreatedAt(v)
	}
	if _, ok := dmdc.mutation.UpdatedAt(); !ok {
		v := directorymemberdepartment.DefaultUpdatedAt()
		dmdc.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (dmdc *DirectoryMemberDepartmentCreate) check() error {
	if _, ok := dmdc.mutation.SourceID(); !ok {
		return &ValidationError{Name: "source_id", err: errors.New(`ent: missing required field "DirectoryMemberDepartment.source_id"`)}
	}
	if _, ok := dmdc.mutation.DirectoryMemberID(); !ok {
		return &ValidationError{Name: "directory_member_id", err: errors.New(`ent: missing required field "DirectoryMemberDepartment.directory_member_id"`)}
	}
	if _, ok := dmdc.mutation.MemberExternalID(); !ok {
		return &ValidationError{Name: "member_external_id", err: errors.New(`ent: missing required field "DirectoryMemberDepartment.member_external_id"`)}
	}
	if _, ok := dmdc.mutation.MemberEmailNormalized(); !ok {
		return &ValidationError{Name: "member_email_normalized", err: errors.New(`ent: missing required field "DirectoryMemberDepartment.member_email_normalized"`)}
	}
	if v, ok := dmdc.mutation.MemberEmailNormalized(); ok {
		if err := directorymemberdepartment.MemberEmailNormalizedValidator(v); err != nil {
			return &ValidationError{Name: "member_email_normalized", err: fmt.Errorf(`ent: validator failed for field "DirectoryMemberDepartment.member_email_normalized": %w`, err)}
		}
	}
	if _, ok := dmdc.mutation.DepartmentExternalID(); !ok {
		return &ValidationError{Name: "department_external_id", err: errors.New(`ent: missing required field "DirectoryMemberDepartment.department_external_id"`)}
	}
	if v, ok := dmdc.mutation.DepartmentExternalID(); ok {
		if err := directorymemberdepartment.DepartmentExternalIDValidator(v); err != nil {
			return &ValidationError{Name: "department_external_id", err: fmt.Errorf(`ent: validator failed for field "DirectoryMemberDepartment.department_external_id": %w`, err)}
		}
	}
	if _, ok := dmdc.mutation.LastSeenRunID(); !ok {
		return &ValidationError{Name: "last_seen_run_id", err: errors.New(`ent: missing required field "DirectoryMemberDepartment.last_seen_run_id"`)}
	}
	if _, ok := dmdc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "DirectoryMemberDepartment.created_at"`)}
	}
	if _, ok := dmdc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "DirectoryMemberDepartment.updated_at"`)}
	}
	return nil
}

func (dmdc *DirectoryMemberDepartmentCreate) sqlSave(ctx context.Context) (*DirectoryMemberDepartment, error) {
	if err := dmdc.check(); err != nil {
		return nil, err
	}
	_node, _spec := dmdc.createSpec()
	if err := sqlgraph.CreateNode(ctx, dmdc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	dmdc.mutation.id = &_node.ID
	dmdc.mutation.done = true
	return _node, nil
}

func (dmdc *DirectoryMemberDepartmentCreate) createSpec() (*DirectoryMemberDepartment, *sqlgraph.CreateSpec) {
	var (
		_node = &DirectoryMemberDepartment{config: dmdc.config}
		_spec = sqlgraph.NewCreateSpec(directorymemberdepartment.Table, sqlgraph.NewFieldSpec(directorymemberdepartment.FieldID, field.TypeInt))
	)
	if value, ok := dmdc.mutation.SourceID(); ok {
		_spec.SetField(directorymemberdepartment.FieldSourceID, field.TypeInt, value)
		_node.SourceID = value
	}
	if value, ok := dmdc.mutation.DirectoryMemberID(); ok {
		_spec.SetField(directorymemberdepartment.FieldDirectoryMemberID, field.TypeInt, value)
		_node.DirectoryMemberID = value
	}
	if value, ok := dmdc.mutation.MemberExternalID(); ok {
		_spec.SetField(directorymemberdepartment.FieldMemberExternalID, field.TypeString, value)
		_node.MemberExternalID = value
	}
	if value, ok := dmdc.mutation.MemberEmailNormalized(); ok {
		_spec.SetField(directorymemberdepartment.FieldMemberEmailNormalized, field.TypeString, value)
		_node.MemberEmailNormalized = value
	}
	if value, ok := dmdc.mutation.DepartmentExternalID(); ok {
		_spec.SetField(directorymemberdepartment.FieldDepartmentExternalID, field.TypeString, value)
		_node.DepartmentExternalID = value
	}
	if value, ok := dmdc.mutation.LastSeenRunID(); ok {
		_spec.SetField(directorymemberdepartment.FieldLastSeenRunID, field.TypeInt, value)
		_node.LastSeenRunID = value
	}
	if value, ok := dmdc.mutation.CreatedAt(); ok {
		_spec.SetField(directorymemberdepartment.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := dmdc.mutation.UpdatedAt(); ok {
		_spec.SetField(directorymemberdepartment.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// DirectoryMemberDepartmentCreateBulk is the builder for creating many DirectoryMemberDepartment entities in bulk.
type DirectoryMemberDepartmentCreateBulk struct {
	config
	err      error
	builders []*DirectoryMemberDepartmentCreate
}

// Save creates the DirectoryMemberDepartment entities in the database.
func (dmdcb *DirectoryMemberDepartmentCreateBulk) Save(ctx context.Context) ([]*DirectoryMemberDepartment, error) {
	if dmdcb.err != nil {
		return nil, dmdcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(dmdcb.builders))
	nodes := make([]*DirectoryMemberDepartment, len(dmdcb.builders))
	mutators := make([]Mutator, len(dmdcb.builders))
	for i := range dmdcb.builders {
		func(i int, root context.Context) {
			builder := dmdcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DirectoryMemberDepartmentMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, dmdcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, dmdcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, dmdcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (dmdcb *DirectoryMemberDepartmentCreateBulk) SaveX(ctx context.Context) []*DirectoryMemberDepartment {
	v, err := dmdcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (dmdcb *DirectoryMemberDepartmentCreateBulk) Exec(ctx context.Context) error {
	_, err := dmdcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (dmdcb *DirectoryMemberDepartmentCreateBulk) ExecX(ctx context.Context) {
	if err := dmdcb.Exec(ctx); err != nil {
		panic(err)
	}
}
