// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ai-efficiency/backend/ent/efficiencymetric"
	"github.com/ai-efficiency/backend/ent/predicate"
)

// EfficiencyMetricDelete is the builder for deleting a EfficiencyMetric entity.
type EfficiencyMetricDelete struct {
	config
	hooks    []Hook
	mutation *EfficiencyMetricMutation
}

// Where appends a list predicates to the EfficiencyMetricDelete builder.
func (emd *EfficiencyMetricDelete) Where(ps ...predicate.EfficiencyMetric) *EfficiencyMetricDelete {
	emd.mutation.Where(ps...)
	return emd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (emd *EfficiencyMetricDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, emd.sqlExec, emd.mutation, emd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (emd *EfficiencyMetricDelete) ExecX(ctx context.Context) int {
	n, err := emd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (emd *EfficiencyMetricDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(efficiencymetric.Table, sqlgraph.NewFieldSpec(efficiencymetric.FieldID, field.TypeInt))
	if ps := emd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, emd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	emd.mutation.done = true
	return affected, err
}

// EfficiencyMetricDeleteOne is the builder for deleting a single EfficiencyMetric entity.
type EfficiencyMetricDeleteOne struct {
	emd *EfficiencyMetricDelete
}

// Where appends a list predicates to the EfficiencyMetricDelete builder.
func (emdo *EfficiencyMetricDeleteOne) Where(ps ...predicate.EfficiencyMetric) *EfficiencyMetricDeleteOne {
	emdo.emd.mutation.Where(ps...)
	return emdo
}

// Exec executes the deletion query.
func (emdo *EfficiencyMetricDeleteOne) Exec(ctx context.Context) error {
	n, err := emdo.emd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{efficiencymetric.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (emdo *EfficiencyMetricDeleteOne) ExecX(ctx context.Context) {
	if err := emdo.Exec(ctx); err != nil {
		panic(err)
	}
}
