// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ai-efficiency/backend/ent/prattributionrun"
	"github.com/ai-efficiency/backend/ent/predicate"
)

// PrAttributionRunDelete is the builder for deleting a PrAttributionRun entity.
type PrAttributionRunDelete struct {
	config
	hooks    []Hook
	mutation *PrAttributionRunMutation
}

// Where appends a list predicates to the PrAttributionRunDelete builder.
func (pard *PrAttributionRunDelete) Where(ps ...predicate.PrAttributionRun) *PrAttributionRunDelete {
	pard.mutation.Where(ps...)
	return pard
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (pard *PrAttributionRunDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, pard.sqlExec, pard.mutation, pard.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (pard *PrAttributionRunDelete) ExecX(ctx context.Context) int {
	n, err := pard.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (pard *PrAttributionRunDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(prattributionrun.Table, sqlgraph.NewFieldSpec(prattributionrun.FieldID, field.TypeInt))
	if ps := pard.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, pard.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	pard.mutation.done = true
	return affected, err
}

// PrAttributionRunDeleteOne is the builder for deleting a single PrAttributionRun entity.
type PrAttributionRunDeleteOne struct {
	pard *PrAttributionRunDelete
}

// Where appends a list predicates to the PrAttributionRunDelete builder.
func (pardo *PrAttributionRunDeleteOne) Where(ps ...predicate.PrAttributionRun) *PrAttributionRunDeleteOne {
	pardo.pard.mutation.Where(ps...)
	return pardo
}

// Exec executes the deletion query.
func (pardo *PrAttributionRunDeleteOne) Exec(ctx context.Context) error {
	n, err := pardo.pard.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{prattributionrun.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (pardo *PrAttributionRunDeleteOne) ExecX(ctx context.Context) {
	if err := pardo.Exec(ctx); err != nil {
		panic(err)
	}
}
