// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/ai-efficiency/backend/ent/prattributionrun"
	"github.com/ai-efficiency/backend/ent/prrecord"
)

// PrAttributionRun is the model entity for the PrAttributionRun schema.
type PrAttributionRun struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// PrRecordID holds the value of the "pr_record_id" field.
	PrRecordID int `json:"pr_record_id,omitempty"`
	// TriggerMode holds the value of the "trigger_mode" field.
	TriggerMode prattributionrun.TriggerMode `json:"trigger_mode,omitempty"`
	// TriggeredBy holds the value of the "triggered_by" field.
	TriggeredBy string `json:"triggered_by,omitempty"`
	// Status holds the value of the "status" field.
	Status prattributionrun.Status `json:"status,omitempty"`
	// ResultClassification holds the value of the "result_classification" field.
	ResultClassification *prattributionrun.ResultClassification `json:"result_classification,omitempty"`
	// MatchedCommitShas holds the value of the "matched_commit_shas" field.
	MatchedCommitShas []string `json:"matched_commit_shas,omitempty"`
	// MatchedSessionIds holds the value of the "matched_session_ids" field.
	MatchedSessionIds []string `json:"matched_session_ids,omitempty"`
	// PrimaryUsageSummary holds the value of the "primary_usage_summary" field.
	PrimaryUsageSummary map[string]interface{} `json:"primary_usage_summary,omitempty"`
	// MetadataSummary holds the value of the "metadata_summary" field.
	MetadataSummary map[string]interface{} `json:"metadata_summary,omitempty"`
	// ValidationSummary holds the value of the "validation_summary" field.
	ValidationSummary map[string]interface{} `json:"validation_summary,omitempty"`
	// ErrorMessage holds the value of the "error_message" field.
	ErrorMessage *string `json:"error_message,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the PrAttributionRunQuery when eager-loading is set.
	Edges        PrAttributionRunEdges `json:"edges"`
	selectValues sql.SelectValues
}

// PrAttributionRunEdges holds the relations/edges for other nodes in the graph.
type PrAttributionRunEdges struct {
	// PrRecord holds the value of the pr_record edge.
	PrRecord *PrRecord `json:"pr_record,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// PrRecordOrErr returns the PrRecord value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PrAttributionRunEdges) PrRecordOrErr() (*PrRecord, error) {
	if e.PrRecord != nil {
		return e.PrRecord, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: prrecord.Label}
	}
	return nil, &NotLoadedError{edge: "pr_record"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*PrAttributionRun) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case prattributionrun.FieldMatchedCommitShas, prattributionrun.FieldMatchedSessionIds, prattributionrun.FieldPrimaryUsageSummary, prattributionrun.FieldMetadataSummary, prattributionrun.FieldValidationSummary:
			values[i] = new([]byte)
		case prattributionrun.FieldID, prattributionrun.FieldPrRecordID:
			values[i] = new(sql.NullInt64)
		case prattributionrun.FieldTriggerMode, prattributionrun.FieldTriggeredBy, prattributionrun.FieldStatus, prattributionrun.FieldResultClassification, prattributionrun.FieldErrorMessage:
			values[i] = new(sql.NullString)
		case prattributionrun.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the PrAttributionRun fields.
func (par *PrAttributionRun) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case prattributionrun.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			par.ID = int(value.Int64)
		case prattributionrun.FieldPrRecordID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field pr_record_id", values[i])
			} else if value.Valid {
				par.PrRecordID = int(value.Int64)
			}
		case prattributionrun.FieldTriggerMode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field trigger_mode", values[i])
			} else if value.Valid {
				par.TriggerMode = prattributionrun.TriggerMode(value.String)
			}
		case prattributionrun.FieldTriggeredBy:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field triggered_by", values[i])
			} else if value.Valid {
				par.TriggeredBy = value.String
			}
		case prattributionrun.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				par.Status = prattributionrun.Status(value.String)
			}
		case prattributionrun.FieldResultClassification:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field result_classification", values[i])
			} else if value.Valid {
				par.ResultClassification = new(prattributionrun.ResultClassification)
				*par.ResultClassification = prattributionrun.ResultClassification(value.String)
			}
		case prattributionrun.FieldMatchedCommitShas:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field matched_commit_shas", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &par.MatchedCommitShas); err != nil {
					return fmt.Errorf("unmarshal field matched_commit_shas: %w", err)
				}
			}
		case prattributionrun.FieldMatchedSessionIds:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field matched_session_ids", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &par.MatchedSessionIds); err != nil {
					return fmt.Errorf("unmarshal field matched_session_ids: %w", err)
				}
			}
		case prattributionrun.FieldPrimaryUsageSummary:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field primary_usage_summary", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &par.PrimaryUsageSummary); err != nil {
					return fmt.Errorf("unmarshal field primary_usage_summary: %w", err)
				}
			}
		case prattributionrun.FieldMetadataSummary:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field metadata_summary", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &par.MetadataSummary); err != nil {
					return fmt.Errorf("unmarshal field metadata_summary: %w", err)
				}
			}
		case prattributionrun.FieldValidationSummary:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field validation_summary", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &par.ValidationSummary); err != nil {
					return fmt.Errorf("unmarshal field validation_summary: %w", err)
				}
			}
		case prattributionrun.FieldErrorMessage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error_message", values[i])
			} else if value.Valid {
				par.ErrorMessage = new(string)
				*par.ErrorMessage = value.String
			}
		case prattributionrun.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				par.CreatedAt = value.Time
			}
		default:
			par.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the PrAttributionRun.
// This includes values selected through modifiers, order, etc.
func (par *PrAttributionRun) Value(name string) (ent.Value, error) {
	return par.selectValues.Get(name)
}

// QueryPrRecord queries the "pr_record" edge of the PrAttributionRun entity.
func (par *PrAttributionRun) QueryPrRecord() *PrRecordQuery {
	return NewPrAttributionRunClient(par.config).QueryPrRecord(par)
}

// Update returns a builder for updating this PrAttributionRun.
// Note that you need to call PrAttributionRun.Unwrap() before calling this method if this PrAttributionRun
// was returned from a transaction, and the transaction was committed or rolled back.
func (par *PrAttributionRun) Update() *PrAttributionRunUpdateOne {
	return NewPrAttributionRunClient(par.config).UpdateOne(par)
}

// Unwrap unwraps the PrAttributionRun entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (par *PrAttributionRun) Unwrap() *PrAttributionRun {
	_tx, ok := par.config.driver.(*txDriver)
	if !ok {
		panic("ent: PrAttributionRun is not a transactional entity")
	}
	par.config.driver = _tx.drv
	return par
}

// String implements the fmt.Stringer.
func (par *PrAttributionRun) String() string {
	var builder strings.Builder
	builder.WriteString("PrAttributionRun(")
	builder.WriteString(fmt.Sprintf("id=%v, ", par.ID))
	builder.WriteString("pr_record_id=")
	builder.WriteString(fmt.Sprintf("%v", par.PrRecordID))
	builder.WriteString(", ")
	builder.WriteString("trigger_mode=")
	builder.WriteString(fmt.Sprintf("%v", par.TriggerMode))
	builder.WriteString(", ")
	builder.WriteString("triggered_by=")
	builder.WriteString(par.TriggeredBy)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", par.Status))
	builder.WriteString(", ")
	if v := par.ResultClassification; v != nil {
		builder.WriteString("result_classification=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("matched_commit_shas=")
	builder.WriteString(fmt.Sprintf("%v", par.MatchedCommitShas))
	builder.WriteString(", ")
	builder.WriteString("matched_session_ids=")
	builder.WriteString(fmt.Sprintf("%v", par.MatchedSessionIds))
	builder.WriteString(", ")
	builder.WriteString("primary_usage_summary=")
	builder.WriteString(fmt.Sprintf("%v", par.PrimaryUsageSummary))
	builder.WriteString(", ")
	builder.WriteString("metadata_summary=")
	builder.WriteString(fmt.Sprintf("%v", par.MetadataSummary))
	builder.WriteString(", ")
	builder.WriteString("validation_summary=")
	builder.WriteString(fmt.Sprintf("%v", par.ValidationSummary))
	builder.WriteString(", ")
	if v := par.ErrorMessage; v != nil {
		builder.WriteString("error_message=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(par.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// PrAttributionRuns is a parsable slice of PrAttributionRun.
type PrAttributionRuns []*PrAttributionRun
