// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ai-efficiency/backend/ent/commitcheckpoint"
	"github.com/ai-efficiency/backend/ent/prcommitusagesnapshot"
	"github.com/ai-efficiency/backend/ent/predicate"
	"github.com/ai-efficiency/backend/ent/prrecord"
)

// PRCommitUsageSnapshotQuery is the builder for querying PRCommitUsageSnapshot entities.
type PRCommitUsageSnapshotQuery struct {
	config
	ctx                  *QueryContext
	order                []prcommitusagesnapshot.OrderOption
	inters               []Interceptor
	predicates           []predicate.PRCommitUsageSnapshot
	withPrRecord         *PrRecordQuery
	withCommitCheckpoint *CommitCheckpointQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the PRCommitUsageSnapshotQuery builder.
func (pcusq *PRCommitUsageSnapshotQuery) Where(ps ...predicate.PRCommitUsageSnapshot) *PRCommitUsageSnapshotQuery {
	pcusq.predicates = append(pcusq.predicates, ps...)
	return pcusq
}

// Limit the number of records to be returned by this query.
func (pcusq *PRCommitUsageSnapshotQuery) Limit(limit int) *PRCommitUsageSnapshotQuery {
	pcusq.ctx.Limit = &limit
	return pcusq
}

// Offset to start from.
func (pcusq *PRCommitUsageSnapshotQuery) Offset(offset int) *PRCommitUsageSnapshotQuery {
	pcusq.ctx.Offset = &offset
	return pcusq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (pcusq *PRCommitUsageSnapshotQuery) Unique(unique bool) *PRCommitUsageSnapshotQuery {
	pcusq.ctx.Unique = &unique
	return pcusq
}

// Order specifies how the records should be ordered.
func (pcusq *PRCommitUsageSnapshotQuery) Order(o ...prcommitusagesnapshot.OrderOption) *PRCommitUsageSnapshotQuery {
	pcusq.order = append(pcusq.order, o...)
	return pcusq
}

// QueryPrRecord chains the current query on the "pr_record" edge.
func (pcusq *PRCommitUsageSnapshotQuery) QueryPrRecord() *PrRecordQuery {
	query := (&PrRecordClient{config: pcusq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := pcusq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := pcusq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(prcommitusagesnapshot.Table, prcommitusagesnapshot.FieldID, selector),
			sqlgraph.To(prrecord.Table, prrecord.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, prcommitusagesnapshot.PrRecordTable, prcommitusagesnapshot.PrRecordColumn),
		)
		fromU = sqlgraph.SetNeighbors(pcusq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryCommitCheckpoint chains the current query on the "commit_checkpoint" edge.
func (pcusq *PRCommitUsageSnapshotQuery) QueryCommitCheckpoint() *CommitCheckpointQuery {
	query := (&CommitCheckpointClient{config: pcusq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := pcusq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := pcusq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(prcommitusagesnapshot.Table, prcommitusagesnapshot.FieldID, selector),
			sqlgraph.To(commitcheckpoint.Table, commitcheckpoint.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, prcommitusagesnapshot.CommitCheckpointTable, prcommitusagesnapshot.CommitCheckpointColumn),
		)
		fromU = sqlgraph.SetNeighbors(pcusq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first PRCommitUsageSnapshot entity from the query.
// Returns a *NotFoundError when no PRCommitUsageSnapshot was found.
func (pcusq *PRCommitUsageSnapshotQuery) First(ctx context.Context) (*PRCommitUsageSnapshot, error) {
	nodes, err := pcusq.Limit(1).All(setContextOp(ctx, pcusq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{prcommitusagesnapshot.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (pcusq *PRCommitUsageSnapshotQuery) FirstX(ctx context.Context) *PRCommitUsageSnapshot {
	node, err := pcusq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first PRCommitUsageSnapshot ID from the query.
// Returns a *NotFoundError when no PRCommitUsageSnapshot ID was found.
func (pcusq *PRCommitUsageSnapshotQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = pcusq.Limit(1).IDs(setContextOp(ctx, pcusq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{prcommitusagesnapshot.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (pcusq *PRCommitUsageSnapshotQuery) FirstIDX(ctx context.Context) int {
	id, err := pcusq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single PRCommitUsageSnapshot entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one PRCommitUsageSnapshot entity is found.
// Returns a *NotFoundError when no PRCommitUsageSnapshot entities are found.
func (pcusq *PRCommitUsageSnapshotQuery) Only(ctx context.Context) (*PRCommitUsageSnapshot, error) {
	nodes, err := pcusq.Limit(2).All(setContextOp(ctx, pcusq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{prcommitusagesnapshot.Label}
	default:
		return nil, &NotSingularError{prcommitusagesnapshot.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (pcusq *PRCommitUsageSnapshotQuery) OnlyX(ctx context.Context) *PRCommitUsageSnapshot {
	node, err := pcusq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only PRCommitUsageSnapshot ID in the query.
// Returns a *NotSingularError when more than one PRCommitUsageSnapshot ID is found.
// Returns a *NotFoundError when no entities are found.
func (pcusq *PRCommitUsageSnapshotQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = pcusq.Limit(2).IDs(setContextOp(ctx, pcusq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{prcommitusagesnapshot.Label}
	default:
		err = &NotSingularError{prcommitusagesnapshot.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (pcusq *PRCommitUsageSnapshotQuery) OnlyIDX(ctx context.Context) int {
	id, err := pcusq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of PRCommitUsageSnapshots.
func (pcusq *PRCommitUsageSnapshotQuery) All(ctx context.Context) ([]*PRCommitUsageSnapshot, error) {
	ctx = setContextOp(ctx, pcusq.ctx, ent.OpQueryAll)
	if err := pcusq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*PRCommitUsageSnapshot, *PRCommitUsageSnapshotQuery]()
	return withInterceptors[[]*PRCommitUsageSnapshot](ctx, pcusq, qr, pcusq.inters)
}

// AllX is like All, but panics if an error occurs.
func (pcusq *PRCommitUsageSnapshotQuery) AllX(ctx context.Context) []*PRCommitUsageSnapshot {
	nodes, err := pcusq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of PRCommitUsageSnapshot IDs.
func (pcusq *PRCommitUsageSnapshotQuery) IDs(ctx context.Context) (ids []int, err error) {
	if pcusq.ctx.Unique == nil && pcusq.path != nil {
		pcusq.Unique(true)
	}
	ctx = setContextOp(ctx, pcusq.ctx, ent.OpQueryIDs)
	if err = pcusq.Select(prcommitusagesnapshot.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (pcusq *PRCommitUsageSnapshotQuery) IDsX(ctx context.Context) []int {
	ids, err := pcusq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (pcusq *PRCommitUsageSnapshotQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, pcusq.ctx, ent.OpQueryCount)
	if err := pcusq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, pcusq, querierCount[*PRCommitUsageSnapshotQuery](), pcusq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (pcusq *PRCommitUsageSnapshotQuery) CountX(ctx context.Context) int {
	count, err := pcusq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (pcusq *PRCommitUsageSnapshotQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, pcusq.ctx, ent.OpQueryExist)
	switch _, err := pcusq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (pcusq *PRCommitUsageSnapshotQuery) ExistX(ctx context.Context) bool {
	exist, err := pcusq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the PRCommitUsageSnapshotQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (pcusq *PRCommitUsageSnapshotQuery) Clone() *PRCommitUsageSnapshotQuery {
	if pcusq == nil {
		return nil
	}
	return &PRCommitUsageSnapshotQuery{
		config:               pcusq.config,
		ctx:                  pcusq.ctx.Clone(),
		order:                append([]prcommitusagesnapshot.OrderOption{}, pcusq.order...),
		inters:               append([]Interceptor{}, pcusq.inters...),
		predicates:           append([]predicate.PRCommitUsageSnapshot{}, pcusq.predicates...),
		withPrRecord:         pcusq.withPrRecord.Clone(),
		withCommitCheckpoint: pcusq.withCommitCheckpoint.Clone(),
		// clone intermediate query.
		sql:  pcusq.sql.Clone(),
		path: pcusq.path,
	}
}

// WithPrRecord tells the query-builder to eager-load the nodes that are connected to
// the "pr_record" edge. The optional arguments are used to configure the query builder of the edge.
func (pcusq *PRCommitUsageSnapshotQuery) WithPrRecord(opts ...func(*PrRecordQuery)) *PRCommitUsageSnapshotQuery {
	query := (&PrRecordClient{config: pcusq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	pcusq.withPrRecord = query
	return pcusq
}

// WithCommitCheckpoint tells the query-builder to eager-load the nodes that are connected to
// the "commit_checkpoint" edge. The optional arguments are used to configure the query builder of the edge.
func (pcusq *PRCommitUsageSnapshotQuery) WithCommitCheckpoint(opts ...func(*CommitCheckpointQuery)) *PRCommitUsageSnapshotQuery {
	query := (&CommitCheckpointClient{config: pcusq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	pcusq.withCommitCheckpoint = query
	return pcusq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		PrRecordID int `json:"pr_record_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.PRCommitUsageSnapshot.Query().
//		GroupBy(prcommitusagesnapshot.FieldPrRecordID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (pcusq *PRCommitUsageSnapshotQuery) GroupBy(field string, fields ...string) *PRCommitUsageSnapshotGroupBy {
	pcusq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &PRCommitUsageSnapshotGroupBy{build: pcusq}
	grbuild.flds = &pcusq.ctx.Fields
	grbuild.label = prcommitusagesnapshot.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		PrRecordID int `json:"pr_record_id,omitempty"`
//	}
//
//	client.PRCommitUsageSnapshot.Query().
//		Select(prcommitusagesnapshot.FieldPrRecordID).
//		Scan(ctx, &v)
func (pcusq *PRCommitUsageSnapshotQuery) Select(fields ...string) *PRCommitUsageSnapshotSelect {
	pcusq.ctx.Fields = append(pcusq.ctx.Fields, fields...)
	sbuild := &PRCommitUsageSnapshotSelect{PRCommitUsageSnapshotQuery: pcusq}
	sbuild.label = prcommitusagesnapshot.Label
	sbuild.flds, sbuild.scan = &pcusq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a PRCommitUsageSnapshotSelect configured with the given aggregations.
func (pcusq *PRCommitUsageSnapshotQuery) Aggregate(fns ...AggregateFunc) *PRCommitUsageSnapshotSelect {
	return pcusq.Select().Aggregate(fns...)
}

func (pcusq *PRCommitUsageSnapshotQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range pcusq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, pcusq); err != nil {
				return err
			}
		}
	}
	for _, f := range pcusq.ctx.Fields {
		if !prcommitusagesnapshot.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if pcusq.path != nil {
		prev, err := pcusq.path(ctx)
		if err != nil {
			return err
		}
		pcusq.sql = prev
	}
	return nil
}

func (pcusq *PRCommitUsageSnapshotQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*PRCommitUsageSnapshot, error) {
	var (
		nodes       = []*PRCommitUsageSnapshot{}
		_spec       = pcusq.querySpec()
		loadedTypes = [2]bool{
			pcusq.withPrRecord != nil,
			pcusq.withCommitCheckpoint != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*PRCommitUsageSnapshot).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &PRCommitUsageSnapshot{config: pcusq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, pcusq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := pcusq.withPrRecord; query != nil {
		if err := pcusq.loadPrRecord(ctx, query, nodes, nil,
			func(n *PRCommitUsageSnapshot, e *PrRecord) { n.Edges.PrRecord = e }); err != nil {
			return nil, err
		}
	}
	if query := pcusq.withCommitCheckpoint; query != nil {
		if err := pcusq.loadCommitCheckpoint(ctx, query, nodes, nil,
			func(n *PRCommitUsageSnapshot, e *CommitCheckpoint) { n.Edges.CommitCheckpoint = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (pcusq *PRCommitUsageSnapshotQuery) loadPrRecord(ctx context.Context, query *PrRecordQuery, nodes []*PRCommitUsageSnapshot, init func(*PRCommitUsageSnapshot), assign func(*PRCommitUsageSnapshot, *PrRecord)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*PRCommitUsageSnapshot)
	for i := range nodes {
		fk := nodes[i].PrRecordID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(prrecord.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "pr_record_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (pcusq *PRCommitUsageSnapshotQuery) loadCommitCheckpoint(ctx context.Context, query *CommitCheckpointQuery, nodes []*PRCommitUsageSnapshot, init func(*PRCommitUsageSnapshot), assign func(*PRCommitUsageSnapshot, *CommitCheckpoint)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*PRCommitUsageSnapshot)
	for i := range nodes {
		if nodes[i].CommitCheckpointID == nil {
			continue
		}
		fk := *nodes[i].CommitCheckpointID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(commitcheckpoint.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "commit_checkpoint_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (pcusq *PRCommitUsageSnapshotQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := pcusq.querySpec()
	_spec.Node.Columns = pcusq.ctx.Fields
	if len(pcusq.ctx.Fields) > 0 {
		_spec.Unique = pcusq.ctx.Unique != nil && *pcusq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, pcusq.driver, _spec)
}

func (pcusq *PRCommitUsageSnapshotQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(prcommitusagesnapshot.Table, prcommitusagesnapshot.Columns, sqlgraph.NewFieldSpec(prcommitusagesnapshot.FieldID, field.TypeInt))
	_spec.From = pcusq.sql
	if unique := pcusq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if pcusq.path != nil {
		_spec.Unique = true
	}
	if fields := pcusq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, prcommitusagesnapshot.FieldID)
		for i := range fields {
			if fields[i] != prcommitusagesnapshot.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if pcusq.withPrRecord != nil {
			_spec.Node.AddColumnOnce(prcommitusagesnapshot.FieldPrRecordID)
		}
		if pcusq.withCommitCheckpoint != nil {
			_spec.Node.AddColumnOnce(prcommitusagesnapshot.FieldCommitCheckpointID)
		}
	}
	if ps := pcusq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := pcusq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := pcusq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := pcusq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (pcusq *PRCommitUsageSnapshotQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(pcusq.driver.Dialect())
	t1 := builder.Table(prcommitusagesnapshot.Table)
	columns := pcusq.ctx.Fields
	if len(columns) == 0 {
		columns = prcommitusagesnapshot.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if pcusq.sql != nil {
		selector = pcusq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if pcusq.ctx.Unique != nil && *pcusq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range pcusq.predicates {
		p(selector)
	}
	for _, p := range pcusq.order {
		p(selector)
	}
	if offset := pcusq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := pcusq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// PRCommitUsageSnapshotGroupBy is the group-by builder for PRCommitUsageSnapshot entities.
type PRCommitUsageSnapshotGroupBy struct {
	selector
	build *PRCommitUsageSnapshotQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (pcusgb *PRCommitUsageSnapshotGroupBy) Aggregate(fns ...AggregateFunc) *PRCommitUsageSnapshotGroupBy {
	pcusgb.fns = append(pcusgb.fns, fns...)
	return pcusgb
}

// Scan applies the selector query and scans the result into the given value.
func (pcusgb *PRCommitUsageSnapshotGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, pcusgb.build.ctx, ent.OpQueryGroupBy)
	if err := pcusgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*PRCommitUsageSnapshotQuery, *PRCommitUsageSnapshotGroupBy](ctx, pcusgb.build, pcusgb, pcusgb.build.inters, v)
}

func (pcusgb *PRCommitUsageSnapshotGroupBy) sqlScan(ctx context.Context, root *PRCommitUsageSnapshotQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(pcusgb.fns))
	for _, fn := range pcusgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*pcusgb.flds)+len(pcusgb.fns))
		for _, f := range *pcusgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*pcusgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := pcusgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// PRCommitUsageSnapshotSelect is the builder for selecting fields of PRCommitUsageSnapshot entities.
type PRCommitUsageSnapshotSelect struct {
	*PRCommitUsageSnapshotQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (pcuss *PRCommitUsageSnapshotSelect) Aggregate(fns ...AggregateFunc) *PRCommitUsageSnapshotSelect {
	pcuss.fns = append(pcuss.fns, fns...)
	return pcuss
}

// Scan applies the selector query and scans the result into the given value.
func (pcuss *PRCommitUsageSnapshotSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, pcuss.ctx, ent.OpQuerySelect)
	if err := pcuss.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*PRCommitUsageSnapshotQuery, *PRCommitUsageSnapshotSelect](ctx, pcuss.PRCommitUsageSnapshotQuery, pcuss, pcuss.inters, v)
}

func (pcuss *PRCommitUsageSnapshotSelect) sqlScan(ctx context.Context, root *PRCommitUsageSnapshotQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(pcuss.fns))
	for _, fn := range pcuss.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*pcuss.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := pcuss.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
