// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ai-efficiency/backend/ent/prattributionrun"
	"github.com/ai-efficiency/backend/ent/predicate"
	"github.com/ai-efficiency/backend/ent/prrecord"
	"github.com/ai-efficiency/backend/ent/repoconfig"
)

// PrRecordQuery is the builder for querying PrRecord entities.
type PrRecordQuery struct {
	config
	ctx                    *QueryContext
	order                  []prrecord.OrderOption
	inters                 []Interceptor
	predicates             []predicate.PrRecord
	withRepoConfig         *RepoConfigQuery
	withAttributionRuns    *PrAttributionRunQuery
	withLastAttributionRun *PrAttributionRunQuery
	withFKs                bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the PrRecordQuery builder.
func (prq *PrRecordQuery) Where(ps ...predicate.PrRecord) *PrRecordQuery {
	prq.predicates = append(prq.predicates, ps...)
	return prq
}

// Limit the number of records to be returned by this query.
func (prq *PrRecordQuery) Limit(limit int) *PrRecordQuery {
	prq.ctx.Limit = &limit
	return prq
}

// Offset to start from.
func (prq *PrRecordQuery) Offset(offset int) *PrRecordQuery {
	prq.ctx.Offset = &offset
	return prq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (prq *PrRecordQuery) Unique(unique bool) *PrRecordQuery {
	prq.ctx.Unique = &unique
	return prq
}

// Order specifies how the records should be ordered.
func (prq *PrRecordQuery) Order(o ...prrecord.OrderOption) *PrRecordQuery {
	prq.order = append(prq.order, o...)
	return prq
}

// QueryRepoConfig chains the current query on the "repo_config" edge.
func (prq *PrRecordQuery) QueryRepoConfig() *RepoConfigQuery {
	query := (&RepoConfigClient{config: prq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := prq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := prq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(prrecord.Table, prrecord.FieldID, selector),
			sqlgraph.To(repoconfig.Table, repoconfig.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, prrecord.RepoConfigTable, prrecord.RepoConfigColumn),
		)
		fromU = sqlgraph.SetNeighbors(prq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryAttributionRuns chains the current query on the "attribution_runs" edge.
func (prq *PrRecordQuery) QueryAttributionRuns() *PrAttributionRunQuery {
	query := (&PrAttributionRunClient{config: prq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := prq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := prq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(prrecord.Table, prrecord.FieldID, selector),
			sqlgraph.To(prattributionrun.Table, prattributionrun.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, prrecord.AttributionRunsTable, prrecord.AttributionRunsColumn),
		)
		fromU = sqlgraph.SetNeighbors(prq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryLastAttributionRun chains the current query on the "last_attribution_run" edge.
func (prq *PrRecordQuery) QueryLastAttributionRun() *PrAttributionRunQuery {
	query := (&PrAttributionRunClient{config: prq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := prq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := prq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(prrecord.Table, prrecord.FieldID, selector),
			sqlgraph.To(prattributionrun.Table, prattributionrun.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, prrecord.LastAttributionRunTable, prrecord.LastAttributionRunColumn),
		)
		fromU = sqlgraph.SetNeighbors(prq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first PrRecord entity from the query.
// Returns a *NotFoundError when no PrRecord was found.
func (prq *PrRecordQuery) First(ctx context.Context) (*PrRecord, error) {
	nodes, err := prq.Limit(1).All(setContextOp(ctx, prq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{prrecord.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (prq *PrRecordQuery) FirstX(ctx context.Context) *PrRecord {
	node, err := prq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first PrRecord ID from the query.
// Returns a *NotFoundError when no PrRecord ID was found.
func (prq *PrRecordQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = prq.Limit(1).IDs(setContextOp(ctx, prq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{prrecord.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (prq *PrRecordQuery) FirstIDX(ctx context.Context) int {
	id, err := prq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single PrRecord entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one PrRecord entity is found.
// Returns a *NotFoundError when no PrRecord entities are found.
func (prq *PrRecordQuery) Only(ctx context.Context) (*PrRecord, error) {
	nodes, err := prq.Limit(2).All(setContextOp(ctx, prq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{prrecord.Label}
	default:
		return nil, &NotSingularError{prrecord.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (prq *PrRecordQuery) OnlyX(ctx context.Context) *PrRecord {
	node, err := prq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only PrRecord ID in the query.
// Returns a *NotSingularError when more than one PrRecord ID is found.
// Returns a *NotFoundError when no entities are found.
func (prq *PrRecordQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = prq.Limit(2).IDs(setContextOp(ctx, prq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{prrecord.Label}
	default:
		err = &NotSingularError{prrecord.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (prq *PrRecordQuery) OnlyIDX(ctx context.Context) int {
	id, err := prq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of PrRecords.
func (prq *PrRecordQuery) All(ctx context.Context) ([]*PrRecord, error) {
	ctx = setContextOp(ctx, prq.ctx, ent.OpQueryAll)
	if err := prq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*PrRecord, *PrRecordQuery]()
	return withInterceptors[[]*PrRecord](ctx, prq, qr, prq.inters)
}

// AllX is like All, but panics if an error occurs.
func (prq *PrRecordQuery) AllX(ctx context.Context) []*PrRecord {
	nodes, err := prq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of PrRecord IDs.
func (prq *PrRecordQuery) IDs(ctx context.Context) (ids []int, err error) {
	if prq.ctx.Unique == nil && prq.path != nil {
		prq.Unique(true)
	}
	ctx = setContextOp(ctx, prq.ctx, ent.OpQueryIDs)
	if err = prq.Select(prrecord.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (prq *PrRecordQuery) IDsX(ctx context.Context) []int {
	ids, err := prq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (prq *PrRecordQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, prq.ctx, ent.OpQueryCount)
	if err := prq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, prq, querierCount[*PrRecordQuery](), prq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (prq *PrRecordQuery) CountX(ctx context.Context) int {
	count, err := prq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (prq *PrRecordQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, prq.ctx, ent.OpQueryExist)
	switch _, err := prq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (prq *PrRecordQuery) ExistX(ctx context.Context) bool {
	exist, err := prq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the PrRecordQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (prq *PrRecordQuery) Clone() *PrRecordQuery {
	if prq == nil {
		return nil
	}
	return &PrRecordQuery{
		config:                 prq.config,
		ctx:                    prq.ctx.Clone(),
		order:                  append([]prrecord.OrderOption{}, prq.order...),
		inters:                 append([]Interceptor{}, prq.inters...),
		predicates:             append([]predicate.PrRecord{}, prq.predicates...),
		withRepoConfig:         prq.withRepoConfig.Clone(),
		withAttributionRuns:    prq.withAttributionRuns.Clone(),
		withLastAttributionRun: prq.withLastAttributionRun.Clone(),
		// clone intermediate query.
		sql:  prq.sql.Clone(),
		path: prq.path,
	}
}

// WithRepoConfig tells the query-builder to eager-load the nodes that are connected to
// the "repo_config" edge. The optional arguments are used to configure the query builder of the edge.
func (prq *PrRecordQuery) WithRepoConfig(opts ...func(*RepoConfigQuery)) *PrRecordQuery {
	query := (&RepoConfigClient{config: prq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	prq.withRepoConfig = query
	return prq
}

// WithAttributionRuns tells the query-builder to eager-load the nodes that are connected to
// the "attribution_runs" edge. The optional arguments are used to configure the query builder of the edge.
func (prq *PrRecordQuery) WithAttributionRuns(opts ...func(*PrAttributionRunQuery)) *PrRecordQuery {
	query := (&PrAttributionRunClient{config: prq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	prq.withAttributionRuns = query
	return prq
}

// WithLastAttributionRun tells the query-builder to eager-load the nodes that are connected to
// the "last_attribution_run" edge. The optional arguments are used to configure the query builder of the edge.
func (prq *PrRecordQuery) WithLastAttributionRun(opts ...func(*PrAttributionRunQuery)) *PrRecordQuery {
	query := (&PrAttributionRunClient{config: prq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	prq.withLastAttributionRun = query
	return prq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		ScmPrID int `json:"scm_pr_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.PrRecord.Query().
//		GroupBy(prrecord.FieldScmPrID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (prq *PrRecordQuery) GroupBy(field string, fields ...string) *PrRecordGroupBy {
	prq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &PrRecordGroupBy{build: prq}
	grbuild.flds = &prq.ctx.Fields
	grbuild.label = prrecord.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		ScmPrID int `json:"scm_pr_id,omitempty"`
//	}
//
//	client.PrRecord.Query().
//		Select(prrecord.FieldScmPrID).
//		Scan(ctx, &v)
func (prq *PrRecordQuery) Select(fields ...string) *PrRecordSelect {
	prq.ctx.Fields = append(prq.ctx.Fields, fields...)
	sbuild := &PrRecordSelect{PrRecordQuery: prq}
	sbuild.label = prrecord.Label
	sbuild.flds, sbuild.scan = &prq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a PrRecordSelect configured with the given aggregations.
func (prq *PrRecordQuery) Aggregate(fns ...AggregateFunc) *PrRecordSelect {
	return prq.Select().Aggregate(fns...)
}

func (prq *PrRecordQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range prq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, prq); err != nil {
				return err
			}
		}
	}
	for _, f := range prq.ctx.Fields {
		if !prrecord.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if prq.path != nil {
		prev, err := prq.path(ctx)
		if err != nil {
			return err
		}
		prq.sql = prev
	}
	return nil
}

func (prq *PrRecordQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*PrRecord, error) {
	var (
		nodes       = []*PrRecord{}
		withFKs     = prq.withFKs
		_spec       = prq.querySpec()
		loadedTypes = [3]bool{
			prq.withRepoConfig != nil,
			prq.withAttributionRuns != nil,
			prq.withLastAttributionRun != nil,
		}
	)
	if prq.withRepoConfig != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, prrecord.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*PrRecord).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &PrRecord{config: prq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, prq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := prq.withRepoConfig; query != nil {
		if err := prq.loadRepoConfig(ctx, query, nodes, nil,
			func(n *PrRecord, e *RepoConfig) { n.Edges.RepoConfig = e }); err != nil {
			return nil, err
		}
	}
	if query := prq.withAttributionRuns; query != nil {
		if err := prq.loadAttributionRuns(ctx, query, nodes,
			func(n *PrRecord) { n.Edges.AttributionRuns = []*PrAttributionRun{} },
			func(n *PrRecord, e *PrAttributionRun) { n.Edges.AttributionRuns = append(n.Edges.AttributionRuns, e) }); err != nil {
			return nil, err
		}
	}
	if query := prq.withLastAttributionRun; query != nil {
		if err := prq.loadLastAttributionRun(ctx, query, nodes, nil,
			func(n *PrRecord, e *PrAttributionRun) { n.Edges.LastAttributionRun = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (prq *PrRecordQuery) loadRepoConfig(ctx context.Context, query *RepoConfigQuery, nodes []*PrRecord, init func(*PrRecord), assign func(*PrRecord, *RepoConfig)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*PrRecord)
	for i := range nodes {
		if nodes[i].repo_config_pr_records == nil {
			continue
		}
		fk := *nodes[i].repo_config_pr_records
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(repoconfig.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "repo_config_pr_records" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (prq *PrRecordQuery) loadAttributionRuns(ctx context.Context, query *PrAttributionRunQuery, nodes []*PrRecord, init func(*PrRecord), assign func(*PrRecord, *PrAttributionRun)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*PrRecord)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(prattributionrun.FieldPrRecordID)
	}
	query.Where(predicate.PrAttributionRun(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(prrecord.AttributionRunsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.PrRecordID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "pr_record_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (prq *PrRecordQuery) loadLastAttributionRun(ctx context.Context, query *PrAttributionRunQuery, nodes []*PrRecord, init func(*PrRecord), assign func(*PrRecord, *PrAttributionRun)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*PrRecord)
	for i := range nodes {
		if nodes[i].LastAttributionRunID == nil {
			continue
		}
		fk := *nodes[i].LastAttributionRunID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(prattributionrun.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "last_attribution_run_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (prq *PrRecordQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := prq.querySpec()
	_spec.Node.Columns = prq.ctx.Fields
	if len(prq.ctx.Fields) > 0 {
		_spec.Unique = prq.ctx.Unique != nil && *prq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, prq.driver, _spec)
}

func (prq *PrRecordQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(prrecord.Table, prrecord.Columns, sqlgraph.NewFieldSpec(prrecord.FieldID, field.TypeInt))
	_spec.From = prq.sql
	if unique := prq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if prq.path != nil {
		_spec.Unique = true
	}
	if fields := prq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, prrecord.FieldID)
		for i := range fields {
			if fields[i] != prrecord.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if prq.withLastAttributionRun != nil {
			_spec.Node.AddColumnOnce(prrecord.FieldLastAttributionRunID)
		}
	}
	if ps := prq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := prq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := prq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := prq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (prq *PrRecordQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(prq.driver.Dialect())
	t1 := builder.Table(prrecord.Table)
	columns := prq.ctx.Fields
	if len(columns) == 0 {
		columns = prrecord.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if prq.sql != nil {
		selector = prq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if prq.ctx.Unique != nil && *prq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range prq.predicates {
		p(selector)
	}
	for _, p := range prq.order {
		p(selector)
	}
	if offset := prq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := prq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// PrRecordGroupBy is the group-by builder for PrRecord entities.
type PrRecordGroupBy struct {
	selector
	build *PrRecordQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (prgb *PrRecordGroupBy) Aggregate(fns ...AggregateFunc) *PrRecordGroupBy {
	prgb.fns = append(prgb.fns, fns...)
	return prgb
}

// Scan applies the selector query and scans the result into the given value.
func (prgb *PrRecordGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, prgb.build.ctx, ent.OpQueryGroupBy)
	if err := prgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*PrRecordQuery, *PrRecordGroupBy](ctx, prgb.build, prgb, prgb.build.inters, v)
}

func (prgb *PrRecordGroupBy) sqlScan(ctx context.Context, root *PrRecordQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(prgb.fns))
	for _, fn := range prgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*prgb.flds)+len(prgb.fns))
		for _, f := range *prgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*prgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := prgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// PrRecordSelect is the builder for selecting fields of PrRecord entities.
type PrRecordSelect struct {
	*PrRecordQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (prs *PrRecordSelect) Aggregate(fns ...AggregateFunc) *PrRecordSelect {
	prs.fns = append(prs.fns, fns...)
	return prs
}

// Scan applies the selector query and scans the result into the given value.
func (prs *PrRecordSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, prs.ctx, ent.OpQuerySelect)
	if err := prs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*PrRecordQuery, *PrRecordSelect](ctx, prs.PrRecordQuery, prs, prs.inters, v)
}

func (prs *PrRecordSelect) sqlScan(ctx context.Context, root *PrRecordQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(prs.fns))
	for _, fn := range prs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*prs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := prs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
