// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ai-efficiency/backend/ent/predicate"
	"github.com/ai-efficiency/backend/ent/quotaresetapprovalchainnode"
)

// QuotaResetApprovalChainNodeDelete is the builder for deleting a QuotaResetApprovalChainNode entity.
type QuotaResetApprovalChainNodeDelete struct {
	config
	hooks    []Hook
	mutation *QuotaResetApprovalChainNodeMutation
}

// Where appends a list predicates to the QuotaResetApprovalChainNodeDelete builder.
func (qracnd *QuotaResetApprovalChainNodeDelete) Where(ps ...predicate.QuotaResetApprovalChainNode) *QuotaResetApprovalChainNodeDelete {
	qracnd.mutation.Where(ps...)
	return qracnd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (qracnd *QuotaResetApprovalChainNodeDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, qracnd.sqlExec, qracnd.mutation, qracnd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (qracnd *QuotaResetApprovalChainNodeDelete) ExecX(ctx context.Context) int {
	n, err := qracnd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (qracnd *QuotaResetApprovalChainNodeDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(quotaresetapprovalchainnode.Table, sqlgraph.NewFieldSpec(quotaresetapprovalchainnode.FieldID, field.TypeInt))
	if ps := qracnd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, qracnd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	qracnd.mutation.done = true
	return affected, err
}

// QuotaResetApprovalChainNodeDeleteOne is the builder for deleting a single QuotaResetApprovalChainNode entity.
type QuotaResetApprovalChainNodeDeleteOne struct {
	qracnd *QuotaResetApprovalChainNodeDelete
}

// Where appends a list predicates to the QuotaResetApprovalChainNodeDelete builder.
func (qracndo *QuotaResetApprovalChainNodeDeleteOne) Where(ps ...predicate.QuotaResetApprovalChainNode) *QuotaResetApprovalChainNodeDeleteOne {
	qracndo.qracnd.mutation.Where(ps...)
	return qracndo
}

// Exec executes the deletion query.
func (qracndo *QuotaResetApprovalChainNodeDeleteOne) Exec(ctx context.Context) error {
	n, err := qracndo.qracnd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{quotaresetapprovalchainnode.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (qracndo *QuotaResetApprovalChainNodeDeleteOne) ExecX(ctx context.Context) {
	if err := qracndo.Exec(ctx); err != nil {
		panic(err)
	}
}
