// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/ai-efficiency/backend/ent/quotaresetrequestnodeapprover"
)

// QuotaResetRequestNodeApprover is the model entity for the QuotaResetRequestNodeApprover schema.
type QuotaResetRequestNodeApprover struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// RequestNodeID holds the value of the "request_node_id" field.
	RequestNodeID int `json:"request_node_id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int `json:"user_id,omitempty"`
	// DisplayName holds the value of the "display_name" field.
	DisplayName string `json:"display_name,omitempty"`
	// Email holds the value of the "email" field.
	Email string `json:"email,omitempty"`
	// Source holds the value of the "source" field.
	Source quotaresetrequestnodeapprover.Source `json:"source,omitempty"`
	// SourceDepartmentExternalIds holds the value of the "source_department_external_ids" field.
	SourceDepartmentExternalIds []string `json:"source_department_external_ids,omitempty"`
	// NotificationIds holds the value of the "notification_ids" field.
	NotificationIds map[string]string `json:"notification_ids,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt    time.Time `json:"created_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*QuotaResetRequestNodeApprover) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case quotaresetrequestnodeapprover.FieldSourceDepartmentExternalIds, quotaresetrequestnodeapprover.FieldNotificationIds:
			values[i] = new([]byte)
		case quotaresetrequestnodeapprover.FieldID, quotaresetrequestnodeapprover.FieldRequestNodeID, quotaresetrequestnodeapprover.FieldUserID:
			values[i] = new(sql.NullInt64)
		case quotaresetrequestnodeapprover.FieldDisplayName, quotaresetrequestnodeapprover.FieldEmail, quotaresetrequestnodeapprover.FieldSource:
			values[i] = new(sql.NullString)
		case quotaresetrequestnodeapprover.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the QuotaResetRequestNodeApprover fields.
func (qrrna *QuotaResetRequestNodeApprover) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case quotaresetrequestnodeapprover.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			qrrna.ID = int(value.Int64)
		case quotaresetrequestnodeapprover.FieldRequestNodeID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field request_node_id", values[i])
			} else if value.Valid {
				qrrna.RequestNodeID = int(value.Int64)
			}
		case quotaresetrequestnodeapprover.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				qrrna.UserID = int(value.Int64)
			}
		case quotaresetrequestnodeapprover.FieldDisplayName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field display_name", values[i])
			} else if value.Valid {
				qrrna.DisplayName = value.String
			}
		case quotaresetrequestnodeapprover.FieldEmail:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field email", values[i])
			} else if value.Valid {
				qrrna.Email = value.String
			}
		case quotaresetrequestnodeapprover.FieldSource:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source", values[i])
			} else if value.Valid {
				qrrna.Source = quotaresetrequestnodeapprover.Source(value.String)
			}
		case quotaresetrequestnodeapprover.FieldSourceDepartmentExternalIds:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field source_department_external_ids", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &qrrna.SourceDepartmentExternalIds); err != nil {
					return fmt.Errorf("unmarshal field source_department_external_ids: %w", err)
				}
			}
		case quotaresetrequestnodeapprover.FieldNotificationIds:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field notification_ids", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &qrrna.NotificationIds); err != nil {
					return fmt.Errorf("unmarshal field notification_ids: %w", err)
				}
			}
		case quotaresetrequestnodeapprover.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				qrrna.CreatedAt = value.Time
			}
		default:
			qrrna.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the QuotaResetRequestNodeApprover.
// This includes values selected through modifiers, order, etc.
func (qrrna *QuotaResetRequestNodeApprover) Value(name string) (ent.Value, error) {
	return qrrna.selectValues.Get(name)
}

// Update returns a builder for updating this QuotaResetRequestNodeApprover.
// Note that you need to call QuotaResetRequestNodeApprover.Unwrap() before calling this method if this QuotaResetRequestNodeApprover
// was returned from a transaction, and the transaction was committed or rolled back.
func (qrrna *QuotaResetRequestNodeApprover) Update() *QuotaResetRequestNodeApproverUpdateOne {
	return NewQuotaResetRequestNodeApproverClient(qrrna.config).UpdateOne(qrrna)
}

// Unwrap unwraps the QuotaResetRequestNodeApprover entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (qrrna *QuotaResetRequestNodeApprover) Unwrap() *QuotaResetRequestNodeApprover {
	_tx, ok := qrrna.config.driver.(*txDriver)
	if !ok {
		panic("ent: QuotaResetRequestNodeApprover is not a transactional entity")
	}
	qrrna.config.driver = _tx.drv
	return qrrna
}

// String implements the fmt.Stringer.
func (qrrna *QuotaResetRequestNodeApprover) String() string {
	var builder strings.Builder
	builder.WriteString("QuotaResetRequestNodeApprover(")
	builder.WriteString(fmt.Sprintf("id=%v, ", qrrna.ID))
	builder.WriteString("request_node_id=")
	builder.WriteString(fmt.Sprintf("%v", qrrna.RequestNodeID))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", qrrna.UserID))
	builder.WriteString(", ")
	builder.WriteString("display_name=")
	builder.WriteString(qrrna.DisplayName)
	builder.WriteString(", ")
	builder.WriteString("email=")
	builder.WriteString(qrrna.Email)
	builder.WriteString(", ")
	builder.WriteString("source=")
	builder.WriteString(fmt.Sprintf("%v", qrrna.Source))
	builder.WriteString(", ")
	builder.WriteString("source_department_external_ids=")
	builder.WriteString(fmt.Sprintf("%v", qrrna.SourceDepartmentExternalIds))
	builder.WriteString(", ")
	builder.WriteString("notification_ids=")
	builder.WriteString(fmt.Sprintf("%v", qrrna.NotificationIds))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(qrrna.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// QuotaResetRequestNodeApprovers is a parsable slice of QuotaResetRequestNodeApprover.
type QuotaResetRequestNodeApprovers []*QuotaResetRequestNodeApprover
