// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ai-efficiency/backend/ent/predicate"
	"github.com/ai-efficiency/backend/ent/quotaresetrequestevent"
)

// QuotaResetRequestEventDelete is the builder for deleting a QuotaResetRequestEvent entity.
type QuotaResetRequestEventDelete struct {
	config
	hooks    []Hook
	mutation *QuotaResetRequestEventMutation
}

// Where appends a list predicates to the QuotaResetRequestEventDelete builder.
func (qrred *QuotaResetRequestEventDelete) Where(ps ...predicate.QuotaResetRequestEvent) *QuotaResetRequestEventDelete {
	qrred.mutation.Where(ps...)
	return qrred
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (qrred *QuotaResetRequestEventDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, qrred.sqlExec, qrred.mutation, qrred.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (qrred *QuotaResetRequestEventDelete) ExecX(ctx context.Context) int {
	n, err := qrred.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (qrred *QuotaResetRequestEventDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(quotaresetrequestevent.Table, sqlgraph.NewFieldSpec(quotaresetrequestevent.FieldID, field.TypeInt))
	if ps := qrred.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, qrred.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	qrred.mutation.done = true
	return affected, err
}

// QuotaResetRequestEventDeleteOne is the builder for deleting a single QuotaResetRequestEvent entity.
type QuotaResetRequestEventDeleteOne struct {
	qrred *QuotaResetRequestEventDelete
}

// Where appends a list predicates to the QuotaResetRequestEventDelete builder.
func (qrredo *QuotaResetRequestEventDeleteOne) Where(ps ...predicate.QuotaResetRequestEvent) *QuotaResetRequestEventDeleteOne {
	qrredo.qrred.mutation.Where(ps...)
	return qrredo
}

// Exec executes the deletion query.
func (qrredo *QuotaResetRequestEventDeleteOne) Exec(ctx context.Context) error {
	n, err := qrredo.qrred.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{quotaresetrequestevent.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (qrredo *QuotaResetRequestEventDeleteOne) ExecX(ctx context.Context) {
	if err := qrredo.Exec(ctx); err != nil {
		panic(err)
	}
}
