// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ai-efficiency/backend/ent/predicate"
	"github.com/ai-efficiency/backend/ent/quotaresetapprovalchainnode"
)

// QuotaResetApprovalChainNodeQuery is the builder for querying QuotaResetApprovalChainNode entities.
type QuotaResetApprovalChainNodeQuery struct {
	config
	ctx        *QueryContext
	order      []quotaresetapprovalchainnode.OrderOption
	inters     []Interceptor
	predicates []predicate.QuotaResetApprovalChainNode
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the QuotaResetApprovalChainNodeQuery builder.
func (qracnq *QuotaResetApprovalChainNodeQuery) Where(ps ...predicate.QuotaResetApprovalChainNode) *QuotaResetApprovalChainNodeQuery {
	qracnq.predicates = append(qracnq.predicates, ps...)
	return qracnq
}

// Limit the number of records to be returned by this query.
func (qracnq *QuotaResetApprovalChainNodeQuery) Limit(limit int) *QuotaResetApprovalChainNodeQuery {
	qracnq.ctx.Limit = &limit
	return qracnq
}

// Offset to start from.
func (qracnq *QuotaResetApprovalChainNodeQuery) Offset(offset int) *QuotaResetApprovalChainNodeQuery {
	qracnq.ctx.Offset = &offset
	return qracnq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (qracnq *QuotaResetApprovalChainNodeQuery) Unique(unique bool) *QuotaResetApprovalChainNodeQuery {
	qracnq.ctx.Unique = &unique
	return qracnq
}

// Order specifies how the records should be ordered.
func (qracnq *QuotaResetApprovalChainNodeQuery) Order(o ...quotaresetapprovalchainnode.OrderOption) *QuotaResetApprovalChainNodeQuery {
	qracnq.order = append(qracnq.order, o...)
	return qracnq
}

// First returns the first QuotaResetApprovalChainNode entity from the query.
// Returns a *NotFoundError when no QuotaResetApprovalChainNode was found.
func (qracnq *QuotaResetApprovalChainNodeQuery) First(ctx context.Context) (*QuotaResetApprovalChainNode, error) {
	nodes, err := qracnq.Limit(1).All(setContextOp(ctx, qracnq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{quotaresetapprovalchainnode.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (qracnq *QuotaResetApprovalChainNodeQuery) FirstX(ctx context.Context) *QuotaResetApprovalChainNode {
	node, err := qracnq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first QuotaResetApprovalChainNode ID from the query.
// Returns a *NotFoundError when no QuotaResetApprovalChainNode ID was found.
func (qracnq *QuotaResetApprovalChainNodeQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = qracnq.Limit(1).IDs(setContextOp(ctx, qracnq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{quotaresetapprovalchainnode.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (qracnq *QuotaResetApprovalChainNodeQuery) FirstIDX(ctx context.Context) int {
	id, err := qracnq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single QuotaResetApprovalChainNode entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one QuotaResetApprovalChainNode entity is found.
// Returns a *NotFoundError when no QuotaResetApprovalChainNode entities are found.
func (qracnq *QuotaResetApprovalChainNodeQuery) Only(ctx context.Context) (*QuotaResetApprovalChainNode, error) {
	nodes, err := qracnq.Limit(2).All(setContextOp(ctx, qracnq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{quotaresetapprovalchainnode.Label}
	default:
		return nil, &NotSingularError{quotaresetapprovalchainnode.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (qracnq *QuotaResetApprovalChainNodeQuery) OnlyX(ctx context.Context) *QuotaResetApprovalChainNode {
	node, err := qracnq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only QuotaResetApprovalChainNode ID in the query.
// Returns a *NotSingularError when more than one QuotaResetApprovalChainNode ID is found.
// Returns a *NotFoundError when no entities are found.
func (qracnq *QuotaResetApprovalChainNodeQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = qracnq.Limit(2).IDs(setContextOp(ctx, qracnq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{quotaresetapprovalchainnode.Label}
	default:
		err = &NotSingularError{quotaresetapprovalchainnode.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (qracnq *QuotaResetApprovalChainNodeQuery) OnlyIDX(ctx context.Context) int {
	id, err := qracnq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of QuotaResetApprovalChainNodes.
func (qracnq *QuotaResetApprovalChainNodeQuery) All(ctx context.Context) ([]*QuotaResetApprovalChainNode, error) {
	ctx = setContextOp(ctx, qracnq.ctx, ent.OpQueryAll)
	if err := qracnq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*QuotaResetApprovalChainNode, *QuotaResetApprovalChainNodeQuery]()
	return withInterceptors[[]*QuotaResetApprovalChainNode](ctx, qracnq, qr, qracnq.inters)
}

// AllX is like All, but panics if an error occurs.
func (qracnq *QuotaResetApprovalChainNodeQuery) AllX(ctx context.Context) []*QuotaResetApprovalChainNode {
	nodes, err := qracnq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of QuotaResetApprovalChainNode IDs.
func (qracnq *QuotaResetApprovalChainNodeQuery) IDs(ctx context.Context) (ids []int, err error) {
	if qracnq.ctx.Unique == nil && qracnq.path != nil {
		qracnq.Unique(true)
	}
	ctx = setContextOp(ctx, qracnq.ctx, ent.OpQueryIDs)
	if err = qracnq.Select(quotaresetapprovalchainnode.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (qracnq *QuotaResetApprovalChainNodeQuery) IDsX(ctx context.Context) []int {
	ids, err := qracnq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (qracnq *QuotaResetApprovalChainNodeQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, qracnq.ctx, ent.OpQueryCount)
	if err := qracnq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, qracnq, querierCount[*QuotaResetApprovalChainNodeQuery](), qracnq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (qracnq *QuotaResetApprovalChainNodeQuery) CountX(ctx context.Context) int {
	count, err := qracnq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (qracnq *QuotaResetApprovalChainNodeQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, qracnq.ctx, ent.OpQueryExist)
	switch _, err := qracnq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (qracnq *QuotaResetApprovalChainNodeQuery) ExistX(ctx context.Context) bool {
	exist, err := qracnq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the QuotaResetApprovalChainNodeQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (qracnq *QuotaResetApprovalChainNodeQuery) Clone() *QuotaResetApprovalChainNodeQuery {
	if qracnq == nil {
		return nil
	}
	return &QuotaResetApprovalChainNodeQuery{
		config:     qracnq.config,
		ctx:        qracnq.ctx.Clone(),
		order:      append([]quotaresetapprovalchainnode.OrderOption{}, qracnq.order...),
		inters:     append([]Interceptor{}, qracnq.inters...),
		predicates: append([]predicate.QuotaResetApprovalChainNode{}, qracnq.predicates...),
		// clone intermediate query.
		sql:  qracnq.sql.Clone(),
		path: qracnq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		ChainID int `json:"chain_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.QuotaResetApprovalChainNode.Query().
//		GroupBy(quotaresetapprovalchainnode.FieldChainID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (qracnq *QuotaResetApprovalChainNodeQuery) GroupBy(field string, fields ...string) *QuotaResetApprovalChainNodeGroupBy {
	qracnq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &QuotaResetApprovalChainNodeGroupBy{build: qracnq}
	grbuild.flds = &qracnq.ctx.Fields
	grbuild.label = quotaresetapprovalchainnode.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		ChainID int `json:"chain_id,omitempty"`
//	}
//
//	client.QuotaResetApprovalChainNode.Query().
//		Select(quotaresetapprovalchainnode.FieldChainID).
//		Scan(ctx, &v)
func (qracnq *QuotaResetApprovalChainNodeQuery) Select(fields ...string) *QuotaResetApprovalChainNodeSelect {
	qracnq.ctx.Fields = append(qracnq.ctx.Fields, fields...)
	sbuild := &QuotaResetApprovalChainNodeSelect{QuotaResetApprovalChainNodeQuery: qracnq}
	sbuild.label = quotaresetapprovalchainnode.Label
	sbuild.flds, sbuild.scan = &qracnq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a QuotaResetApprovalChainNodeSelect configured with the given aggregations.
func (qracnq *QuotaResetApprovalChainNodeQuery) Aggregate(fns ...AggregateFunc) *QuotaResetApprovalChainNodeSelect {
	return qracnq.Select().Aggregate(fns...)
}

func (qracnq *QuotaResetApprovalChainNodeQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range qracnq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, qracnq); err != nil {
				return err
			}
		}
	}
	for _, f := range qracnq.ctx.Fields {
		if !quotaresetapprovalchainnode.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if qracnq.path != nil {
		prev, err := qracnq.path(ctx)
		if err != nil {
			return err
		}
		qracnq.sql = prev
	}
	return nil
}

func (qracnq *QuotaResetApprovalChainNodeQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*QuotaResetApprovalChainNode, error) {
	var (
		nodes = []*QuotaResetApprovalChainNode{}
		_spec = qracnq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*QuotaResetApprovalChainNode).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &QuotaResetApprovalChainNode{config: qracnq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, qracnq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (qracnq *QuotaResetApprovalChainNodeQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := qracnq.querySpec()
	_spec.Node.Columns = qracnq.ctx.Fields
	if len(qracnq.ctx.Fields) > 0 {
		_spec.Unique = qracnq.ctx.Unique != nil && *qracnq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, qracnq.driver, _spec)
}

func (qracnq *QuotaResetApprovalChainNodeQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(quotaresetapprovalchainnode.Table, quotaresetapprovalchainnode.Columns, sqlgraph.NewFieldSpec(quotaresetapprovalchainnode.FieldID, field.TypeInt))
	_spec.From = qracnq.sql
	if unique := qracnq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if qracnq.path != nil {
		_spec.Unique = true
	}
	if fields := qracnq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, quotaresetapprovalchainnode.FieldID)
		for i := range fields {
			if fields[i] != quotaresetapprovalchainnode.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := qracnq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := qracnq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := qracnq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := qracnq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (qracnq *QuotaResetApprovalChainNodeQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(qracnq.driver.Dialect())
	t1 := builder.Table(quotaresetapprovalchainnode.Table)
	columns := qracnq.ctx.Fields
	if len(columns) == 0 {
		columns = quotaresetapprovalchainnode.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if qracnq.sql != nil {
		selector = qracnq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if qracnq.ctx.Unique != nil && *qracnq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range qracnq.predicates {
		p(selector)
	}
	for _, p := range qracnq.order {
		p(selector)
	}
	if offset := qracnq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := qracnq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// QuotaResetApprovalChainNodeGroupBy is the group-by builder for QuotaResetApprovalChainNode entities.
type QuotaResetApprovalChainNodeGroupBy struct {
	selector
	build *QuotaResetApprovalChainNodeQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (qracngb *QuotaResetApprovalChainNodeGroupBy) Aggregate(fns ...AggregateFunc) *QuotaResetApprovalChainNodeGroupBy {
	qracngb.fns = append(qracngb.fns, fns...)
	return qracngb
}

// Scan applies the selector query and scans the result into the given value.
func (qracngb *QuotaResetApprovalChainNodeGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, qracngb.build.ctx, ent.OpQueryGroupBy)
	if err := qracngb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*QuotaResetApprovalChainNodeQuery, *QuotaResetApprovalChainNodeGroupBy](ctx, qracngb.build, qracngb, qracngb.build.inters, v)
}

func (qracngb *QuotaResetApprovalChainNodeGroupBy) sqlScan(ctx context.Context, root *QuotaResetApprovalChainNodeQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(qracngb.fns))
	for _, fn := range qracngb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*qracngb.flds)+len(qracngb.fns))
		for _, f := range *qracngb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*qracngb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := qracngb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// QuotaResetApprovalChainNodeSelect is the builder for selecting fields of QuotaResetApprovalChainNode entities.
type QuotaResetApprovalChainNodeSelect struct {
	*QuotaResetApprovalChainNodeQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (qracns *QuotaResetApprovalChainNodeSelect) Aggregate(fns ...AggregateFunc) *QuotaResetApprovalChainNodeSelect {
	qracns.fns = append(qracns.fns, fns...)
	return qracns
}

// Scan applies the selector query and scans the result into the given value.
func (qracns *QuotaResetApprovalChainNodeSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, qracns.ctx, ent.OpQuerySelect)
	if err := qracns.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*QuotaResetApprovalChainNodeQuery, *QuotaResetApprovalChainNodeSelect](ctx, qracns.QuotaResetApprovalChainNodeQuery, qracns, qracns.inters, v)
}

func (qracns *QuotaResetApprovalChainNodeSelect) sqlScan(ctx context.Context, root *QuotaResetApprovalChainNodeQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(qracns.fns))
	for _, fn := range qracns.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*qracns.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := qracns.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
