// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ai-efficiency/backend/ent/quotaresetnotificationsetting"
)

// QuotaResetNotificationSettingCreate is the builder for creating a QuotaResetNotificationSetting entity.
type QuotaResetNotificationSettingCreate struct {
	config
	mutation *QuotaResetNotificationSettingMutation
	hooks    []Hook
}

// SetEnabled sets the "enabled" field.
func (qrnsc *QuotaResetNotificationSettingCreate) SetEnabled(b bool) *QuotaResetNotificationSettingCreate {
	qrnsc.mutation.SetEnabled(b)
	return qrnsc
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (qrnsc *QuotaResetNotificationSettingCreate) SetNillableEnabled(b *bool) *QuotaResetNotificationSettingCreate {
	if b != nil {
		qrnsc.SetEnabled(*b)
	}
	return qrnsc
}

// SetChannelType sets the "channel_type" field.
func (qrnsc *QuotaResetNotificationSettingCreate) SetChannelType(qt quotaresetnotificationsetting.ChannelType) *QuotaResetNotificationSettingCreate {
	qrnsc.mutation.SetChannelType(qt)
	return qrnsc
}

// SetNillableChannelType sets the "channel_type" field if the given value is not nil.
func (qrnsc *QuotaResetNotificationSettingCreate) SetNillableChannelType(qt *quotaresetnotificationsetting.ChannelType) *QuotaResetNotificationSettingCreate {
	if qt != nil {
		qrnsc.SetChannelType(*qt)
	}
	return qrnsc
}

// SetChannelTypeConfigured sets the "channel_type_configured" field.
func (qrnsc *QuotaResetNotificationSettingCreate) SetChannelTypeConfigured(b bool) *QuotaResetNotificationSettingCreate {
	qrnsc.mutation.SetChannelTypeConfigured(b)
	return qrnsc
}

// SetNillableChannelTypeConfigured sets the "channel_type_configured" field if the given value is not nil.
func (qrnsc *QuotaResetNotificationSettingCreate) SetNillableChannelTypeConfigured(b *bool) *QuotaResetNotificationSettingCreate {
	if b != nil {
		qrnsc.SetChannelTypeConfigured(*b)
	}
	return qrnsc
}

// SetTemplateVersion sets the "template_version" field.
func (qrnsc *QuotaResetNotificationSettingCreate) SetTemplateVersion(i int) *QuotaResetNotificationSettingCreate {
	qrnsc.mutation.SetTemplateVersion(i)
	return qrnsc
}

// SetNillableTemplateVersion sets the "template_version" field if the given value is not nil.
func (qrnsc *QuotaResetNotificationSettingCreate) SetNillableTemplateVersion(i *int) *QuotaResetNotificationSettingCreate {
	if i != nil {
		qrnsc.SetTemplateVersion(*i)
	}
	return qrnsc
}

// SetURL sets the "url" field.
func (qrnsc *QuotaResetNotificationSettingCreate) SetURL(s string) *QuotaResetNotificationSettingCreate {
	qrnsc.mutation.SetURL(s)
	return qrnsc
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (qrnsc *QuotaResetNotificationSettingCreate) SetNillableURL(s *string) *QuotaResetNotificationSettingCreate {
	if s != nil {
		qrnsc.SetURL(*s)
	}
	return qrnsc
}

// SetAuthType sets the "auth_type" field.
func (qrnsc *QuotaResetNotificationSettingCreate) SetAuthType(qt quotaresetnotificationsetting.AuthType) *QuotaResetNotificationSettingCreate {
	qrnsc.mutation.SetAuthType(qt)
	return qrnsc
}

// SetNillableAuthType sets the "auth_type" field if the given value is not nil.
func (qrnsc *QuotaResetNotificationSettingCreate) SetNillableAuthType(qt *quotaresetnotificationsetting.AuthType) *QuotaResetNotificationSettingCreate {
	if qt != nil {
		qrnsc.SetAuthType(*qt)
	}
	return qrnsc
}

// SetCredentialID sets the "credential_id" field.
func (qrnsc *QuotaResetNotificationSettingCreate) SetCredentialID(i int) *QuotaResetNotificationSettingCreate {
	qrnsc.mutation.SetCredentialID(i)
	return qrnsc
}

// SetNillableCredentialID sets the "credential_id" field if the given value is not nil.
func (qrnsc *QuotaResetNotificationSettingCreate) SetNillableCredentialID(i *int) *QuotaResetNotificationSettingCreate {
	if i != nil {
		qrnsc.SetCredentialID(*i)
	}
	return qrnsc
}

// SetCreatedByUserID sets the "created_by_user_id" field.
func (qrnsc *QuotaResetNotificationSettingCreate) SetCreatedByUserID(i int) *QuotaResetNotificationSettingCreate {
	qrnsc.mutation.SetCreatedByUserID(i)
	return qrnsc
}

// SetNillableCreatedByUserID sets the "created_by_user_id" field if the given value is not nil.
func (qrnsc *QuotaResetNotificationSettingCreate) SetNillableCreatedByUserID(i *int) *QuotaResetNotificationSettingCreate {
	if i != nil {
		qrnsc.SetCreatedByUserID(*i)
	}
	return qrnsc
}

// SetUpdatedByUserID sets the "updated_by_user_id" field.
func (qrnsc *QuotaResetNotificationSettingCreate) SetUpdatedByUserID(i int) *QuotaResetNotificationSettingCreate {
	qrnsc.mutation.SetUpdatedByUserID(i)
	return qrnsc
}

// SetNillableUpdatedByUserID sets the "updated_by_user_id" field if the given value is not nil.
func (qrnsc *QuotaResetNotificationSettingCreate) SetNillableUpdatedByUserID(i *int) *QuotaResetNotificationSettingCreate {
	if i != nil {
		qrnsc.SetUpdatedByUserID(*i)
	}
	return qrnsc
}

// SetCreatedAt sets the "created_at" field.
func (qrnsc *QuotaResetNotificationSettingCreate) SetCreatedAt(t time.Time) *QuotaResetNotificationSettingCreate {
	qrnsc.mutation.SetCreatedAt(t)
	return qrnsc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (qrnsc *QuotaResetNotificationSettingCreate) SetNillableCreatedAt(t *time.Time) *QuotaResetNotificationSettingCreate {
	if t != nil {
		qrnsc.SetCreatedAt(*t)
	}
	return qrnsc
}

// SetUpdatedAt sets the "updated_at" field.
func (qrnsc *QuotaResetNotificationSettingCreate) SetUpdatedAt(t time.Time) *QuotaResetNotificationSettingCreate {
	qrnsc.mutation.SetUpdatedAt(t)
	return qrnsc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (qrnsc *QuotaResetNotificationSettingCreate) SetNillableUpdatedAt(t *time.Time) *QuotaResetNotificationSettingCreate {
	if t != nil {
		qrnsc.SetUpdatedAt(*t)
	}
	return qrnsc
}

// Mutation returns the QuotaResetNotificationSettingMutation object of the builder.
func (qrnsc *QuotaResetNotificationSettingCreate) Mutation() *QuotaResetNotificationSettingMutation {
	return qrnsc.mutation
}

// Save creates the QuotaResetNotificationSetting in the database.
func (qrnsc *QuotaResetNotificationSettingCreate) Save(ctx context.Context) (*QuotaResetNotificationSetting, error) {
	qrnsc.defaults()
	return withHooks(ctx, qrnsc.sqlSave, qrnsc.mutation, qrnsc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (qrnsc *QuotaResetNotificationSettingCreate) SaveX(ctx context.Context) *QuotaResetNotificationSetting {
	v, err := qrnsc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (qrnsc *QuotaResetNotificationSettingCreate) Exec(ctx context.Context) error {
	_, err := qrnsc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (qrnsc *QuotaResetNotificationSettingCreate) ExecX(ctx context.Context) {
	if err := qrnsc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (qrnsc *QuotaResetNotificationSettingCreate) defaults() {
	if _, ok := qrnsc.mutation.Enabled(); !ok {
		v := quotaresetnotificationsetting.DefaultEnabled
		qrnsc.mutation.SetEnabled(v)
	}
	if _, ok := qrnsc.mutation.ChannelType(); !ok {
		v := quotaresetnotificationsetting.DefaultChannelType
		qrnsc.mutation.SetChannelType(v)
	}
	if _, ok := qrnsc.mutation.ChannelTypeConfigured(); !ok {
		v := quotaresetnotificationsetting.DefaultChannelTypeConfigured
		qrnsc.mutation.SetChannelTypeConfigured(v)
	}
	if _, ok := qrnsc.mutation.TemplateVersion(); !ok {
		v := quotaresetnotificationsetting.DefaultTemplateVersion
		qrnsc.mutation.SetTemplateVersion(v)
	}
	if _, ok := qrnsc.mutation.URL(); !ok {
		v := quotaresetnotificationsetting.DefaultURL
		qrnsc.mutation.SetURL(v)
	}
	if _, ok := qrnsc.mutation.AuthType(); !ok {
		v := quotaresetnotificationsetting.DefaultAuthType
		qrnsc.mutation.SetAuthType(v)
	}
	if _, ok := qrnsc.mutation.CreatedByUserID(); !ok {
		v := quotaresetnotificationsetting.DefaultCreatedByUserID
		qrnsc.mutation.SetCreatedByUserID(v)
	}
	if _, ok := qrnsc.mutation.UpdatedByUserID(); !ok {
		v := quotaresetnotificationsetting.DefaultUpdatedByUserID
		qrnsc.mutation.SetUpdatedByUserID(v)
	}
	if _, ok := qrnsc.mutation.CreatedAt(); !ok {
		v := quotaresetnotificationsetting.DefaultCreatedAt()
		qrnsc.mutation.SetCreatedAt(v)
	}
	if _, ok := qrnsc.mutation.UpdatedAt(); !ok {
		v := quotaresetnotificationsetting.DefaultUpdatedAt()
		qrnsc.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (qrnsc *QuotaResetNotificationSettingCreate) check() error {
	if _, ok := qrnsc.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "QuotaResetNotificationSetting.enabled"`)}
	}
	if _, ok := qrnsc.mutation.ChannelType(); !ok {
		return &ValidationError{Name: "channel_type", err: errors.New(`ent: missing required field "QuotaResetNotificationSetting.channel_type"`)}
	}
	if v, ok := qrnsc.mutation.ChannelType(); ok {
		if err := quotaresetnotificationsetting.ChannelTypeValidator(v); err != nil {
			return &ValidationError{Name: "channel_type", err: fmt.Errorf(`ent: validator failed for field "QuotaResetNotificationSetting.channel_type": %w`, err)}
		}
	}
	if _, ok := qrnsc.mutation.ChannelTypeConfigured(); !ok {
		return &ValidationError{Name: "channel_type_configured", err: errors.New(`ent: missing required field "QuotaResetNotificationSetting.channel_type_configured"`)}
	}
	if _, ok := qrnsc.mutation.TemplateVersion(); !ok {
		return &ValidationError{Name: "template_version", err: errors.New(`ent: missing required field "QuotaResetNotificationSetting.template_version"`)}
	}
	if _, ok := qrnsc.mutation.URL(); !ok {
		return &ValidationError{Name: "url", err: errors.New(`ent: missing required field "QuotaResetNotificationSetting.url"`)}
	}
	if _, ok := qrnsc.mutation.AuthType(); !ok {
		return &ValidationError{Name: "auth_type", err: errors.New(`ent: missing required field "QuotaResetNotificationSetting.auth_type"`)}
	}
	if v, ok := qrnsc.mutation.AuthType(); ok {
		if err := quotaresetnotificationsetting.AuthTypeValidator(v); err != nil {
			return &ValidationError{Name: "auth_type", err: fmt.Errorf(`ent: validator failed for field "QuotaResetNotificationSetting.auth_type": %w`, err)}
		}
	}
	if _, ok := qrnsc.mutation.CreatedByUserID(); !ok {
		return &ValidationError{Name: "created_by_user_id", err: errors.New(`ent: missing required field "QuotaResetNotificationSetting.created_by_user_id"`)}
	}
	if _, ok := qrnsc.mutation.UpdatedByUserID(); !ok {
		return &ValidationError{Name: "updated_by_user_id", err: errors.New(`ent: missing required field "QuotaResetNotificationSetting.updated_by_user_id"`)}
	}
	if _, ok := qrnsc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "QuotaResetNotificationSetting.created_at"`)}
	}
	if _, ok := qrnsc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "QuotaResetNotificationSetting.updated_at"`)}
	}
	return nil
}

func (qrnsc *QuotaResetNotificationSettingCreate) sqlSave(ctx context.Context) (*QuotaResetNotificationSetting, error) {
	if err := qrnsc.check(); err != nil {
		return nil, err
	}
	_node, _spec := qrnsc.createSpec()
	if err := sqlgraph.CreateNode(ctx, qrnsc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	qrnsc.mutation.id = &_node.ID
	qrnsc.mutation.done = true
	return _node, nil
}

func (qrnsc *QuotaResetNotificationSettingCreate) createSpec() (*QuotaResetNotificationSetting, *sqlgraph.CreateSpec) {
	var (
		_node = &QuotaResetNotificationSetting{config: qrnsc.config}
		_spec = sqlgraph.NewCreateSpec(quotaresetnotificationsetting.Table, sqlgraph.NewFieldSpec(quotaresetnotificationsetting.FieldID, field.TypeInt))
	)
	if value, ok := qrnsc.mutation.Enabled(); ok {
		_spec.SetField(quotaresetnotificationsetting.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	if value, ok := qrnsc.mutation.ChannelType(); ok {
		_spec.SetField(quotaresetnotificationsetting.FieldChannelType, field.TypeEnum, value)
		_node.ChannelType = value
	}
	if value, ok := qrnsc.mutation.ChannelTypeConfigured(); ok {
		_spec.SetField(quotaresetnotificationsetting.FieldChannelTypeConfigured, field.TypeBool, value)
		_node.ChannelTypeConfigured = value
	}
	if value, ok := qrnsc.mutation.TemplateVersion(); ok {
		_spec.SetField(quotaresetnotificationsetting.FieldTemplateVersion, field.TypeInt, value)
		_node.TemplateVersion = value
	}
	if value, ok := qrnsc.mutation.URL(); ok {
		_spec.SetField(quotaresetnotificationsetting.FieldURL, field.TypeString, value)
		_node.URL = value
	}
	if value, ok := qrnsc.mutation.AuthType(); ok {
		_spec.SetField(quotaresetnotificationsetting.FieldAuthType, field.TypeEnum, value)
		_node.AuthType = value
	}
	if value, ok := qrnsc.mutation.CredentialID(); ok {
		_spec.SetField(quotaresetnotificationsetting.FieldCredentialID, field.TypeInt, value)
		_node.CredentialID = &value
	}
	if value, ok := qrnsc.mutation.CreatedByUserID(); ok {
		_spec.SetField(quotaresetnotificationsetting.FieldCreatedByUserID, field.TypeInt, value)
		_node.CreatedByUserID = value
	}
	if value, ok := qrnsc.mutation.UpdatedByUserID(); ok {
		_spec.SetField(quotaresetnotificationsetting.FieldUpdatedByUserID, field.TypeInt, value)
		_node.UpdatedByUserID = value
	}
	if value, ok := qrnsc.mutation.CreatedAt(); ok {
		_spec.SetField(quotaresetnotificationsetting.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := qrnsc.mutation.UpdatedAt(); ok {
		_spec.SetField(quotaresetnotificationsetting.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// QuotaResetNotificationSettingCreateBulk is the builder for creating many QuotaResetNotificationSetting entities in bulk.
type QuotaResetNotificationSettingCreateBulk struct {
	config
	err      error
	builders []*QuotaResetNotificationSettingCreate
}

// Save creates the QuotaResetNotificationSetting entities in the database.
func (qrnscb *QuotaResetNotificationSettingCreateBulk) Save(ctx context.Context) ([]*QuotaResetNotificationSetting, error) {
	if qrnscb.err != nil {
		return nil, qrnscb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(qrnscb.builders))
	nodes := make([]*QuotaResetNotificationSetting, len(qrnscb.builders))
	mutators := make([]Mutator, len(qrnscb.builders))
	for i := range qrnscb.builders {
		func(i int, root context.Context) {
			builder := qrnscb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*QuotaResetNotificationSettingMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, qrnscb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, qrnscb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, qrnscb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (qrnscb *QuotaResetNotificationSettingCreateBulk) SaveX(ctx context.Context) []*QuotaResetNotificationSetting {
	v, err := qrnscb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (qrnscb *QuotaResetNotificationSettingCreateBulk) Exec(ctx context.Context) error {
	_, err := qrnscb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (qrnscb *QuotaResetNotificationSettingCreateBulk) ExecX(ctx context.Context) {
	if err := qrnscb.Exec(ctx); err != nil {
		panic(err)
	}
}
