// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ai-efficiency/backend/ent/quotaresetapprovalchain"
)

// QuotaResetApprovalChainCreate is the builder for creating a QuotaResetApprovalChain entity.
type QuotaResetApprovalChainCreate struct {
	config
	mutation *QuotaResetApprovalChainMutation
	hooks    []Hook
}

// SetProviderID sets the "provider_id" field.
func (qracc *QuotaResetApprovalChainCreate) SetProviderID(i int) *QuotaResetApprovalChainCreate {
	qracc.mutation.SetProviderID(i)
	return qracc
}

// SetGroupID sets the "group_id" field.
func (qracc *QuotaResetApprovalChainCreate) SetGroupID(s string) *QuotaResetApprovalChainCreate {
	qracc.mutation.SetGroupID(s)
	return qracc
}

// SetGroupName sets the "group_name" field.
func (qracc *QuotaResetApprovalChainCreate) SetGroupName(s string) *QuotaResetApprovalChainCreate {
	qracc.mutation.SetGroupName(s)
	return qracc
}

// SetNillableGroupName sets the "group_name" field if the given value is not nil.
func (qracc *QuotaResetApprovalChainCreate) SetNillableGroupName(s *string) *QuotaResetApprovalChainCreate {
	if s != nil {
		qracc.SetGroupName(*s)
	}
	return qracc
}

// SetDepartmentChain sets the "department_chain" field.
func (qracc *QuotaResetApprovalChainCreate) SetDepartmentChain(m []map[string]interface{}) *QuotaResetApprovalChainCreate {
	qracc.mutation.SetDepartmentChain(m)
	return qracc
}

// SetEnabled sets the "enabled" field.
func (qracc *QuotaResetApprovalChainCreate) SetEnabled(b bool) *QuotaResetApprovalChainCreate {
	qracc.mutation.SetEnabled(b)
	return qracc
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (qracc *QuotaResetApprovalChainCreate) SetNillableEnabled(b *bool) *QuotaResetApprovalChainCreate {
	if b != nil {
		qracc.SetEnabled(*b)
	}
	return qracc
}

// SetCreatedByUserID sets the "created_by_user_id" field.
func (qracc *QuotaResetApprovalChainCreate) SetCreatedByUserID(i int) *QuotaResetApprovalChainCreate {
	qracc.mutation.SetCreatedByUserID(i)
	return qracc
}

// SetNillableCreatedByUserID sets the "created_by_user_id" field if the given value is not nil.
func (qracc *QuotaResetApprovalChainCreate) SetNillableCreatedByUserID(i *int) *QuotaResetApprovalChainCreate {
	if i != nil {
		qracc.SetCreatedByUserID(*i)
	}
	return qracc
}

// SetUpdatedByUserID sets the "updated_by_user_id" field.
func (qracc *QuotaResetApprovalChainCreate) SetUpdatedByUserID(i int) *QuotaResetApprovalChainCreate {
	qracc.mutation.SetUpdatedByUserID(i)
	return qracc
}

// SetNillableUpdatedByUserID sets the "updated_by_user_id" field if the given value is not nil.
func (qracc *QuotaResetApprovalChainCreate) SetNillableUpdatedByUserID(i *int) *QuotaResetApprovalChainCreate {
	if i != nil {
		qracc.SetUpdatedByUserID(*i)
	}
	return qracc
}

// SetCreatedAt sets the "created_at" field.
func (qracc *QuotaResetApprovalChainCreate) SetCreatedAt(t time.Time) *QuotaResetApprovalChainCreate {
	qracc.mutation.SetCreatedAt(t)
	return qracc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (qracc *QuotaResetApprovalChainCreate) SetNillableCreatedAt(t *time.Time) *QuotaResetApprovalChainCreate {
	if t != nil {
		qracc.SetCreatedAt(*t)
	}
	return qracc
}

// SetUpdatedAt sets the "updated_at" field.
func (qracc *QuotaResetApprovalChainCreate) SetUpdatedAt(t time.Time) *QuotaResetApprovalChainCreate {
	qracc.mutation.SetUpdatedAt(t)
	return qracc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (qracc *QuotaResetApprovalChainCreate) SetNillableUpdatedAt(t *time.Time) *QuotaResetApprovalChainCreate {
	if t != nil {
		qracc.SetUpdatedAt(*t)
	}
	return qracc
}

// Mutation returns the QuotaResetApprovalChainMutation object of the builder.
func (qracc *QuotaResetApprovalChainCreate) Mutation() *QuotaResetApprovalChainMutation {
	return qracc.mutation
}

// Save creates the QuotaResetApprovalChain in the database.
func (qracc *QuotaResetApprovalChainCreate) Save(ctx context.Context) (*QuotaResetApprovalChain, error) {
	qracc.defaults()
	return withHooks(ctx, qracc.sqlSave, qracc.mutation, qracc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (qracc *QuotaResetApprovalChainCreate) SaveX(ctx context.Context) *QuotaResetApprovalChain {
	v, err := qracc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (qracc *QuotaResetApprovalChainCreate) Exec(ctx context.Context) error {
	_, err := qracc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (qracc *QuotaResetApprovalChainCreate) ExecX(ctx context.Context) {
	if err := qracc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (qracc *QuotaResetApprovalChainCreate) defaults() {
	if _, ok := qracc.mutation.GroupName(); !ok {
		v := quotaresetapprovalchain.DefaultGroupName
		qracc.mutation.SetGroupName(v)
	}
	if _, ok := qracc.mutation.DepartmentChain(); !ok {
		v := quotaresetapprovalchain.DefaultDepartmentChain
		qracc.mutation.SetDepartmentChain(v)
	}
	if _, ok := qracc.mutation.Enabled(); !ok {
		v := quotaresetapprovalchain.DefaultEnabled
		qracc.mutation.SetEnabled(v)
	}
	if _, ok := qracc.mutation.CreatedByUserID(); !ok {
		v := quotaresetapprovalchain.DefaultCreatedByUserID
		qracc.mutation.SetCreatedByUserID(v)
	}
	if _, ok := qracc.mutation.UpdatedByUserID(); !ok {
		v := quotaresetapprovalchain.DefaultUpdatedByUserID
		qracc.mutation.SetUpdatedByUserID(v)
	}
	if _, ok := qracc.mutation.CreatedAt(); !ok {
		v := quotaresetapprovalchain.DefaultCreatedAt()
		qracc.mutation.SetCreatedAt(v)
	}
	if _, ok := qracc.mutation.UpdatedAt(); !ok {
		v := quotaresetapprovalchain.DefaultUpdatedAt()
		qracc.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (qracc *QuotaResetApprovalChainCreate) check() error {
	if _, ok := qracc.mutation.ProviderID(); !ok {
		return &ValidationError{Name: "provider_id", err: errors.New(`ent: missing required field "QuotaResetApprovalChain.provider_id"`)}
	}
	if _, ok := qracc.mutation.GroupID(); !ok {
		return &ValidationError{Name: "group_id", err: errors.New(`ent: missing required field "QuotaResetApprovalChain.group_id"`)}
	}
	if v, ok := qracc.mutation.GroupID(); ok {
		if err := quotaresetapprovalchain.GroupIDValidator(v); err != nil {
			return &ValidationError{Name: "group_id", err: fmt.Errorf(`ent: validator failed for field "QuotaResetApprovalChain.group_id": %w`, err)}
		}
	}
	if _, ok := qracc.mutation.GroupName(); !ok {
		return &ValidationError{Name: "group_name", err: errors.New(`ent: missing required field "QuotaResetApprovalChain.group_name"`)}
	}
	if _, ok := qracc.mutation.DepartmentChain(); !ok {
		return &ValidationError{Name: "department_chain", err: errors.New(`ent: missing required field "QuotaResetApprovalChain.department_chain"`)}
	}
	if _, ok := qracc.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "QuotaResetApprovalChain.enabled"`)}
	}
	if _, ok := qracc.mutation.CreatedByUserID(); !ok {
		return &ValidationError{Name: "created_by_user_id", err: errors.New(`ent: missing required field "QuotaResetApprovalChain.created_by_user_id"`)}
	}
	if _, ok := qracc.mutation.UpdatedByUserID(); !ok {
		return &ValidationError{Name: "updated_by_user_id", err: errors.New(`ent: missing required field "QuotaResetApprovalChain.updated_by_user_id"`)}
	}
	if _, ok := qracc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "QuotaResetApprovalChain.created_at"`)}
	}
	if _, ok := qracc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "QuotaResetApprovalChain.updated_at"`)}
	}
	return nil
}

func (qracc *QuotaResetApprovalChainCreate) sqlSave(ctx context.Context) (*QuotaResetApprovalChain, error) {
	if err := qracc.check(); err != nil {
		return nil, err
	}
	_node, _spec := qracc.createSpec()
	if err := sqlgraph.CreateNode(ctx, qracc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	qracc.mutation.id = &_node.ID
	qracc.mutation.done = true
	return _node, nil
}

func (qracc *QuotaResetApprovalChainCreate) createSpec() (*QuotaResetApprovalChain, *sqlgraph.CreateSpec) {
	var (
		_node = &QuotaResetApprovalChain{config: qracc.config}
		_spec = sqlgraph.NewCreateSpec(quotaresetapprovalchain.Table, sqlgraph.NewFieldSpec(quotaresetapprovalchain.FieldID, field.TypeInt))
	)
	if value, ok := qracc.mutation.ProviderID(); ok {
		_spec.SetField(quotaresetapprovalchain.FieldProviderID, field.TypeInt, value)
		_node.ProviderID = value
	}
	if value, ok := qracc.mutation.GroupID(); ok {
		_spec.SetField(quotaresetapprovalchain.FieldGroupID, field.TypeString, value)
		_node.GroupID = value
	}
	if value, ok := qracc.mutation.GroupName(); ok {
		_spec.SetField(quotaresetapprovalchain.FieldGroupName, field.TypeString, value)
		_node.GroupName = value
	}
	if value, ok := qracc.mutation.DepartmentChain(); ok {
		_spec.SetField(quotaresetapprovalchain.FieldDepartmentChain, field.TypeJSON, value)
		_node.DepartmentChain = value
	}
	if value, ok := qracc.mutation.Enabled(); ok {
		_spec.SetField(quotaresetapprovalchain.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	if value, ok := qracc.mutation.CreatedByUserID(); ok {
		_spec.SetField(quotaresetapprovalchain.FieldCreatedByUserID, field.TypeInt, value)
		_node.CreatedByUserID = value
	}
	if value, ok := qracc.mutation.UpdatedByUserID(); ok {
		_spec.SetField(quotaresetapprovalchain.FieldUpdatedByUserID, field.TypeInt, value)
		_node.UpdatedByUserID = value
	}
	if value, ok := qracc.mutation.CreatedAt(); ok {
		_spec.SetField(quotaresetapprovalchain.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := qracc.mutation.UpdatedAt(); ok {
		_spec.SetField(quotaresetapprovalchain.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// QuotaResetApprovalChainCreateBulk is the builder for creating many QuotaResetApprovalChain entities in bulk.
type QuotaResetApprovalChainCreateBulk struct {
	config
	err      error
	builders []*QuotaResetApprovalChainCreate
}

// Save creates the QuotaResetApprovalChain entities in the database.
func (qraccb *QuotaResetApprovalChainCreateBulk) Save(ctx context.Context) ([]*QuotaResetApprovalChain, error) {
	if qraccb.err != nil {
		return nil, qraccb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(qraccb.builders))
	nodes := make([]*QuotaResetApprovalChain, len(qraccb.builders))
	mutators := make([]Mutator, len(qraccb.builders))
	for i := range qraccb.builders {
		func(i int, root context.Context) {
			builder := qraccb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*QuotaResetApprovalChainMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, qraccb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, qraccb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, qraccb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (qraccb *QuotaResetApprovalChainCreateBulk) SaveX(ctx context.Context) []*QuotaResetApprovalChain {
	v, err := qraccb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (qraccb *QuotaResetApprovalChainCreateBulk) Exec(ctx context.Context) error {
	_, err := qraccb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (qraccb *QuotaResetApprovalChainCreateBulk) ExecX(ctx context.Context) {
	if err := qraccb.Exec(ctx); err != nil {
		panic(err)
	}
}
