// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/ai-efficiency/backend/ent/relationshipoperation"
	"github.com/ai-efficiency/backend/ent/relationshipoperationmapping"
	"github.com/ai-efficiency/backend/ent/relaygroupmapping"
)

// RelationshipOperationMapping is the model entity for the RelationshipOperationMapping schema.
type RelationshipOperationMapping struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// OperationID holds the value of the "operation_id" field.
	OperationID int `json:"operation_id,omitempty"`
	// MappingID holds the value of the "mapping_id" field.
	MappingID int `json:"mapping_id,omitempty"`
	// Role holds the value of the "role" field.
	Role relationshipoperationmapping.Role `json:"role,omitempty"`
	// BaselineRevision holds the value of the "baseline_revision" field.
	BaselineRevision int64 `json:"baseline_revision,omitempty"`
	// BaselineSnapshot holds the value of the "baseline_snapshot" field.
	BaselineSnapshot map[string]interface{} `json:"baseline_snapshot,omitempty"`
	// Active holds the value of the "active" field.
	Active bool `json:"active,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// ReleasedAt holds the value of the "released_at" field.
	ReleasedAt *time.Time `json:"released_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the RelationshipOperationMappingQuery when eager-loading is set.
	Edges        RelationshipOperationMappingEdges `json:"edges"`
	selectValues sql.SelectValues
}

// RelationshipOperationMappingEdges holds the relations/edges for other nodes in the graph.
type RelationshipOperationMappingEdges struct {
	// Operation holds the value of the operation edge.
	Operation *RelationshipOperation `json:"operation,omitempty"`
	// Mapping holds the value of the mapping edge.
	Mapping *RelayGroupMapping `json:"mapping,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// OperationOrErr returns the Operation value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e RelationshipOperationMappingEdges) OperationOrErr() (*RelationshipOperation, error) {
	if e.Operation != nil {
		return e.Operation, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: relationshipoperation.Label}
	}
	return nil, &NotLoadedError{edge: "operation"}
}

// MappingOrErr returns the Mapping value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e RelationshipOperationMappingEdges) MappingOrErr() (*RelayGroupMapping, error) {
	if e.Mapping != nil {
		return e.Mapping, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: relaygroupmapping.Label}
	}
	return nil, &NotLoadedError{edge: "mapping"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*RelationshipOperationMapping) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case relationshipoperationmapping.FieldBaselineSnapshot:
			values[i] = new([]byte)
		case relationshipoperationmapping.FieldActive:
			values[i] = new(sql.NullBool)
		case relationshipoperationmapping.FieldID, relationshipoperationmapping.FieldOperationID, relationshipoperationmapping.FieldMappingID, relationshipoperationmapping.FieldBaselineRevision:
			values[i] = new(sql.NullInt64)
		case relationshipoperationmapping.FieldRole:
			values[i] = new(sql.NullString)
		case relationshipoperationmapping.FieldCreatedAt, relationshipoperationmapping.FieldReleasedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the RelationshipOperationMapping fields.
func (rom *RelationshipOperationMapping) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case relationshipoperationmapping.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			rom.ID = int(value.Int64)
		case relationshipoperationmapping.FieldOperationID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field operation_id", values[i])
			} else if value.Valid {
				rom.OperationID = int(value.Int64)
			}
		case relationshipoperationmapping.FieldMappingID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field mapping_id", values[i])
			} else if value.Valid {
				rom.MappingID = int(value.Int64)
			}
		case relationshipoperationmapping.FieldRole:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field role", values[i])
			} else if value.Valid {
				rom.Role = relationshipoperationmapping.Role(value.String)
			}
		case relationshipoperationmapping.FieldBaselineRevision:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field baseline_revision", values[i])
			} else if value.Valid {
				rom.BaselineRevision = value.Int64
			}
		case relationshipoperationmapping.FieldBaselineSnapshot:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field baseline_snapshot", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &rom.BaselineSnapshot); err != nil {
					return fmt.Errorf("unmarshal field baseline_snapshot: %w", err)
				}
			}
		case relationshipoperationmapping.FieldActive:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field active", values[i])
			} else if value.Valid {
				rom.Active = value.Bool
			}
		case relationshipoperationmapping.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				rom.CreatedAt = value.Time
			}
		case relationshipoperationmapping.FieldReleasedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field released_at", values[i])
			} else if value.Valid {
				rom.ReleasedAt = new(time.Time)
				*rom.ReleasedAt = value.Time
			}
		default:
			rom.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the RelationshipOperationMapping.
// This includes values selected through modifiers, order, etc.
func (rom *RelationshipOperationMapping) Value(name string) (ent.Value, error) {
	return rom.selectValues.Get(name)
}

// QueryOperation queries the "operation" edge of the RelationshipOperationMapping entity.
func (rom *RelationshipOperationMapping) QueryOperation() *RelationshipOperationQuery {
	return NewRelationshipOperationMappingClient(rom.config).QueryOperation(rom)
}

// QueryMapping queries the "mapping" edge of the RelationshipOperationMapping entity.
func (rom *RelationshipOperationMapping) QueryMapping() *RelayGroupMappingQuery {
	return NewRelationshipOperationMappingClient(rom.config).QueryMapping(rom)
}

// Update returns a builder for updating this RelationshipOperationMapping.
// Note that you need to call RelationshipOperationMapping.Unwrap() before calling this method if this RelationshipOperationMapping
// was returned from a transaction, and the transaction was committed or rolled back.
func (rom *RelationshipOperationMapping) Update() *RelationshipOperationMappingUpdateOne {
	return NewRelationshipOperationMappingClient(rom.config).UpdateOne(rom)
}

// Unwrap unwraps the RelationshipOperationMapping entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (rom *RelationshipOperationMapping) Unwrap() *RelationshipOperationMapping {
	_tx, ok := rom.config.driver.(*txDriver)
	if !ok {
		panic("ent: RelationshipOperationMapping is not a transactional entity")
	}
	rom.config.driver = _tx.drv
	return rom
}

// String implements the fmt.Stringer.
func (rom *RelationshipOperationMapping) String() string {
	var builder strings.Builder
	builder.WriteString("RelationshipOperationMapping(")
	builder.WriteString(fmt.Sprintf("id=%v, ", rom.ID))
	builder.WriteString("operation_id=")
	builder.WriteString(fmt.Sprintf("%v", rom.OperationID))
	builder.WriteString(", ")
	builder.WriteString("mapping_id=")
	builder.WriteString(fmt.Sprintf("%v", rom.MappingID))
	builder.WriteString(", ")
	builder.WriteString("role=")
	builder.WriteString(fmt.Sprintf("%v", rom.Role))
	builder.WriteString(", ")
	builder.WriteString("baseline_revision=")
	builder.WriteString(fmt.Sprintf("%v", rom.BaselineRevision))
	builder.WriteString(", ")
	builder.WriteString("baseline_snapshot=")
	builder.WriteString(fmt.Sprintf("%v", rom.BaselineSnapshot))
	builder.WriteString(", ")
	builder.WriteString("active=")
	builder.WriteString(fmt.Sprintf("%v", rom.Active))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(rom.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := rom.ReleasedAt; v != nil {
		builder.WriteString("released_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// RelationshipOperationMappings is a parsable slice of RelationshipOperationMapping.
type RelationshipOperationMappings []*RelationshipOperationMapping
