// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/ai-efficiency/backend/ent/repoconfig"
	"github.com/ai-efficiency/backend/ent/session"
	"github.com/ai-efficiency/backend/ent/user"
	"github.com/google/uuid"
)

// Session is the model entity for the Session schema.
type Session struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Branch holds the value of the "branch" field.
	Branch string `json:"branch,omitempty"`
	// RelayUserID holds the value of the "relay_user_id" field.
	RelayUserID *int `json:"relay_user_id,omitempty"`
	// RelayAPIKeyID holds the value of the "relay_api_key_id" field.
	RelayAPIKeyID *int `json:"relay_api_key_id,omitempty"`
	// ProviderName holds the value of the "provider_name" field.
	ProviderName *string `json:"provider_name,omitempty"`
	// ToolConfigs holds the value of the "tool_configs" field.
	ToolConfigs []map[string]interface{} `json:"tool_configs,omitempty"`
	// StartedAt holds the value of the "started_at" field.
	StartedAt time.Time `json:"started_at,omitempty"`
	// EndedAt holds the value of the "ended_at" field.
	EndedAt *time.Time `json:"ended_at,omitempty"`
	// ToolInvocations holds the value of the "tool_invocations" field.
	ToolInvocations []map[string]interface{} `json:"tool_invocations,omitempty"`
	// Status holds the value of the "status" field.
	Status session.Status `json:"status,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the SessionQuery when eager-loading is set.
	Edges                SessionEdges `json:"edges"`
	repo_config_sessions *int
	user_sessions        *int
	selectValues         sql.SelectValues
}

// SessionEdges holds the relations/edges for other nodes in the graph.
type SessionEdges struct {
	// RepoConfig holds the value of the repo_config edge.
	RepoConfig *RepoConfig `json:"repo_config,omitempty"`
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// RepoConfigOrErr returns the RepoConfig value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SessionEdges) RepoConfigOrErr() (*RepoConfig, error) {
	if e.RepoConfig != nil {
		return e.RepoConfig, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: repoconfig.Label}
	}
	return nil, &NotLoadedError{edge: "repo_config"}
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SessionEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Session) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case session.FieldToolConfigs, session.FieldToolInvocations:
			values[i] = new([]byte)
		case session.FieldRelayUserID, session.FieldRelayAPIKeyID:
			values[i] = new(sql.NullInt64)
		case session.FieldBranch, session.FieldProviderName, session.FieldStatus:
			values[i] = new(sql.NullString)
		case session.FieldStartedAt, session.FieldEndedAt, session.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case session.FieldID:
			values[i] = new(uuid.UUID)
		case session.ForeignKeys[0]: // repo_config_sessions
			values[i] = new(sql.NullInt64)
		case session.ForeignKeys[1]: // user_sessions
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Session fields.
func (s *Session) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case session.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				s.ID = *value
			}
		case session.FieldBranch:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field branch", values[i])
			} else if value.Valid {
				s.Branch = value.String
			}
		case session.FieldRelayUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field relay_user_id", values[i])
			} else if value.Valid {
				s.RelayUserID = new(int)
				*s.RelayUserID = int(value.Int64)
			}
		case session.FieldRelayAPIKeyID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field relay_api_key_id", values[i])
			} else if value.Valid {
				s.RelayAPIKeyID = new(int)
				*s.RelayAPIKeyID = int(value.Int64)
			}
		case session.FieldProviderName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field provider_name", values[i])
			} else if value.Valid {
				s.ProviderName = new(string)
				*s.ProviderName = value.String
			}
		case session.FieldToolConfigs:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field tool_configs", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &s.ToolConfigs); err != nil {
					return fmt.Errorf("unmarshal field tool_configs: %w", err)
				}
			}
		case session.FieldStartedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field started_at", values[i])
			} else if value.Valid {
				s.StartedAt = value.Time
			}
		case session.FieldEndedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field ended_at", values[i])
			} else if value.Valid {
				s.EndedAt = new(time.Time)
				*s.EndedAt = value.Time
			}
		case session.FieldToolInvocations:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field tool_invocations", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &s.ToolInvocations); err != nil {
					return fmt.Errorf("unmarshal field tool_invocations: %w", err)
				}
			}
		case session.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				s.Status = session.Status(value.String)
			}
		case session.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				s.CreatedAt = value.Time
			}
		case session.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field repo_config_sessions", value)
			} else if value.Valid {
				s.repo_config_sessions = new(int)
				*s.repo_config_sessions = int(value.Int64)
			}
		case session.ForeignKeys[1]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field user_sessions", value)
			} else if value.Valid {
				s.user_sessions = new(int)
				*s.user_sessions = int(value.Int64)
			}
		default:
			s.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Session.
// This includes values selected through modifiers, order, etc.
func (s *Session) Value(name string) (ent.Value, error) {
	return s.selectValues.Get(name)
}

// QueryRepoConfig queries the "repo_config" edge of the Session entity.
func (s *Session) QueryRepoConfig() *RepoConfigQuery {
	return NewSessionClient(s.config).QueryRepoConfig(s)
}

// QueryUser queries the "user" edge of the Session entity.
func (s *Session) QueryUser() *UserQuery {
	return NewSessionClient(s.config).QueryUser(s)
}

// Update returns a builder for updating this Session.
// Note that you need to call Session.Unwrap() before calling this method if this Session
// was returned from a transaction, and the transaction was committed or rolled back.
func (s *Session) Update() *SessionUpdateOne {
	return NewSessionClient(s.config).UpdateOne(s)
}

// Unwrap unwraps the Session entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (s *Session) Unwrap() *Session {
	_tx, ok := s.config.driver.(*txDriver)
	if !ok {
		panic("ent: Session is not a transactional entity")
	}
	s.config.driver = _tx.drv
	return s
}

// String implements the fmt.Stringer.
func (s *Session) String() string {
	var builder strings.Builder
	builder.WriteString("Session(")
	builder.WriteString(fmt.Sprintf("id=%v, ", s.ID))
	builder.WriteString("branch=")
	builder.WriteString(s.Branch)
	builder.WriteString(", ")
	if v := s.RelayUserID; v != nil {
		builder.WriteString("relay_user_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := s.RelayAPIKeyID; v != nil {
		builder.WriteString("relay_api_key_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := s.ProviderName; v != nil {
		builder.WriteString("provider_name=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("tool_configs=")
	builder.WriteString(fmt.Sprintf("%v", s.ToolConfigs))
	builder.WriteString(", ")
	builder.WriteString("started_at=")
	builder.WriteString(s.StartedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := s.EndedAt; v != nil {
		builder.WriteString("ended_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("tool_invocations=")
	builder.WriteString(fmt.Sprintf("%v", s.ToolInvocations))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", s.Status))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(s.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Sessions is a parsable slice of Session.
type Sessions []*Session
