// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ai-efficiency/backend/ent/agentmetadataevent"
	"github.com/ai-efficiency/backend/ent/commitcheckpoint"
	"github.com/ai-efficiency/backend/ent/commitrewrite"
	"github.com/ai-efficiency/backend/ent/predicate"
	"github.com/ai-efficiency/backend/ent/repoconfig"
	"github.com/ai-efficiency/backend/ent/session"
	"github.com/ai-efficiency/backend/ent/sessionworkspace"
	"github.com/ai-efficiency/backend/ent/user"
	"github.com/google/uuid"
)

// SessionQuery is the builder for querying Session entities.
type SessionQuery struct {
	config
	ctx                     *QueryContext
	order                   []session.OrderOption
	inters                  []Interceptor
	predicates              []predicate.Session
	withRepoConfig          *RepoConfigQuery
	withUser                *UserQuery
	withSessionWorkspaces   *SessionWorkspaceQuery
	withAgentMetadataEvents *AgentMetadataEventQuery
	withCommitCheckpoints   *CommitCheckpointQuery
	withCommitRewrites      *CommitRewriteQuery
	withFKs                 bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the SessionQuery builder.
func (sq *SessionQuery) Where(ps ...predicate.Session) *SessionQuery {
	sq.predicates = append(sq.predicates, ps...)
	return sq
}

// Limit the number of records to be returned by this query.
func (sq *SessionQuery) Limit(limit int) *SessionQuery {
	sq.ctx.Limit = &limit
	return sq
}

// Offset to start from.
func (sq *SessionQuery) Offset(offset int) *SessionQuery {
	sq.ctx.Offset = &offset
	return sq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (sq *SessionQuery) Unique(unique bool) *SessionQuery {
	sq.ctx.Unique = &unique
	return sq
}

// Order specifies how the records should be ordered.
func (sq *SessionQuery) Order(o ...session.OrderOption) *SessionQuery {
	sq.order = append(sq.order, o...)
	return sq
}

// QueryRepoConfig chains the current query on the "repo_config" edge.
func (sq *SessionQuery) QueryRepoConfig() *RepoConfigQuery {
	query := (&RepoConfigClient{config: sq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := sq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := sq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(session.Table, session.FieldID, selector),
			sqlgraph.To(repoconfig.Table, repoconfig.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, session.RepoConfigTable, session.RepoConfigColumn),
		)
		fromU = sqlgraph.SetNeighbors(sq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryUser chains the current query on the "user" edge.
func (sq *SessionQuery) QueryUser() *UserQuery {
	query := (&UserClient{config: sq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := sq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := sq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(session.Table, session.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, session.UserTable, session.UserColumn),
		)
		fromU = sqlgraph.SetNeighbors(sq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QuerySessionWorkspaces chains the current query on the "session_workspaces" edge.
func (sq *SessionQuery) QuerySessionWorkspaces() *SessionWorkspaceQuery {
	query := (&SessionWorkspaceClient{config: sq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := sq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := sq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(session.Table, session.FieldID, selector),
			sqlgraph.To(sessionworkspace.Table, sessionworkspace.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, session.SessionWorkspacesTable, session.SessionWorkspacesColumn),
		)
		fromU = sqlgraph.SetNeighbors(sq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryAgentMetadataEvents chains the current query on the "agent_metadata_events" edge.
func (sq *SessionQuery) QueryAgentMetadataEvents() *AgentMetadataEventQuery {
	query := (&AgentMetadataEventClient{config: sq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := sq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := sq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(session.Table, session.FieldID, selector),
			sqlgraph.To(agentmetadataevent.Table, agentmetadataevent.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, session.AgentMetadataEventsTable, session.AgentMetadataEventsColumn),
		)
		fromU = sqlgraph.SetNeighbors(sq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryCommitCheckpoints chains the current query on the "commit_checkpoints" edge.
func (sq *SessionQuery) QueryCommitCheckpoints() *CommitCheckpointQuery {
	query := (&CommitCheckpointClient{config: sq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := sq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := sq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(session.Table, session.FieldID, selector),
			sqlgraph.To(commitcheckpoint.Table, commitcheckpoint.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, session.CommitCheckpointsTable, session.CommitCheckpointsColumn),
		)
		fromU = sqlgraph.SetNeighbors(sq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryCommitRewrites chains the current query on the "commit_rewrites" edge.
func (sq *SessionQuery) QueryCommitRewrites() *CommitRewriteQuery {
	query := (&CommitRewriteClient{config: sq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := sq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := sq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(session.Table, session.FieldID, selector),
			sqlgraph.To(commitrewrite.Table, commitrewrite.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, session.CommitRewritesTable, session.CommitRewritesColumn),
		)
		fromU = sqlgraph.SetNeighbors(sq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Session entity from the query.
// Returns a *NotFoundError when no Session was found.
func (sq *SessionQuery) First(ctx context.Context) (*Session, error) {
	nodes, err := sq.Limit(1).All(setContextOp(ctx, sq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{session.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (sq *SessionQuery) FirstX(ctx context.Context) *Session {
	node, err := sq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Session ID from the query.
// Returns a *NotFoundError when no Session ID was found.
func (sq *SessionQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = sq.Limit(1).IDs(setContextOp(ctx, sq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{session.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (sq *SessionQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := sq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Session entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Session entity is found.
// Returns a *NotFoundError when no Session entities are found.
func (sq *SessionQuery) Only(ctx context.Context) (*Session, error) {
	nodes, err := sq.Limit(2).All(setContextOp(ctx, sq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{session.Label}
	default:
		return nil, &NotSingularError{session.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (sq *SessionQuery) OnlyX(ctx context.Context) *Session {
	node, err := sq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Session ID in the query.
// Returns a *NotSingularError when more than one Session ID is found.
// Returns a *NotFoundError when no entities are found.
func (sq *SessionQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = sq.Limit(2).IDs(setContextOp(ctx, sq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{session.Label}
	default:
		err = &NotSingularError{session.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (sq *SessionQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := sq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Sessions.
func (sq *SessionQuery) All(ctx context.Context) ([]*Session, error) {
	ctx = setContextOp(ctx, sq.ctx, ent.OpQueryAll)
	if err := sq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Session, *SessionQuery]()
	return withInterceptors[[]*Session](ctx, sq, qr, sq.inters)
}

// AllX is like All, but panics if an error occurs.
func (sq *SessionQuery) AllX(ctx context.Context) []*Session {
	nodes, err := sq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Session IDs.
func (sq *SessionQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if sq.ctx.Unique == nil && sq.path != nil {
		sq.Unique(true)
	}
	ctx = setContextOp(ctx, sq.ctx, ent.OpQueryIDs)
	if err = sq.Select(session.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (sq *SessionQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := sq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (sq *SessionQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, sq.ctx, ent.OpQueryCount)
	if err := sq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, sq, querierCount[*SessionQuery](), sq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (sq *SessionQuery) CountX(ctx context.Context) int {
	count, err := sq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (sq *SessionQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, sq.ctx, ent.OpQueryExist)
	switch _, err := sq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (sq *SessionQuery) ExistX(ctx context.Context) bool {
	exist, err := sq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the SessionQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (sq *SessionQuery) Clone() *SessionQuery {
	if sq == nil {
		return nil
	}
	return &SessionQuery{
		config:                  sq.config,
		ctx:                     sq.ctx.Clone(),
		order:                   append([]session.OrderOption{}, sq.order...),
		inters:                  append([]Interceptor{}, sq.inters...),
		predicates:              append([]predicate.Session{}, sq.predicates...),
		withRepoConfig:          sq.withRepoConfig.Clone(),
		withUser:                sq.withUser.Clone(),
		withSessionWorkspaces:   sq.withSessionWorkspaces.Clone(),
		withAgentMetadataEvents: sq.withAgentMetadataEvents.Clone(),
		withCommitCheckpoints:   sq.withCommitCheckpoints.Clone(),
		withCommitRewrites:      sq.withCommitRewrites.Clone(),
		// clone intermediate query.
		sql:  sq.sql.Clone(),
		path: sq.path,
	}
}

// WithRepoConfig tells the query-builder to eager-load the nodes that are connected to
// the "repo_config" edge. The optional arguments are used to configure the query builder of the edge.
func (sq *SessionQuery) WithRepoConfig(opts ...func(*RepoConfigQuery)) *SessionQuery {
	query := (&RepoConfigClient{config: sq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	sq.withRepoConfig = query
	return sq
}

// WithUser tells the query-builder to eager-load the nodes that are connected to
// the "user" edge. The optional arguments are used to configure the query builder of the edge.
func (sq *SessionQuery) WithUser(opts ...func(*UserQuery)) *SessionQuery {
	query := (&UserClient{config: sq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	sq.withUser = query
	return sq
}

// WithSessionWorkspaces tells the query-builder to eager-load the nodes that are connected to
// the "session_workspaces" edge. The optional arguments are used to configure the query builder of the edge.
func (sq *SessionQuery) WithSessionWorkspaces(opts ...func(*SessionWorkspaceQuery)) *SessionQuery {
	query := (&SessionWorkspaceClient{config: sq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	sq.withSessionWorkspaces = query
	return sq
}

// WithAgentMetadataEvents tells the query-builder to eager-load the nodes that are connected to
// the "agent_metadata_events" edge. The optional arguments are used to configure the query builder of the edge.
func (sq *SessionQuery) WithAgentMetadataEvents(opts ...func(*AgentMetadataEventQuery)) *SessionQuery {
	query := (&AgentMetadataEventClient{config: sq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	sq.withAgentMetadataEvents = query
	return sq
}

// WithCommitCheckpoints tells the query-builder to eager-load the nodes that are connected to
// the "commit_checkpoints" edge. The optional arguments are used to configure the query builder of the edge.
func (sq *SessionQuery) WithCommitCheckpoints(opts ...func(*CommitCheckpointQuery)) *SessionQuery {
	query := (&CommitCheckpointClient{config: sq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	sq.withCommitCheckpoints = query
	return sq
}

// WithCommitRewrites tells the query-builder to eager-load the nodes that are connected to
// the "commit_rewrites" edge. The optional arguments are used to configure the query builder of the edge.
func (sq *SessionQuery) WithCommitRewrites(opts ...func(*CommitRewriteQuery)) *SessionQuery {
	query := (&CommitRewriteClient{config: sq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	sq.withCommitRewrites = query
	return sq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Branch string `json:"branch,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Session.Query().
//		GroupBy(session.FieldBranch).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (sq *SessionQuery) GroupBy(field string, fields ...string) *SessionGroupBy {
	sq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &SessionGroupBy{build: sq}
	grbuild.flds = &sq.ctx.Fields
	grbuild.label = session.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Branch string `json:"branch,omitempty"`
//	}
//
//	client.Session.Query().
//		Select(session.FieldBranch).
//		Scan(ctx, &v)
func (sq *SessionQuery) Select(fields ...string) *SessionSelect {
	sq.ctx.Fields = append(sq.ctx.Fields, fields...)
	sbuild := &SessionSelect{SessionQuery: sq}
	sbuild.label = session.Label
	sbuild.flds, sbuild.scan = &sq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a SessionSelect configured with the given aggregations.
func (sq *SessionQuery) Aggregate(fns ...AggregateFunc) *SessionSelect {
	return sq.Select().Aggregate(fns...)
}

func (sq *SessionQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range sq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, sq); err != nil {
				return err
			}
		}
	}
	for _, f := range sq.ctx.Fields {
		if !session.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if sq.path != nil {
		prev, err := sq.path(ctx)
		if err != nil {
			return err
		}
		sq.sql = prev
	}
	return nil
}

func (sq *SessionQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Session, error) {
	var (
		nodes       = []*Session{}
		withFKs     = sq.withFKs
		_spec       = sq.querySpec()
		loadedTypes = [6]bool{
			sq.withRepoConfig != nil,
			sq.withUser != nil,
			sq.withSessionWorkspaces != nil,
			sq.withAgentMetadataEvents != nil,
			sq.withCommitCheckpoints != nil,
			sq.withCommitRewrites != nil,
		}
	)
	if sq.withRepoConfig != nil || sq.withUser != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, session.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Session).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Session{config: sq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, sq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := sq.withRepoConfig; query != nil {
		if err := sq.loadRepoConfig(ctx, query, nodes, nil,
			func(n *Session, e *RepoConfig) { n.Edges.RepoConfig = e }); err != nil {
			return nil, err
		}
	}
	if query := sq.withUser; query != nil {
		if err := sq.loadUser(ctx, query, nodes, nil,
			func(n *Session, e *User) { n.Edges.User = e }); err != nil {
			return nil, err
		}
	}
	if query := sq.withSessionWorkspaces; query != nil {
		if err := sq.loadSessionWorkspaces(ctx, query, nodes,
			func(n *Session) { n.Edges.SessionWorkspaces = []*SessionWorkspace{} },
			func(n *Session, e *SessionWorkspace) {
				n.Edges.SessionWorkspaces = append(n.Edges.SessionWorkspaces, e)
			}); err != nil {
			return nil, err
		}
	}
	if query := sq.withAgentMetadataEvents; query != nil {
		if err := sq.loadAgentMetadataEvents(ctx, query, nodes,
			func(n *Session) { n.Edges.AgentMetadataEvents = []*AgentMetadataEvent{} },
			func(n *Session, e *AgentMetadataEvent) {
				n.Edges.AgentMetadataEvents = append(n.Edges.AgentMetadataEvents, e)
			}); err != nil {
			return nil, err
		}
	}
	if query := sq.withCommitCheckpoints; query != nil {
		if err := sq.loadCommitCheckpoints(ctx, query, nodes,
			func(n *Session) { n.Edges.CommitCheckpoints = []*CommitCheckpoint{} },
			func(n *Session, e *CommitCheckpoint) {
				n.Edges.CommitCheckpoints = append(n.Edges.CommitCheckpoints, e)
			}); err != nil {
			return nil, err
		}
	}
	if query := sq.withCommitRewrites; query != nil {
		if err := sq.loadCommitRewrites(ctx, query, nodes,
			func(n *Session) { n.Edges.CommitRewrites = []*CommitRewrite{} },
			func(n *Session, e *CommitRewrite) { n.Edges.CommitRewrites = append(n.Edges.CommitRewrites, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (sq *SessionQuery) loadRepoConfig(ctx context.Context, query *RepoConfigQuery, nodes []*Session, init func(*Session), assign func(*Session, *RepoConfig)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*Session)
	for i := range nodes {
		if nodes[i].repo_config_sessions == nil {
			continue
		}
		fk := *nodes[i].repo_config_sessions
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(repoconfig.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "repo_config_sessions" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (sq *SessionQuery) loadUser(ctx context.Context, query *UserQuery, nodes []*Session, init func(*Session), assign func(*Session, *User)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*Session)
	for i := range nodes {
		if nodes[i].user_sessions == nil {
			continue
		}
		fk := *nodes[i].user_sessions
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "user_sessions" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (sq *SessionQuery) loadSessionWorkspaces(ctx context.Context, query *SessionWorkspaceQuery, nodes []*Session, init func(*Session), assign func(*Session, *SessionWorkspace)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*Session)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(sessionworkspace.FieldSessionID)
	}
	query.Where(predicate.SessionWorkspace(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(session.SessionWorkspacesColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.SessionID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "session_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (sq *SessionQuery) loadAgentMetadataEvents(ctx context.Context, query *AgentMetadataEventQuery, nodes []*Session, init func(*Session), assign func(*Session, *AgentMetadataEvent)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*Session)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(agentmetadataevent.FieldSessionID)
	}
	query.Where(predicate.AgentMetadataEvent(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(session.AgentMetadataEventsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.SessionID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "session_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (sq *SessionQuery) loadCommitCheckpoints(ctx context.Context, query *CommitCheckpointQuery, nodes []*Session, init func(*Session), assign func(*Session, *CommitCheckpoint)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*Session)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(commitcheckpoint.FieldSessionID)
	}
	query.Where(predicate.CommitCheckpoint(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(session.CommitCheckpointsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.SessionID
		if fk == nil {
			return fmt.Errorf(`foreign-key "session_id" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "session_id" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (sq *SessionQuery) loadCommitRewrites(ctx context.Context, query *CommitRewriteQuery, nodes []*Session, init func(*Session), assign func(*Session, *CommitRewrite)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*Session)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(commitrewrite.FieldSessionID)
	}
	query.Where(predicate.CommitRewrite(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(session.CommitRewritesColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.SessionID
		if fk == nil {
			return fmt.Errorf(`foreign-key "session_id" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "session_id" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (sq *SessionQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := sq.querySpec()
	_spec.Node.Columns = sq.ctx.Fields
	if len(sq.ctx.Fields) > 0 {
		_spec.Unique = sq.ctx.Unique != nil && *sq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, sq.driver, _spec)
}

func (sq *SessionQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(session.Table, session.Columns, sqlgraph.NewFieldSpec(session.FieldID, field.TypeUUID))
	_spec.From = sq.sql
	if unique := sq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if sq.path != nil {
		_spec.Unique = true
	}
	if fields := sq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, session.FieldID)
		for i := range fields {
			if fields[i] != session.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := sq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := sq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := sq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := sq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (sq *SessionQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(sq.driver.Dialect())
	t1 := builder.Table(session.Table)
	columns := sq.ctx.Fields
	if len(columns) == 0 {
		columns = session.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if sq.sql != nil {
		selector = sq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if sq.ctx.Unique != nil && *sq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range sq.predicates {
		p(selector)
	}
	for _, p := range sq.order {
		p(selector)
	}
	if offset := sq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := sq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// SessionGroupBy is the group-by builder for Session entities.
type SessionGroupBy struct {
	selector
	build *SessionQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (sgb *SessionGroupBy) Aggregate(fns ...AggregateFunc) *SessionGroupBy {
	sgb.fns = append(sgb.fns, fns...)
	return sgb
}

// Scan applies the selector query and scans the result into the given value.
func (sgb *SessionGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, sgb.build.ctx, ent.OpQueryGroupBy)
	if err := sgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SessionQuery, *SessionGroupBy](ctx, sgb.build, sgb, sgb.build.inters, v)
}

func (sgb *SessionGroupBy) sqlScan(ctx context.Context, root *SessionQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(sgb.fns))
	for _, fn := range sgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*sgb.flds)+len(sgb.fns))
		for _, f := range *sgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*sgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := sgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// SessionSelect is the builder for selecting fields of Session entities.
type SessionSelect struct {
	*SessionQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ss *SessionSelect) Aggregate(fns ...AggregateFunc) *SessionSelect {
	ss.fns = append(ss.fns, fns...)
	return ss
}

// Scan applies the selector query and scans the result into the given value.
func (ss *SessionSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ss.ctx, ent.OpQuerySelect)
	if err := ss.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SessionQuery, *SessionSelect](ctx, ss.SessionQuery, ss, ss.inters, v)
}

func (ss *SessionSelect) sqlScan(ctx context.Context, root *SessionQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(ss.fns))
	for _, fn := range ss.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*ss.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ss.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
