// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ai-efficiency/backend/ent/predicate"
	"github.com/ai-efficiency/backend/ent/repoconfig"
	"github.com/ai-efficiency/backend/ent/webhookdeadletter"
)

// WebhookDeadLetterUpdate is the builder for updating WebhookDeadLetter entities.
type WebhookDeadLetterUpdate struct {
	config
	hooks    []Hook
	mutation *WebhookDeadLetterMutation
}

// Where appends a list predicates to the WebhookDeadLetterUpdate builder.
func (wdlu *WebhookDeadLetterUpdate) Where(ps ...predicate.WebhookDeadLetter) *WebhookDeadLetterUpdate {
	wdlu.mutation.Where(ps...)
	return wdlu
}

// SetDeliveryID sets the "delivery_id" field.
func (wdlu *WebhookDeadLetterUpdate) SetDeliveryID(s string) *WebhookDeadLetterUpdate {
	wdlu.mutation.SetDeliveryID(s)
	return wdlu
}

// SetNillableDeliveryID sets the "delivery_id" field if the given value is not nil.
func (wdlu *WebhookDeadLetterUpdate) SetNillableDeliveryID(s *string) *WebhookDeadLetterUpdate {
	if s != nil {
		wdlu.SetDeliveryID(*s)
	}
	return wdlu
}

// SetEventType sets the "event_type" field.
func (wdlu *WebhookDeadLetterUpdate) SetEventType(s string) *WebhookDeadLetterUpdate {
	wdlu.mutation.SetEventType(s)
	return wdlu
}

// SetNillableEventType sets the "event_type" field if the given value is not nil.
func (wdlu *WebhookDeadLetterUpdate) SetNillableEventType(s *string) *WebhookDeadLetterUpdate {
	if s != nil {
		wdlu.SetEventType(*s)
	}
	return wdlu
}

// SetPayload sets the "payload" field.
func (wdlu *WebhookDeadLetterUpdate) SetPayload(m map[string]interface{}) *WebhookDeadLetterUpdate {
	wdlu.mutation.SetPayload(m)
	return wdlu
}

// SetErrorMessage sets the "error_message" field.
func (wdlu *WebhookDeadLetterUpdate) SetErrorMessage(s string) *WebhookDeadLetterUpdate {
	wdlu.mutation.SetErrorMessage(s)
	return wdlu
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (wdlu *WebhookDeadLetterUpdate) SetNillableErrorMessage(s *string) *WebhookDeadLetterUpdate {
	if s != nil {
		wdlu.SetErrorMessage(*s)
	}
	return wdlu
}

// SetRetryCount sets the "retry_count" field.
func (wdlu *WebhookDeadLetterUpdate) SetRetryCount(i int) *WebhookDeadLetterUpdate {
	wdlu.mutation.ResetRetryCount()
	wdlu.mutation.SetRetryCount(i)
	return wdlu
}

// SetNillableRetryCount sets the "retry_count" field if the given value is not nil.
func (wdlu *WebhookDeadLetterUpdate) SetNillableRetryCount(i *int) *WebhookDeadLetterUpdate {
	if i != nil {
		wdlu.SetRetryCount(*i)
	}
	return wdlu
}

// AddRetryCount adds i to the "retry_count" field.
func (wdlu *WebhookDeadLetterUpdate) AddRetryCount(i int) *WebhookDeadLetterUpdate {
	wdlu.mutation.AddRetryCount(i)
	return wdlu
}

// SetMaxRetries sets the "max_retries" field.
func (wdlu *WebhookDeadLetterUpdate) SetMaxRetries(i int) *WebhookDeadLetterUpdate {
	wdlu.mutation.ResetMaxRetries()
	wdlu.mutation.SetMaxRetries(i)
	return wdlu
}

// SetNillableMaxRetries sets the "max_retries" field if the given value is not nil.
func (wdlu *WebhookDeadLetterUpdate) SetNillableMaxRetries(i *int) *WebhookDeadLetterUpdate {
	if i != nil {
		wdlu.SetMaxRetries(*i)
	}
	return wdlu
}

// AddMaxRetries adds i to the "max_retries" field.
func (wdlu *WebhookDeadLetterUpdate) AddMaxRetries(i int) *WebhookDeadLetterUpdate {
	wdlu.mutation.AddMaxRetries(i)
	return wdlu
}

// SetStatus sets the "status" field.
func (wdlu *WebhookDeadLetterUpdate) SetStatus(w webhookdeadletter.Status) *WebhookDeadLetterUpdate {
	wdlu.mutation.SetStatus(w)
	return wdlu
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (wdlu *WebhookDeadLetterUpdate) SetNillableStatus(w *webhookdeadletter.Status) *WebhookDeadLetterUpdate {
	if w != nil {
		wdlu.SetStatus(*w)
	}
	return wdlu
}

// SetResolvedAt sets the "resolved_at" field.
func (wdlu *WebhookDeadLetterUpdate) SetResolvedAt(t time.Time) *WebhookDeadLetterUpdate {
	wdlu.mutation.SetResolvedAt(t)
	return wdlu
}

// SetNillableResolvedAt sets the "resolved_at" field if the given value is not nil.
func (wdlu *WebhookDeadLetterUpdate) SetNillableResolvedAt(t *time.Time) *WebhookDeadLetterUpdate {
	if t != nil {
		wdlu.SetResolvedAt(*t)
	}
	return wdlu
}

// ClearResolvedAt clears the value of the "resolved_at" field.
func (wdlu *WebhookDeadLetterUpdate) ClearResolvedAt() *WebhookDeadLetterUpdate {
	wdlu.mutation.ClearResolvedAt()
	return wdlu
}

// SetRepoConfigID sets the "repo_config" edge to the RepoConfig entity by ID.
func (wdlu *WebhookDeadLetterUpdate) SetRepoConfigID(id int) *WebhookDeadLetterUpdate {
	wdlu.mutation.SetRepoConfigID(id)
	return wdlu
}

// SetRepoConfig sets the "repo_config" edge to the RepoConfig entity.
func (wdlu *WebhookDeadLetterUpdate) SetRepoConfig(r *RepoConfig) *WebhookDeadLetterUpdate {
	return wdlu.SetRepoConfigID(r.ID)
}

// Mutation returns the WebhookDeadLetterMutation object of the builder.
func (wdlu *WebhookDeadLetterUpdate) Mutation() *WebhookDeadLetterMutation {
	return wdlu.mutation
}

// ClearRepoConfig clears the "repo_config" edge to the RepoConfig entity.
func (wdlu *WebhookDeadLetterUpdate) ClearRepoConfig() *WebhookDeadLetterUpdate {
	wdlu.mutation.ClearRepoConfig()
	return wdlu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (wdlu *WebhookDeadLetterUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, wdlu.sqlSave, wdlu.mutation, wdlu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (wdlu *WebhookDeadLetterUpdate) SaveX(ctx context.Context) int {
	affected, err := wdlu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (wdlu *WebhookDeadLetterUpdate) Exec(ctx context.Context) error {
	_, err := wdlu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (wdlu *WebhookDeadLetterUpdate) ExecX(ctx context.Context) {
	if err := wdlu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (wdlu *WebhookDeadLetterUpdate) check() error {
	if v, ok := wdlu.mutation.DeliveryID(); ok {
		if err := webhookdeadletter.DeliveryIDValidator(v); err != nil {
			return &ValidationError{Name: "delivery_id", err: fmt.Errorf(`ent: validator failed for field "WebhookDeadLetter.delivery_id": %w`, err)}
		}
	}
	if v, ok := wdlu.mutation.EventType(); ok {
		if err := webhookdeadletter.EventTypeValidator(v); err != nil {
			return &ValidationError{Name: "event_type", err: fmt.Errorf(`ent: validator failed for field "WebhookDeadLetter.event_type": %w`, err)}
		}
	}
	if v, ok := wdlu.mutation.Status(); ok {
		if err := webhookdeadletter.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "WebhookDeadLetter.status": %w`, err)}
		}
	}
	if wdlu.mutation.RepoConfigCleared() && len(wdlu.mutation.RepoConfigIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "WebhookDeadLetter.repo_config"`)
	}
	return nil
}

func (wdlu *WebhookDeadLetterUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := wdlu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(webhookdeadletter.Table, webhookdeadletter.Columns, sqlgraph.NewFieldSpec(webhookdeadletter.FieldID, field.TypeInt))
	if ps := wdlu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := wdlu.mutation.DeliveryID(); ok {
		_spec.SetField(webhookdeadletter.FieldDeliveryID, field.TypeString, value)
	}
	if value, ok := wdlu.mutation.EventType(); ok {
		_spec.SetField(webhookdeadletter.FieldEventType, field.TypeString, value)
	}
	if value, ok := wdlu.mutation.Payload(); ok {
		_spec.SetField(webhookdeadletter.FieldPayload, field.TypeJSON, value)
	}
	if value, ok := wdlu.mutation.ErrorMessage(); ok {
		_spec.SetField(webhookdeadletter.FieldErrorMessage, field.TypeString, value)
	}
	if value, ok := wdlu.mutation.RetryCount(); ok {
		_spec.SetField(webhookdeadletter.FieldRetryCount, field.TypeInt, value)
	}
	if value, ok := wdlu.mutation.AddedRetryCount(); ok {
		_spec.AddField(webhookdeadletter.FieldRetryCount, field.TypeInt, value)
	}
	if value, ok := wdlu.mutation.MaxRetries(); ok {
		_spec.SetField(webhookdeadletter.FieldMaxRetries, field.TypeInt, value)
	}
	if value, ok := wdlu.mutation.AddedMaxRetries(); ok {
		_spec.AddField(webhookdeadletter.FieldMaxRetries, field.TypeInt, value)
	}
	if value, ok := wdlu.mutation.Status(); ok {
		_spec.SetField(webhookdeadletter.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := wdlu.mutation.ResolvedAt(); ok {
		_spec.SetField(webhookdeadletter.FieldResolvedAt, field.TypeTime, value)
	}
	if wdlu.mutation.ResolvedAtCleared() {
		_spec.ClearField(webhookdeadletter.FieldResolvedAt, field.TypeTime)
	}
	if wdlu.mutation.RepoConfigCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   webhookdeadletter.RepoConfigTable,
			Columns: []string{webhookdeadletter.RepoConfigColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(repoconfig.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := wdlu.mutation.RepoConfigIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   webhookdeadletter.RepoConfigTable,
			Columns: []string{webhookdeadletter.RepoConfigColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(repoconfig.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, wdlu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{webhookdeadletter.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	wdlu.mutation.done = true
	return n, nil
}

// WebhookDeadLetterUpdateOne is the builder for updating a single WebhookDeadLetter entity.
type WebhookDeadLetterUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *WebhookDeadLetterMutation
}

// SetDeliveryID sets the "delivery_id" field.
func (wdluo *WebhookDeadLetterUpdateOne) SetDeliveryID(s string) *WebhookDeadLetterUpdateOne {
	wdluo.mutation.SetDeliveryID(s)
	return wdluo
}

// SetNillableDeliveryID sets the "delivery_id" field if the given value is not nil.
func (wdluo *WebhookDeadLetterUpdateOne) SetNillableDeliveryID(s *string) *WebhookDeadLetterUpdateOne {
	if s != nil {
		wdluo.SetDeliveryID(*s)
	}
	return wdluo
}

// SetEventType sets the "event_type" field.
func (wdluo *WebhookDeadLetterUpdateOne) SetEventType(s string) *WebhookDeadLetterUpdateOne {
	wdluo.mutation.SetEventType(s)
	return wdluo
}

// SetNillableEventType sets the "event_type" field if the given value is not nil.
func (wdluo *WebhookDeadLetterUpdateOne) SetNillableEventType(s *string) *WebhookDeadLetterUpdateOne {
	if s != nil {
		wdluo.SetEventType(*s)
	}
	return wdluo
}

// SetPayload sets the "payload" field.
func (wdluo *WebhookDeadLetterUpdateOne) SetPayload(m map[string]interface{}) *WebhookDeadLetterUpdateOne {
	wdluo.mutation.SetPayload(m)
	return wdluo
}

// SetErrorMessage sets the "error_message" field.
func (wdluo *WebhookDeadLetterUpdateOne) SetErrorMessage(s string) *WebhookDeadLetterUpdateOne {
	wdluo.mutation.SetErrorMessage(s)
	return wdluo
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (wdluo *WebhookDeadLetterUpdateOne) SetNillableErrorMessage(s *string) *WebhookDeadLetterUpdateOne {
	if s != nil {
		wdluo.SetErrorMessage(*s)
	}
	return wdluo
}

// SetRetryCount sets the "retry_count" field.
func (wdluo *WebhookDeadLetterUpdateOne) SetRetryCount(i int) *WebhookDeadLetterUpdateOne {
	wdluo.mutation.ResetRetryCount()
	wdluo.mutation.SetRetryCount(i)
	return wdluo
}

// SetNillableRetryCount sets the "retry_count" field if the given value is not nil.
func (wdluo *WebhookDeadLetterUpdateOne) SetNillableRetryCount(i *int) *WebhookDeadLetterUpdateOne {
	if i != nil {
		wdluo.SetRetryCount(*i)
	}
	return wdluo
}

// AddRetryCount adds i to the "retry_count" field.
func (wdluo *WebhookDeadLetterUpdateOne) AddRetryCount(i int) *WebhookDeadLetterUpdateOne {
	wdluo.mutation.AddRetryCount(i)
	return wdluo
}

// SetMaxRetries sets the "max_retries" field.
func (wdluo *WebhookDeadLetterUpdateOne) SetMaxRetries(i int) *WebhookDeadLetterUpdateOne {
	wdluo.mutation.ResetMaxRetries()
	wdluo.mutation.SetMaxRetries(i)
	return wdluo
}

// SetNillableMaxRetries sets the "max_retries" field if the given value is not nil.
func (wdluo *WebhookDeadLetterUpdateOne) SetNillableMaxRetries(i *int) *WebhookDeadLetterUpdateOne {
	if i != nil {
		wdluo.SetMaxRetries(*i)
	}
	return wdluo
}

// AddMaxRetries adds i to the "max_retries" field.
func (wdluo *WebhookDeadLetterUpdateOne) AddMaxRetries(i int) *WebhookDeadLetterUpdateOne {
	wdluo.mutation.AddMaxRetries(i)
	return wdluo
}

// SetStatus sets the "status" field.
func (wdluo *WebhookDeadLetterUpdateOne) SetStatus(w webhookdeadletter.Status) *WebhookDeadLetterUpdateOne {
	wdluo.mutation.SetStatus(w)
	return wdluo
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (wdluo *WebhookDeadLetterUpdateOne) SetNillableStatus(w *webhookdeadletter.Status) *WebhookDeadLetterUpdateOne {
	if w != nil {
		wdluo.SetStatus(*w)
	}
	return wdluo
}

// SetResolvedAt sets the "resolved_at" field.
func (wdluo *WebhookDeadLetterUpdateOne) SetResolvedAt(t time.Time) *WebhookDeadLetterUpdateOne {
	wdluo.mutation.SetResolvedAt(t)
	return wdluo
}

// SetNillableResolvedAt sets the "resolved_at" field if the given value is not nil.
func (wdluo *WebhookDeadLetterUpdateOne) SetNillableResolvedAt(t *time.Time) *WebhookDeadLetterUpdateOne {
	if t != nil {
		wdluo.SetResolvedAt(*t)
	}
	return wdluo
}

// ClearResolvedAt clears the value of the "resolved_at" field.
func (wdluo *WebhookDeadLetterUpdateOne) ClearResolvedAt() *WebhookDeadLetterUpdateOne {
	wdluo.mutation.ClearResolvedAt()
	return wdluo
}

// SetRepoConfigID sets the "repo_config" edge to the RepoConfig entity by ID.
func (wdluo *WebhookDeadLetterUpdateOne) SetRepoConfigID(id int) *WebhookDeadLetterUpdateOne {
	wdluo.mutation.SetRepoConfigID(id)
	return wdluo
}

// SetRepoConfig sets the "repo_config" edge to the RepoConfig entity.
func (wdluo *WebhookDeadLetterUpdateOne) SetRepoConfig(r *RepoConfig) *WebhookDeadLetterUpdateOne {
	return wdluo.SetRepoConfigID(r.ID)
}

// Mutation returns the WebhookDeadLetterMutation object of the builder.
func (wdluo *WebhookDeadLetterUpdateOne) Mutation() *WebhookDeadLetterMutation {
	return wdluo.mutation
}

// ClearRepoConfig clears the "repo_config" edge to the RepoConfig entity.
func (wdluo *WebhookDeadLetterUpdateOne) ClearRepoConfig() *WebhookDeadLetterUpdateOne {
	wdluo.mutation.ClearRepoConfig()
	return wdluo
}

// Where appends a list predicates to the WebhookDeadLetterUpdate builder.
func (wdluo *WebhookDeadLetterUpdateOne) Where(ps ...predicate.WebhookDeadLetter) *WebhookDeadLetterUpdateOne {
	wdluo.mutation.Where(ps...)
	return wdluo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (wdluo *WebhookDeadLetterUpdateOne) Select(field string, fields ...string) *WebhookDeadLetterUpdateOne {
	wdluo.fields = append([]string{field}, fields...)
	return wdluo
}

// Save executes the query and returns the updated WebhookDeadLetter entity.
func (wdluo *WebhookDeadLetterUpdateOne) Save(ctx context.Context) (*WebhookDeadLetter, error) {
	return withHooks(ctx, wdluo.sqlSave, wdluo.mutation, wdluo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (wdluo *WebhookDeadLetterUpdateOne) SaveX(ctx context.Context) *WebhookDeadLetter {
	node, err := wdluo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (wdluo *WebhookDeadLetterUpdateOne) Exec(ctx context.Context) error {
	_, err := wdluo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (wdluo *WebhookDeadLetterUpdateOne) ExecX(ctx context.Context) {
	if err := wdluo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (wdluo *WebhookDeadLetterUpdateOne) check() error {
	if v, ok := wdluo.mutation.DeliveryID(); ok {
		if err := webhookdeadletter.DeliveryIDValidator(v); err != nil {
			return &ValidationError{Name: "delivery_id", err: fmt.Errorf(`ent: validator failed for field "WebhookDeadLetter.delivery_id": %w`, err)}
		}
	}
	if v, ok := wdluo.mutation.EventType(); ok {
		if err := webhookdeadletter.EventTypeValidator(v); err != nil {
			return &ValidationError{Name: "event_type", err: fmt.Errorf(`ent: validator failed for field "WebhookDeadLetter.event_type": %w`, err)}
		}
	}
	if v, ok := wdluo.mutation.Status(); ok {
		if err := webhookdeadletter.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "WebhookDeadLetter.status": %w`, err)}
		}
	}
	if wdluo.mutation.RepoConfigCleared() && len(wdluo.mutation.RepoConfigIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "WebhookDeadLetter.repo_config"`)
	}
	return nil
}

func (wdluo *WebhookDeadLetterUpdateOne) sqlSave(ctx context.Context) (_node *WebhookDeadLetter, err error) {
	if err := wdluo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(webhookdeadletter.Table, webhookdeadletter.Columns, sqlgraph.NewFieldSpec(webhookdeadletter.FieldID, field.TypeInt))
	id, ok := wdluo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "WebhookDeadLetter.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := wdluo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, webhookdeadletter.FieldID)
		for _, f := range fields {
			if !webhookdeadletter.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != webhookdeadletter.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := wdluo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := wdluo.mutation.DeliveryID(); ok {
		_spec.SetField(webhookdeadletter.FieldDeliveryID, field.TypeString, value)
	}
	if value, ok := wdluo.mutation.EventType(); ok {
		_spec.SetField(webhookdeadletter.FieldEventType, field.TypeString, value)
	}
	if value, ok := wdluo.mutation.Payload(); ok {
		_spec.SetField(webhookdeadletter.FieldPayload, field.TypeJSON, value)
	}
	if value, ok := wdluo.mutation.ErrorMessage(); ok {
		_spec.SetField(webhookdeadletter.FieldErrorMessage, field.TypeString, value)
	}
	if value, ok := wdluo.mutation.RetryCount(); ok {
		_spec.SetField(webhookdeadletter.FieldRetryCount, field.TypeInt, value)
	}
	if value, ok := wdluo.mutation.AddedRetryCount(); ok {
		_spec.AddField(webhookdeadletter.FieldRetryCount, field.TypeInt, value)
	}
	if value, ok := wdluo.mutation.MaxRetries(); ok {
		_spec.SetField(webhookdeadletter.FieldMaxRetries, field.TypeInt, value)
	}
	if value, ok := wdluo.mutation.AddedMaxRetries(); ok {
		_spec.AddField(webhookdeadletter.FieldMaxRetries, field.TypeInt, value)
	}
	if value, ok := wdluo.mutation.Status(); ok {
		_spec.SetField(webhookdeadletter.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := wdluo.mutation.ResolvedAt(); ok {
		_spec.SetField(webhookdeadletter.FieldResolvedAt, field.TypeTime, value)
	}
	if wdluo.mutation.ResolvedAtCleared() {
		_spec.ClearField(webhookdeadletter.FieldResolvedAt, field.TypeTime)
	}
	if wdluo.mutation.RepoConfigCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   webhookdeadletter.RepoConfigTable,
			Columns: []string{webhookdeadletter.RepoConfigColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(repoconfig.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := wdluo.mutation.RepoConfigIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   webhookdeadletter.RepoConfigTable,
			Columns: []string{webhookdeadletter.RepoConfigColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(repoconfig.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &WebhookDeadLetter{config: wdluo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, wdluo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{webhookdeadletter.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	wdluo.mutation.done = true
	return _node, nil
}
